### ISSUE TITLE
MPRIS integration displaying twice in Ubuntu 21.10 notification centre

### ISSUE THREAD

**Issue by JamyGolden** [Mastermindzh/tidal-hifi#100]
This is happening for me on Ubuntu 21.10 having installed the `tidal-hifi_2.7.1_amd64.deb` package.

Not something I care too much about but I noticed this and thought it might be useful to mention here.

![Screenshot from 2022-02-01 12-08-55](https://user-images.githubusercontent.com/602472/151958266-674d4ac2-71a1-4929-be3f-a3c4f4393b63.png)

**Comment by Mastermindzh** [comment]
Hey @JamyGolden,

That is Gnome right?
It picks up both the custom mpris (the one with a picture) and the "chrome" instance's audio (second one).

There is not too much we can do from a Tidal-HiFi perspective (or so I thought) but maybe aligning the instance name (our other discussion) with the app (/mpris) name might make Gnome behave 😄 

Thanks for sharing!

**Comment by JamyGolden** [comment]
Great! Yeah on Gnome. I'll close this then since it is something you are aware of :smile:

**Comment by fatalhare** [comment]
Sorry to revive a closed issue - I had the same problem, running gnome 42 on arch linux. I was able to fix this by adding 

`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling');`

to `main.js` and re-packaging. It prevents chrome from creating its own default MPRIS instance in addition to the custom one.

**Comment by Mastermindzh** [comment]
Thanks for the tip! I will add a setting for that!
