### ISSUE TITLE
Tidal-HiFi not starting anymore since recent package update

### ISSUE THREAD

**Issue by Mar0xy** [Mastermindzh/tidal-hifi#102]
I have updated my packages yesterday and realized each time I go to open tidal-hifi it would close so I went and ran it in Terminal to see this
![image](https://user-images.githubusercontent.com/8841466/154075267-ee0ee750-a170-434a-9ff8-0ab470be91fb.png)

this is only happening with tidal-hifi as discord and other apps work just fine.

**Comment by Mar0xy** [comment]
Updating electron in package.json to v17.0.0+wvcus fixed this issue.

**Comment by lptnmachine** [comment]
This is happening for me too, after updating packages yesterday (on Arch)
When cloning the git repo and starting it from there it starts, but I can't play music. Building fails because libcrypt.so.1 is missing.

**Comment by yhager** [comment]
Same here, on arch the latest from aur is not working. The latest snap from the releases page *does* work thogh. 

For what it's worth, the web player is not working for me either, both on Firefox and Chrome.

**Comment by Mar0xy** [comment]
> Same here, on arch the latest from aur is not working. The latest snap from the releases page _does_ work thogh.
> 
> For what it's worth, the web player is not working for me either, both on Firefox and Chrome.

I have just been using the web player cause it works fine for me.

**Comment by Mar0xy** [comment]
Update on research: After looking around I found a old github issue talking about this issue and they suggested using the following flag `--disable-seccomp-filter-sandbox` after using that flag I can indeed start up the app like normal.
![image](https://user-images.githubusercontent.com/8841466/154264850-f6ce6b09-dc81-4409-a877-a7c5f5e17d29.png)

**Comment by Mar0xy** [comment]
I have now opened a PR(#104) which should fix this issue

**Comment by MateoCignetti** [comment]
Can confirm I have the same behaviour on my system and my brother's does behave the same as well. Launching tidal-hifi with the --disable-seccomp-filter-sandbox fixes the issue. Hopefully this gets fixed in the next update, thanks @Mar0xy !!

**Comment by Mastermindzh** [comment]
Well well well, I am unavailable for a few days and @Mar0xy fixes the issue again.
Thanks!

I will make sure it is included in the next release which will happen today!

**Comment by Mastermindzh** [comment]
The pr fixed it and version 2.7.2 has been released!
Thanks again!

**Comment by Lisoveliy** [comment]
Hi, problem is returned. `--disable-seccomp-filter-sandbox` fixes this issue. And removing `.config/tidal-hifi` directory also fixes this on first launch.
