### ISSUE TITLE
White screen on Login

### ISSUE THREAD

**Issue by kusma** [Mastermindzh/tidal-hifi#107]
When I try to press the "Log in" button on the start-screen, all I get is a white screen.

When I do the same from my web-browser, that button takes me to login.tidal.com. Perhaps that domain needs some sort of white-listing?

**Comment by Graphincer** [comment]
I'm also having the same issue.

**Comment by Graphincer** [comment]
Issue does not seem to be aparant on 2.7.1 for me though.

**Comment by Mastermindzh** [comment]
Great, seems fixed then 😄 !

**Comment by kusma** [comment]
Yep, seems to work fine now!
