### ISSUE TITLE
npm install on git repository not found electron

### ISSUE THREAD

**Issue by ljack1915** [Mastermindzh/tidal-hifi#110]
I cloned the latest repository and ran npm install, here is the error.

......
> electron@git+ssh://git@github.com/castlabs/electron-releases.git#8d8957ec0fae843760a583ed7a82e5d266fde647 postinstall /home/sherry/GitHub/tidal-hifi/node_modules/electron
> node install.js

HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v16.0.4/electron-v16.0.4-linux-x64.zip

**Comment by Mastermindzh** [comment]
Fixed in 3.0.0
