### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ghost** [Mastermindzh/tidal-hifi#12]
Just wondering, can you add FreeBSD support for this app? I attempted to clone your repo and install it on FreeBSD using `sudo npm install -g` after installing the `electron7` package from the FreeBSD package repositories and ran into this after `npm start`:

>> tidal-hifi@1.0.1 start /usr/home/varun/tidal-hifi
>> electron .
>
>App threw an error during load
>Error: Cannot find module 'electron-reload'
>Require stack:
>- /usr/home/varun/tidal-hifi/src/main.js
>- /usr/local/share/electron7/resources/default_app.asar/main.js
>-
>    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
>    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename >(electron/js2c/browser_init.js:7648:16)
>    at Module._load (internal/modules/cjs/loader.js:622:27)
>    at Module._load (electron/js2c/asar.js:717:26)
>    at Function.Module._load (electron/js2c/asar.js:717:26)
>    at Module.require (internal/modules/cjs/loader.js:775:19)
>    at require (internal/modules/cjs/helpers.js:68:18)
>    at Object.<anonymous> (/usr/home/varun/tidal-hifi/src/main.js:27:3)
>    at Module._compile (internal/modules/cjs/loader.js:880:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
>A JavaScript error occurred in the main process
>Uncaught Exception:
>Error: Cannot find module 'electron-reload'
>Require stack:
>- /usr/home/varun/tidal-hifi/src/main.js
>- /usr/local/share/electron7/resources/default_app.asar/main.js
>-
>    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
>    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename >(electron/js2c/browser_init.js:7648:16)
>    at Module._load (internal/modules/cjs/loader.js:622:27)
>    at Module._load (electron/js2c/asar.js:717:26)
>    at Function.Module._load (electron/js2c/asar.js:717:26)
>    at Module.require (internal/modules/cjs/loader.js:775:19)
>    at require (internal/modules/cjs/helpers.js:68:18)
>    at Object.<anonymous> (/usr/home/varun/tidal-hifi/src/main.js:27:3)
>    at Module._compile (internal/modules/cjs/loader.js:880:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)`

Weirdly enough I think the only error is that the electron-reload module is just not present in the FreeBSD version of electron7 from packages. But, is it possible?

**Comment by Mastermindzh** [comment]
Hello my friend!

Your question is twofold.

**1. Can I add FreeBSD support?**

well... I just uploaded a freebsd version to release 1.0.1 which you can download by clicking [here](https://github.com/Mastermindzh/tidal-hifi/releases/download/1.0.1/tidal-hifi-1.0.1.freebsd) :)
I will check if I can add it to the automatic Github builds as well.

Enjoy using the app!

**2. Why can't you run the source version.**

Well, you don't want to be installing anything globally (with the -g) flag to run this app. I set it up so all you need to do is install the dependencies in the local folder.

If you want to do that you can follow the [instructions from the readme](https://github.com/Mastermindzh/tidal-hifi/blob/1.0.1/README.md#L54-L61):

```sh

- git clone https://github.com/Mastermindzh/tidal-hifi.git
- cd tidal-hifi
- npm install
- npm start

```

**Comment by varun-narravula** [comment]
Got it, thanks! Love your app, music and DRM is the only thing that has kept me from using FreeBSD in its entirety

**Comment by Mastermindzh** [comment]
Mmm I'm using electron-builder to actually create the package so if it messes up I will have to take a look at it later, sorry.

**Comment by varun-narravula** [comment]
No worries, take your time. I'll mess with electron-build and see if I can do something.

**Comment by Mastermindzh** [comment]
Please do :) 
I have no FreeBSD system at the moment but I'll be able to set one up if need be.

Finding time is a bit hard at the moment though :P

PS: thanks for the kind words. DRM is unfortunately needed and platforms like Linux and FreeBSD are often forgotten by the big guys (tidal included)

**Comment by varun-narravula** [comment]
Haha yeah; everyone is using Widevine these days and I couldn't seem to get it running at all in the Linux compatibility layer, so that sucks, but in my experience Electron does somehow work with it so I'll see if I can build it tomorrow
