### ISSUE TITLE
Open existing Tidal window from desktop icon.

### ISSUE THREAD

**Issue by bageljrkhanofemus** [Mastermindzh/tidal-hifi#121]
So if Tidal is already running in the tray and I open it again, how do I get it to show the existing window rather than open another tray icon?
It works for other tray icons like discord, and I can patch the desktop file/wrapper command to do it if I knew the CLI command.

**Comment by Mastermindzh** [comment]
Hey @bageljrkhanofemus,

I can add a setting for this that is enabled by default.
I don't give out concrete release dates but it's certainly going to be implemented :D

Thanks!
