### ISSUE TITLE
Title of the song is not updating to MPRIS

### ISSUE THREAD

**Issue by Akselmo** [Mastermindzh/tidal-hifi#122]
Hi, I don't know how exactly this works but the song name won't update the song name to MPRIS, unless I manually select a song.

In other words, autoplay doesn't update the song name for MPRIS.

**Comment by Mastermindzh** [comment]
@Akselmo,

I've observed similar behavior for the past 2 weeks or so, but it happens at random times for me.
Thanks for the confirmation.

If you have the time, can you check whether the web API (can be enabled under settings) also stops reporting the correct info?
By default the API is available at: http://localhost:47836/current

Thanks!

**Comment by Akselmo** [comment]
I checked the API, it won't update there either.

**Comment by Mastermindzh** [comment]
@Akselmo,

We've just done a big update to Electron 15 in 3.0.0.
I'm hoping that also fixes this issue as I don't have a clue where it is coming from otherwise.

Let me know!

**Comment by Akselmo** [comment]
After some quick testing it seems to work now!
