### ISSUE TITLE
new installation: "Failed to install Widevine components"

### ISSUE THREAD

**Issue by daudo** [Mastermindzh/tidal-hifi#126]
I just had to reinstall my Manjaro gnome workstation and unfortunately, tidal doesn't want to start:

![tidal](https://user-images.githubusercontent.com/360141/164283273-717daa21-116f-46f5-8c10-ab1489076126.png)

This is really a brand new install and I've tried both the tidal-hifi-bin version in Manjaro https://aur.archlinux.org/packages/tidal-hifi-bin as well as the AppImage from the releases page https://github.com/Mastermindzh/tidal-hifi/releases

Unfortunately, it always ends up with that same error message.

**Comment by Mastermindzh** [comment]
Can you confirm whether the -git version also has the issue?

**Comment by daudo** [comment]
unfortunately, the same error message as before. 

this is the build:

```
$ git clone https://github.com/Mastermindzh/tidal-hifi.git
Cloning into 'tidal-hifi'...
remote: Enumerating objects: 635, done.
remote: Counting objects: 100% (335/335), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 635 (delta 200), reused 256 (delta 151), pack-reused 300
Receiving objects: 100% (635/635), 2.99 MiB | 3.65 MiB/s, done.
Resolving deltas: 100% (360/360), done.
$
]$ cd tidal-hifi/
$ npm install

added 452 packages, and audited 453 packages in 30s

26 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
$
$ npm start

> tidal-hifi@2.8.0 start
> electron .

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by Mar0xy** [comment]
Could you try running it with flag --no-update-widevine-cdm

**Comment by daudo** [comment]
not sure where to add the parameter, tried this:

```
$ cd tidal-hifi
$ node_modules/electron/dist/electron  . --no-update-widevine-cdm
```

Unfortunately, this doesn't change anything, still the same error message.

But what I also tried now is starting it using another version of electron. I have version 15 and version 17 installed on my box:

```
$ cd tidal-hifi
$ electron17 .
```

```
$ cd tidal-hifi
$ electron15 .
```

And both of them successfully manage to start tidal. Can it be that the issue is related to the old electron 8.5.2 that tidal is shipped with? 

Looking at https://github.com/castlabs/electron-releases/ I see this message:

>     warning The v16 series of Electron for Content Security, labeled wvcus, moves to using the Component Updater Service to handle installation of the Widevine CDM, and has incompatible API updates compared to the previous wvvmp releases.
> 
>     See additional updates in the sections below, and please report any issues you find!
