### ISSUE TITLE
No playback at all

### ISSUE THREAD

**Issue by aalhitennf** [Mastermindzh/tidal-hifi#129]
I just updated from 2.8.0 to 2.8.1 and playback is broken after that. I get loading circle around play button and it never starts, sometimes "playback" starts and seek bar moves but nothing plays and time stays at 0:00, sometimes just nothing happens.  

I get sound from other apps so that is not problem. Started from terminal and theres no errors. Also tried logging out and in, still broken. Listen.tidal.com in browser plays songs without problems.  

e. I use tidal-hifi-bin from AUR.

**Comment by aalhitennf** [comment]
Reverted to tidal-hifi-appimage 2.7.1 and playback works normally.

**Comment by Mastermindzh** [comment]
@aalhitennf,

I seem to have the same issue, I only tested it directly from source before accepting a couple of prs and that (still) works.
It seems to be related to electron as all other code (for example, shortcuts) also doesn't work.

I'll have a look tomorrow, sorry for the inconvenience!

**Comment by aalhitennf** [comment]
Works again, thanks for fast fix!
