### ISSUE TITLE
Adding Gnome3 desktop icon?

### ISSUE THREAD

**Issue by haydenjames** [Mastermindzh/tidal-hifi#13]
I'm on vanilla Ubuntu 20.04 LTS. The app itself works great, no issues. How can I add a Tidal icon so that it's not using a generic grey gear?

Previously I used https://github.com/valknight/tidal-desktop which won't play much due to DRM error. However, the app did have an icon throughout gnome. 

thanks

**Comment by Mastermindzh** [comment]
I will have to look into this. 

Which version do you use? (e.g snap, aur, etc)
Which version of gnome (latest?)

**Comment by haydenjames** [comment]
I downloaded https://github.com/Mastermindzh/tidal-hifi/releases/download/1.0.1/tidal-hifi_1.0.1_amd64.deb 

then installed using apt install ./tidal-hifi_1.0.1_amd64.deb 

Default Ubuntu 20.04 LTS do with Gnome 3.36.2

Thanks again!

**Comment by Mastermindzh** [comment]
I'll have a look today. I'll let you know :)
Impressions so far:

- Love the wallpaper
- Install is kinda slow, is it always this slow? (I used around 20 cores and 40 or so gb of memory...)

**Comment by Mastermindzh** [comment]
Seems to be an issue with Gnome picking up the icons, might be to do with electron-builder.
I also tested it on KDE and XFCE, both worked.

When googling I found a lot of related issues, none of the solutions solved the problem though.

Gonna slap the help wanted label on it and see if someone with more experience with electron-builder and Gnome can fix it.

**Comment by haydenjames** [comment]
Install was fast for me. I have 8 cores with old i7, but the bottle neck is usually either network during additional downloads or writing to storage.  I have 2 NVMe drives in raid 0 in my laptop. So write speeds are pretty insane. 

Thanks for your efforts, this is far, far, better support response and action than any requests I made previously with Spotify. Happy to switch to Tidal, hopefully they make your work official.

**Comment by Mastermindzh** [comment]
Yeah, it was probably the network...
Meanwhile you can get the icon to work by changing the desktop file:

1. Open /usr/share/applications/tidal-hifi.desktop
2. Change the icon line to /usr/share/icons/0x0/apps/tidal-hifi.png
3. run `gtk-update-icon-cache`

The icons will update themselves :)

![image](https://user-images.githubusercontent.com/4190290/85231080-99167780-b3f4-11ea-9f11-c88063a241b3.png)


Now the 1 thing that is left is figuring out why in the world the icon isn't being picked up whilst it is in the 0x0 folder (or why it's even placed there... 0x0 shouldn't be a size)

**Comment by haydenjames** [comment]
Thanks. 

That didn't quite work for me. The icon is now blank, invisible or maybe it's 0.0px:
![Screenshot from 2020-06-22 18-45-41](https://user-images.githubusercontent.com/6467408/85342590-fecc3780-b4b8-11ea-8f70-28465051520e.png)

**Comment by Mastermindzh** [comment]
Did you run `gtk-update-icon-cache`?
I can look at it more lataer today, but your files look good to me.

I didn't have the dock though, I looked for tidal-hifi in the launcher.

You can always resize it to 512x512 with something like imagemagick:

`convert /usr/share/icons/0x0/apps/tidal-hifi.png -resize 512x512 /usr/share/icons/512x512/apps/tidal-hifi.png`

Then update your desktop file to reflect the new path.

What kinda dock is that? Is that the "Dash to dock" thing from years ago :P?

**Comment by haydenjames** [comment]
Its Ubuntu Dock. which is based on dash to dock.  Made a few dconf edits.

It's blank in app list also. Yes tried gtk-update-icon-cache.

thanks

**Comment by dspacejs** [comment]
@Mastermindzh There's no `/usr/share/icons/0x0` folder for me. I installed it via the .deb file on Ubuntu 20.04 LTS

Where can I find the icon?

**Comment by Mastermindzh** [comment]
@dspacejs I would have to check by installing a .deb version myself.
Meanwhile, you can get the icon from the tar.gz release: https://github.com/Mastermindzh/tidal-hifi/releases/download/1.0.1/tidal-hifi-1.0.1.tar.gz

**Comment by Mastermindzh** [comment]
Fixed in [v1.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/1.1.0).
Please open a new issue if an issue arrives.

**Comment by dspacejs** [comment]
@Mastermindzh how do I update this app when installing via source? Thanks

**Comment by Mastermindzh** [comment]
Kinda depends on how you installed it.

- Did you generate a build and install that? -> do it again and install the new one, your OS will be smart enough to replace the old one :+1: 
- Did you just build the source and copy the dist somewhere? -> overwrite the copy with the new dist.

If you provide some extra info I might be able to help a bit better, sorry.

**Comment by yashank09** [comment]
Hi @Mastermindzh ! Such a delight to see Tidal run(look) almost native on Linux, so thank you for that. 
I'm having the same icon issue in release 1.2.0 also, running PopOS with the same 'dash-to-dock' extension. The icon folder does not exist either. I tried every other package I could, but only tar.gz has an icon however I am unable to extract it and use it with my .deb installation. 
Since tar.gz seems to be working fine, could you please tell me how I could install using tar but still get a desktop icon since I believe we have to launch tar apps from the terminal everytime?

**Comment by Mastermindzh** [comment]
Hey @yashank09,

I'll have to look more into getting those darn icons to work then...
I have no idea why it doesn't work at this point as I'm doing exactly what electron-builder asks. (it creates the packages).

Installing the tar is difficult, you would have to basically do all steps yourself. e.g:

- copy icons to the correct directory
- copy licenses to the right directories
- copy the app to the right directories

Do you have any idea what icon dash-to-dock actually tries to load? That would be the first step to find out what I have to do.

**Comment by cwells** [comment]
On Fedora 32 (installed app via rpm), icon is located at `/usr/share/icons/hicolor/0x0/apps/tidal-hifi.png`.

**Comment by Mastermindzh** [comment]
@cwells does it work there? Because that is the path it's located at for me as well.

**Comment by cwells** [comment]
@Mastermindzh I had to edit `/usr/share/applications/tidal-hifi.desktop` as mentioned earlier, but using the path above rather than the suggested path, and then it works.

**Comment by Mastermindzh** [comment]
The icon is not in that location for the arch install, unfortunately. 
I really have to look into what electron-builder does with the darn icon... not clear to me anyway.

Thanks for the extra info, glad the workaround worked with a few tweaks.

**Comment by Mastermindzh** [comment]
Should be fixed in [2.2.2](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.2.1).
I changed the desktop file to the path specified above and fixed the arch install in another git repo.

Use your preferred update path and enjoy!

**Comment by dspacejs** [comment]
How did you get the `tidal-hifi` executable? I'm reinstalling the app and forgot how I did this @Mastermindzh 

I have the repo cloned in `/opt/tidal-hifi`, and I also have the `.desktop` file set up. But I'm missing this executable at `/opt/tidal-hifi/tidal-hifi`.

**Comment by Mastermindzh** [comment]
It is placed there by an installer. (e.g snap, deb, aur)
If you want to install from source you'd do it like this:

```sh
npm install
npm run build # you can use whatever build script you want, you're gonna use the unpacked version anyway.
mv dist/linux-unpacked/ /opt/tidal-hifi
chmod +x /opt/tidal-hifi/tidal-hifi
```

You can also download the zip file with the linux-unpacked version from [the releases](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.2.1).
That way you won't even have to build it 😄 

This, however, is quite a bit of work. By default on the release page (linked above) there are quite a few package formats published, you can usually install those in your system (we got deb, rpm, snap, etc)
