### ISSUE TITLE
Update to Electron 9+

### ISSUE THREAD

**Issue by Mastermindzh** [Mastermindzh/tidal-hifi#130]
Issues arrive when we build the app with electron-builder and Electron 9+.

Issue #129, is the first issue but from that I got the following:

- Audio doesn't reliably play (it does ... sometimes... but restarting the app over and over breaks it eventually)
- Hotkeys don't work anymore either
- The API doesn't seem to start
- If you open the settings window you can't close it

The weird thing is that when we use electron in dev mode, all the stuff works.
I will have to debug it later, but 2.8.2 fixes the issue by reverting to electron 8.5.2

@Mar0xy , I reverted the electron version because of this. I will look into updating it again later.

**Comment by Mar0xy** [comment]
Yea that is very odd it would be nice to only be able to build linux-unpacked version so that testing built versions would be faster.

**Comment by Mastermindzh** [comment]
I can add that in for you, no biggie.

**Comment by Mastermindzh** [comment]
`npm run build-unpacked` will now build just the unpacked.
Note that I tested `npm run build-arch` and installed it with `pacman -U` to test the 4 missing features described above.


PS: just waiting for artifacts to upload so I can hit release...

**Comment by Mar0xy** [comment]
I just went and used devtools on tidal-hifi-bin and saw these two errors in the main window 
![image](https://user-images.githubusercontent.com/8841466/164561255-a48a0795-0efe-4947-b53b-eb45cf96cddc.png)

**Comment by Mar0xy** [comment]
and the reason settings can't close is cause it thinks hide isn't defined 
![image](https://user-images.githubusercontent.com/8841466/164561495-6fda791f-3cb7-4184-ae3d-1963754fa24d.png)

**Comment by Mastermindzh** [comment]
I was thinking that between version 8 and... whatever (16) some API's might have changed.
If it runs into a snag anywhere in the preload then all the other code simply won't execute.

I don't have time (tonight, I should already be in bed) to dive any deeper than my hunch unfortunately.
I will dive into it tomorrow. Let's keep in touch so that we don't duplicate each others effort 😄

**Comment by Mar0xy** [comment]
Just looked at all changes from 8 to 16:
app.allowRendererProcessReuse was removed
the remote module was replace by [@electron/remote](https://github.com/electron/remote) which explains all the issues

**Comment by Mastermindzh** [comment]
Do you not need sleep!?

I will check the code and the remaining issues from the PR tonight.
Let's make this thing happen!

PS: did you try 16 as well? Or did the switch from uwvvp to the new thing break tidal?

**Comment by Mar0xy** [comment]
I explained more in the PR about what didn't function anymore like window.(function) being borked due to security increases and me having to replace those with counterparts for settings.

also yes the switch from wvvmp to wvcus does indeed break tidal.

**Comment by Mastermindzh** [comment]
Fixed by: https://github.com/Mastermindzh/tidal-hifi/pull/134
