### ISSUE TITLE
slow animations

### ISSUE THREAD

**Issue by licentiapoetica** [Mastermindzh/tidal-hifi#132]
I get rather poor performance with this software when it comes to animations, feels a bit slow compared to chromium or qutebrowser, any idea if this is some setting I can tweak to make it work better, like enabling hardware acceleration or something like this?

**Comment by licentiapoetica** [comment]
Here is a little video showing what exactly I mean and experience while using this nice software
feels a bit like there is a bottleneck holding it down

https://user-images.githubusercontent.com/51519051/164775425-eada48fb-3365-45aa-922d-29281c57c0b3.mp4

**Comment by Mar0xy** [comment]
This shouldn't be the case considering Hardware Acceleration is on by default.

**Comment by Mar0xy** [comment]
https://user-images.githubusercontent.com/8841466/164777283-aca1779f-b80b-4622-be51-409be673ee5b.mp4

**Comment by licentiapoetica** [comment]
yeah its a bit strange, I tried with the git version and running it myself via npm and the appimage, it's for me consistent with both, I have little experience when it comes to debugging this, if you maybe know something I could try let me know, would like to get the best performance possible out of this :)

**Comment by Mar0xy** [comment]
Well, there is a limit in this case all you can do is really nothing at all as this could be related with anything on your system considering it's already hardware accelerated which is the max you can do on electron to boost performance.

**Comment by licentiapoetica** [comment]
mh :/ that sucks

**Comment by Mar0xy** [comment]
You could try running this PR to see if a newer electron version fixes the lag: https://github.com/Mastermindzh/tidal-hifi/pull/131

**Comment by licentiapoetica** [comment]
> You could try running this PR to see if a newer electron version fixes the slowdown of animations: #131

Will try now!

**Comment by licentiapoetica** [comment]
It actually fixed the slow animations but I encountered a new problem, a problem that makes tidal completely unusable for me, no song will play anymore

**Comment by Mar0xy** [comment]
that happens when you run it directly without building try running
`npm run build` and then cancelling it when it finished linux-unpacked and starts building snap and etc

**Comment by licentiapoetica** [comment]
```
[nx@uca tidal-hifi]$ npm run build

> tidal-hifi@2.8.2 build
> electron-builder --publish=never -c ./build/electron-builder.yml

Error: Cannot find module 'fs/promises'
Require stack:
- /home/nx/git/tidal-hifi/node_modules/builder-util/out/fs.js
- /home/nx/git/tidal-hifi/node_modules/builder-util/out/util.js
- /home/nx/git/tidal-hifi/node_modules/electron-builder/out/cli/cli.js
- /home/nx/git/tidal-hifi/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nx/git/tidal-hifi/node_modules/builder-util/src/fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nx/git/tidal-hifi/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code 1
npm ERR! path /home/nx/git/tidal-hifi
npm ERR! command failed
npm ERR! command sh -c electron-builder --publish=never -c ./build/electron-builder.yml

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nx/.npm/_logs/2022-04-22T19_23_50_845Z-debug.log
```
somethings not right

**Comment by Mar0xy** [comment]
what node version

**Comment by licentiapoetica** [comment]
v12.22.5

**Comment by Mar0xy** [comment]
yea you need node version 16 for electron 15

**Comment by Mar0xy** [comment]
I personally use 16.14.0

**Comment by licentiapoetica** [comment]
It's building :^) truly awesome, hifi plays now, thank you very very much for your time, the animations are beautiful and smooth now too <3 take my love

**Comment by licentiapoetica** [comment]
I found a very potent fix for the slow animation bug, when I launch tidal-hifi with the argument `--disable-gpu` it works perfectly just wanted to add this here if someone has the same problem

**Comment by Mastermindzh** [comment]
Thank you @licentiapoetica,

Do you happen to use a laptop with both intel + nvidia drivers?
I've had weird behavior using that combo before (though not on tidal-hifi)

**Comment by licentiapoetica** [comment]
> Thank you @licentiapoetica,
> 
> Do you happen to use a laptop with both intel + nvidia drivers? I've had weird behavior using that combo before (though not on tidal-hifi)

actually yes I do! And sadly the fix is not permament it seems like, it worked like 5 minutes and then suddenly stopped working

**Comment by licentiapoetica** [comment]
```
           `.:/ossyyyysso/:.               nx@uca 
        .:oyyyyyyyyyyyyyyyyyyo:`           ------ 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 21.10 x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: Nitro AN515-55 V2.03 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 5.13.0-40-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 1 day, 20 hours, 26 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 3037 (dpkg), 19 (flatpak), 9 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: bash 5.1.8 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 1920x1080 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.22.5 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Icons: [Plasma], breeze-dark [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Terminal: konsole 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     CPU: Intel i5-10300H (8) @ 4.500GHz 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      GPU: NVIDIA GeForce RTX 3050 Mobile 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       GPU: Intel CometLake-H GT2 [UHD Graphics] 
      -oyyyyyyydMMyyyyyyysosyyyyo-         Memory: 2848MiB / 7780MiB 
        ./oyyyyyyyyyyyyyyyyyyo/.
           `.:/oosyyyysso/:.`                                      
                                                                   

```
I enabled nvidia as my primary gpu in the nvidia-settings

**Comment by licentiapoetica** [comment]
I tinkered a bit and modified Line 85 in main.js to be `mainWindow.loadURL('chrome://gpu/');` this is what I get, how does it look for you?

![image](https://user-images.githubusercontent.com/51519051/164980396-8b9a46b9-0a8a-46ea-bb43-8b0f39268618.png)

Full report here
https://p.sicp.me/pUDa8

**Comment by licentiapoetica** [comment]
apparently this is doing the trick in my case `app.commandLine.appendSwitch('enable-gpu-rasterization')` hopefully it works for a long time!

**Comment by licentiapoetica** [comment]
Before `enable-gpu-rasterization`

https://user-images.githubusercontent.com/51519051/164981932-f963983f-111b-47e1-aab8-11d661087d79.mp4

After `enable-gpu-rasterization`

https://user-images.githubusercontent.com/51519051/164981954-554d567e-636e-42a4-bef1-fffc4d8d061a.mp4

**Comment by licentiapoetica** [comment]
I am now back at home where I was able to test tidal-hifi with my desktop pc

```
                   -`                    nx@tyrus 
                  .o+`                   -------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MS-7C91 2.0 
               `+oooooo:                 Kernel: 5.17.5-zen1-1-zen 
               -+oooooo+:                Uptime: 43 mins 
             `/:-:++oooo+:               Packages: 1766 (pacman), 5 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 1920x1080, 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.24.5 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: Breeze-Dunkel [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack 10 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
 `++:.                           `-/+/   Memory: 4125MiB / 32022MiB 
 .`                                 `/   

```

and I noticed slower animations on my system aswell without `--enable-gpu-rasterization` so at this point I believe gpu-rasterization is definetly needed in this application to perform as intended on most systems, since it's an optional argument I post this just here as a follow up necro bump.

Please take a look at the comparison video from my desktop pc aswell to see the difference it makes without and with it enabled, imo HUGE difference

https://user-images.githubusercontent.com/51519051/166884645-cfeb34aa-738c-4d1d-a441-fdcbf23fcc6f.mp4

It would be interesting to see how the app performs for others with and without it enabled and maybe some special setups without a dedicated gpu and how it performs with and without it, just to make sure.

**Comment by Mastermindzh** [comment]
I recently got a new work laptop with integrated graphics so I can test it for you if you want.

I am going to add a "advanced settings" section to the settings menu with a few of the ... advanced settings and I will include this flag there as well.

I will test what enabling rasterization does on a few platforms (amd integrated, intel integrated, nvidia and amd dedicated) and if it works everywhere with a default install (I'll probably take ubuntu or something...) I am not against enabling it by default.

**Comment by licentiapoetica** [comment]
> 

Very cool, I will also test on some devices I have here, a old Thinkpad T420 and a old Nvidia laptop

**Comment by licentiapoetica** [comment]
On my thinkpad T420 it's also obviously needed to add the gpu rasterization argument

```nx@Otterpad:~$ neofetch
            .-/+oossssoo+/-.               nx@Otterpad 
        `:+ssssssssssssssssss+:`           ----------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 4236Q23 ThinkPad T420 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-100-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 7 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2167 (dpkg), 17 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: sh 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1366x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-2450M (4) @ 3.100GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel 2nd Generation Core Processo 
      -+sssssssssssssssssyyyssss+-         Memory: 1751MiB / 3813MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
```

Also comparison video aswell!

At this point I have no doubt anymore

https://user-images.githubusercontent.com/51519051/166904448-9ec29a73-5ad9-4933-a657-bc3237d8ff3d.mp4

**Comment by Mar0xy** [comment]
Still very bizarre considering my arch pc with a nvidia gpu doesn't have this issue.
I could try it out on a laptop from 2010 with gentoo installed which has an radeon hd gpu and core2 duo cpu

**Comment by licentiapoetica** [comment]
please do I will try today with a old laptop with nvidia gpu too to see if this is a intel/amd thing

**Comment by Mastermindzh** [comment]
My results (I'll implement fixes later):

- Ryzen system with nvidia gpu -> lag without param
- Intel system with nvidia gpu -> **no** lag without param
- Ryzen with AMD GPU -> **no lag** without param
- Intel with AMD GPU -> lag without param
- Intel integrated graphics -> lag without param
- amd integrated graphics -> lag without param
- vm with nvidia card -> lag without param

As of right now I don't see any negatives to enabling the flag by default and offering users a way to opt out (settings can be adjusted even if tidal doesn't happen to start).

I'll add the new settings screen tonight and include this option.
Thank you both for the extensive testing work 😄

**Comment by Mar0xy** [comment]
"Ryzen system with nvidia gpu -> lag without param" would be interesting to know what the specs are as my arch system with a Ryzen 5 1600 and a Nvidia GTX 1060 3GB doesn't lag

**Comment by Mastermindzh** [comment]
@Mar0xy, Ryzen 7 3700x and nvidia gtx 970.

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/167262678-870b34a9-fb89-44d3-be98-882c87ac5253.png)

Settings screen done, also migrated a setting to the new flags area.

Will commit now and the builds will start rolling, hang on!

**Comment by Mastermindzh** [comment]
Version [3.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/3.1.0) has been released and it includes the rasterization setting enabled by default.

Thanks and enjoy!
