### ISSUE TITLE
Double mpris

### ISSUE THREAD

**Issue by Mastermindzh** [Mastermindzh/tidal-hifi#133]
Sorry to revive a closed issue - I had the same problem, running gnome 42 on arch linux. I was able to fix this by adding 

`app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling');`

to `main.js` and re-packaging. It prevents chrome from creating its own default MPRIS instance in addition to the custom one.

_Originally posted by @fatalhare in https://github.com/Mastermindzh/tidal-hifi/issues/100#issuecomment-1107435699_

**Comment by fatalhare** [comment]
New setting works great, thank you!
