### ISSUE TITLE
Question: Add auto update via Electron Builder?

### ISSUE THREAD

**Issue by KorbsStudio** [Mastermindzh/tidal-hifi#135]
While exploring the source code, I noticed there is no way to easily update the app in case you create a new release.

This can be easily implemented with [Electron Builder](https://www.electron.build/auto-update).
Can be setup with either GitHub Releases or using a custom update server(VPS or whatever).

My questions is: **Will you implement auto-update?**

**Comment by Mar0xy** [comment]
This is a tough question considering we already offer flatpak, aur and pacstall(debian/ubuntu) so this would only really be useful for people using snap (why would you use snap), the Mac release and bsd

**Comment by Mastermindzh** [comment]
Agreed, not really worth the effort for just the AppImage i.m.o.
I'll keep it open, if it gets a lot of votes I can spend the time on it but ... meh.

If you want to take a crack at it the github release strategy would be what I would go with for this project.

**Comment by KorbsStudio** [comment]
I just remembered that only certain formats are supported for auto update on Electron Builder, so on second thought it's not worth it since I'm on Linux and all.
I don't use AppImage that often, mainly RPM and Flatpak.
