### ISSUE TITLE
Unable to access developer tools

### ISSUE THREAD

**Issue by licentiapoetica** [Mastermindzh/tidal-hifi#136]
I am running latest git and I am unable to open developer tools via ctrl+shift+i or f12, I even checked the main.js which says devtools true

**Comment by Mar0xy** [comment]
You can access devtools through chromium aswell by putting `--remote-debugging-port 8315 --host-rules MAP * 127.0.0.1` into the start command though note that running it straight via npm start will most likely always result in audio not working as it needs to be built to work but you can use the same approach on builds

**Comment by licentiapoetica** [comment]
I have chromium installed on my machine but the devtools don't show up, I guess the normal behaviour should be that the devtools just open when the shortcut is pressed right?

**Comment by Mar0xy** [comment]
That has never worked for me so I always end up doing `--remote-debugging-port 8315 --host-rules MAP * 127.0.0.1 ` and then opening chromium and pasting the ip:port it gives me in the terminal to access devtools

**Comment by licentiapoetica** [comment]
sadly it doesn't work for me, in chrome it can't be accessed that way

**Comment by Mar0xy** [comment]
what do you paste in considering this is all you need
![image](https://user-images.githubusercontent.com/8841466/164973677-005ff7ab-a06d-43ce-a6ae-7149fd9a1b5a.png)

**Comment by licentiapoetica** [comment]
oh I think I understood it wrong then, it works now using the compiled binary and calling this, thanks again!
