### ISSUE TITLE
tidal:// protocol

### ISSUE THREAD

**Issue by licentiapoetica** [Mastermindzh/tidal-hifi#138]
Is it possible to add protocol support to tidal-hifi?

Like when a friend sends you a tidal.com song link, you click play on tidal and it opens in the app instead of in-browser.

`Prevented navigation to “tidal://mix/002a5c0eaac56c7223da4320e9310f” due to an unknown protocol.` 

This is what firefox reported in the console when I tried to open a playlist

**Comment by Mastermindzh** [comment]
It should be possible 😄 

Do you have more share links like that? (Or a way to find them)
Seems to be playlist/song/artists specific.

**Comment by Mar0xy** [comment]
Pretty sure it follows the same principle as the links to listen.tidal.com or tidal.com do so `tidal.com/browse/track/177534759` would result in `tidal://track/177534759` or `listen.tidal.com/playlist/41e20e82-ec05-4539-92f4-8988cb352850` would result in `tidal://playlist/41e20e82-ec05-4539-92f4-8988cb352850`

**Comment by Mastermindzh** [comment]
Thanks, I'll see what I can do this weekend 😄

**Comment by Mastermindzh** [comment]
Version [4.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.1.0) was just released with a fix for this issue 😄
