### ISSUE TITLE
tidal-hifi-flags.conf

### ISSUE THREAD

**Issue by nekinie** [Mastermindzh/tidal-hifi#139]
I happily use this project (thank you) on sway (wayland) by executing the following command ```tidal-hifi -enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland```. Most electron based projects support a electron15-flags.conf or chrome-flags.conf file to configure these flags, it would make my ergonomics a little easier this project could follow the same convention.

**Comment by Mastermindzh** [comment]
Hey @nekinie,

I don't know how that works but I'll check it out this weekend 😄

**Comment by Mastermindzh** [comment]
@nekinie, Got any links for me? 

Can't seem to find too much 🤔.

**Comment by nekinie** [comment]
I did some research into how this is handled in the system electron and this is what I found:
```
#!/usr/bin/bash

set -euo pipefail

name=electron
flags_file="${XDG_CONFIG_HOME:-$HOME/.config}/${name}-flags.conf"

declare -a flags

if [[ -f "${flags_file}" ]]; then
    mapfile -t < "${flags_file}"
fi

for line in "${MAPFILE[@]}"; do
    if [[ ! "${line}" =~ ^[[:space:]]*#.* ]]; then
        flags+=("${line}")
    fi
done

exec /usr/lib/${name}/electron "$@" "${flags[@]}"
```

This looks to be packaging related rather than a code change, we can close this issue and I will reach out to the package maintainer. Sorry for the bother.

**Comment by Mar0xy** [comment]
I have decided to add it in later done the road but on another note I am surprised it even is working with wayland due to https://github.com/electron/electron/issues/32487

**Comment by Mastermindzh** [comment]
Oh I see, just a bash script to add flags from a config file then.

I'll keep this open and possibly add advanced flag handling inside tidal-hifi itself, might be useful regardless.

**Comment by Mar0xy** [comment]
> Oh I see, just a bash script to add flags from a config file then.
> 
> I'll keep this open and possibly add advanced flag handling inside tidal-hifi itself, might be useful regardless.

Yeah, afaik some electron apps actually add that into their app(Discord and a few others) instead of doing it through bash scripts.

**Comment by Mastermindzh** [comment]
Yeah, seems cleaner to do it in the app so I'll eventually just do that :)

**Comment by cold-nagai** [comment]
Any updates?

**Comment by Mastermindzh** [comment]
We've been adding flags straight into the application for now.
Do you need advanced flag handling or just a specific flag :) ?

**Comment by cold-nagai** [comment]
> We've been adding flags straight into the application for now. Do you need advanced flag handling or just a specific flag :) ?

I was hoping tidal-hifi would respect  ~/.config/electron-flags.conf or at least implement a workaround:

> I'll keep this open and possibly add advanced flag handling inside tidal-hifi itself, might be useful regardless.

For now i have to update tidal-hifi.desktop with proper flags via hook every time a new AUR update comes. Janky!

**Comment by jthvai** [comment]
I understand that tidal-hifi bundles its own version of electron, rather than using the system installed one, so it may not make sense to respect `~/.config/electron-flags.conf` since its internal electron version may not be the same as the system electron version.
