### ISSUE TITLE
White screen at startup

### ISSUE THREAD

**Issue by daggr8** [Mastermindzh/tidal-hifi#142]
Hi, 

I searched the issues and found a few that also had issues with white screen prior to login.
I have the issue as well. I'm on Kubuntu 22.04. Same issue with flatpak and snap. 

I tried installing it on a Ubuntu 22.04 VM and that seemed to work fine.

I would of course want it to work on my machine and I'd be happy to provide any logs or assistance to find the issue. 

Thanks!

**Comment by daggr8** [comment]
Solved!

For me, the issue was my VPN provider. I changed endpoint and now it works.

**Comment by E34rrsff** [comment]
I also have this issue, but I don't use a VPN or anything. Just installed from AUR.

**Comment by E34rrsff** [comment]
Now it seems to be fixed... not sure what the problem was, but I did run a system update. Not sure if that fixed it.

**Comment by daggr8** [comment]
When it didn't work for me. `listen.tidal.com` didn't respond to ping requests.

**Comment by Mastermindzh** [comment]
The white screen is usually an issue with listen.tidal.com loading 😄.
Unfortunately it is sometimes unresponsive when it thinks you're doing anything "fishy".
We've even had account bans (for 24h) for people that rotated their ips too quickly ....

Good to hear it was all resolved.
Enjoy the music my friends!
