### ISSUE TITLE
Add functionality to toggle window from tray by clicking app icon

### ISSUE THREAD

**Issue by lolrepeatlol** [Mastermindzh/tidal-hifi#143]
Tidal-Hifi has interesting tray functionality in that it works by disallowing you from opening the app twice. This means, to toggle the window back open, the only way you can do so is by clicking the tray icon and hitting Toggle Window.

This behavior is different from other apps, which just allow you to toggle the window back open by clicking the app in your launcher. Notable examples include Discord and 1Password.

Is there any chance the behavior of Tidal-Hifi could match how most apps work?

**Comment by Mastermindzh** [comment]
Sure. Regular gnome tray or some other tray I can use to test?

**Comment by Mastermindzh** [comment]
@lolrepeatlol,

Sorry. I forgot about this. I will try and hook it up next weekend!

**Comment by lolrepeatlol** [comment]
awesome!!! appreciate it :))

**Comment by Mastermindzh** [comment]
Hey,

I installed gnome-shell and noticed it didn't have a tray. I tried getting [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/) working but my shell (42.3.1)] wasn't compatible.


However, I also found out that the 'click' event is simply not working at all in Linux anyway (and that seems to be "by design" according to docs): https://github.com/electron/electron/issues/6773

So what I did, whilst fixing another issue, is to add a "toggle window" button to the tray icon menu (which has been fixed again).
This is in KDE... (also works in i3 and cinnamon) but I assume it works with whatever tray you are using:

![tidal-menu](https://user-images.githubusercontent.com/4190290/183294307-0df42483-0bea-4c03-902a-7e03fff240c7.png)

**Comment by lolrepeatlol** [comment]
> Hey,
> 
> I installed gnome-shell and noticed it didn't have a tray. I tried getting [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/) working but my shell (42.3.1)] wasn't compatible.
> 
> However, I also found out that the 'click' event is simply not working at all in Linux anyway (and that seems to be "by design" according to docs): [electron/electron#6773](https://github.com/electron/electron/issues/6773)
> 
> So what I did, whilst fixing another issue, is to add a "toggle window" button to the tray icon menu (which has been fixed again). This is in KDE... (also works in i3 and cinnamon) but I assume it works with whatever tray you are using:
> 
> ![tidal-menu](https://user-images.githubusercontent.com/4190290/183294307-0df42483-0bea-4c03-902a-7e03fff240c7.png)

hey!! thanks for the response. 

i do have the tray icon gnome extension but pretty much only for tidal right now. 

i do now realize that the click event doesn't really work, but other apps like 1password, element, and discord seem to work around it by simply making the current window reappear [when the app is called to open??](https://support.1password.com/keyboard-shortcuts/#wayland) not entirely sure. 

at the very least, i do know that 1password and discord are electron apps themselves. so is element, which is open source.

that's why i find the "toggle window" solution that currently exists somewhat clunky -- it doesn't match the behavior i perform for every other app on my system, making tidal-hifi the one app i have a tray icon extension for.

nonetheless i appreciate your response & time working on this :heart:

**Comment by Mastermindzh** [comment]
We can apply the same workaround 🤷🏻.
The app is already configured to only open 1 instance so I can simply check whether `--show` was passed as an args and if so toggle the window open (if it isn't already) and keep the "give focus"* logic that we currently have.

You're gonna have to wait till I have some time again, but it should work after that 😂 

* if you try to start tidal-hifi twice it will focus the old window.

PS: I appreciate your candor!

**Comment by lolrepeatlol** [comment]
no worries! and thank *you* so much for working on this! <3

**Comment by isle9** [comment]
Hello, any change you implement a feature to reopen the app when you relaunch it? Currently it also seems to do nothing while the single-instance setting is enabled.

**Comment by nobrayner** [comment]
> so I can simply check whether --show was passed as an args and if so toggle the window open
Is this still possible to be done? I had a quick (cursory) glance through the source, but I can't see where this would be done...

I have a key binding to launch tidal in my WM, but can only use the tray icon to toggle the window of the single instance. Ideally, I could use the same keybinding to launch Tidal if it isn't already running, and also to toggle the window if it is.
