### ISSUE TITLE
Will you consider working on gapless playback?

### ISSUE THREAD

**Issue by reyquito** [Mastermindzh/tidal-hifi#144]
I'm on Ubuntu, and gapless playback does not work on Tidal web player. Someone on Reddit suggested this app, which I tried and really liked, but it doesn't seem to support gapless playback. It would be great to have this feature! Thanks for all the hard work.

**Comment by Mar0xy** [comment]
This isn't possible due to the technical limitation of the web player that TIDAL uses if you want "gapless" (which TIDAL officially also says is unsupported) then the only way is to use a phone or switch back to windows for their windows client.

**Comment by Mastermindzh** [comment]
Agreed, since we don't control media playback it would be incredibly hard (and invasive).

Sorry!
