### ISSUE TITLE
failed to install widevine components

### ISSUE THREAD

**Issue by sioce** [Mastermindzh/tidal-hifi#145]
![Screenshot from 2022-06-10 23-12-55](https://user-images.githubusercontent.com/107278462/173143556-f18f964d-207d-42b0-8e9f-0557eeb84b15.png)

**Comment by Mastermindzh** [comment]
Sorry, wrong button.

What version are you using? Haven't seen this before.

**Comment by sioce** [comment]
> Sorry, wrong button.
> 
> What version are you using? Haven't seen this before.

Ubuntu 22.0
![Screenshot from 2022-06-16 10-52-10](https://user-images.githubusercontent.com/107278462/174022004-18fa6ccd-7805-480e-9a03-72219e36a833.png)
4

**Comment by Mastermindzh** [comment]
Does the same thing happen with the .deb package?

**Comment by alternateved** [comment]
I installed tidal-hifi for the first time (via flatpak) and have the same error. If you need any additional information, I would happily provide. I am using in on openSUSE. Partial output of command `flatpak list`:
```
tidal-hifi  com.mastermindzh.tidal-hifi  3.1.1 stable system
```

**Comment by Mastermindzh** [comment]
Might have been fixed with the following patch:

https://github.com/Mastermindzh/tidal-hifi/pull/152

Please update to 4.0.0 and let me know if the issue persist.
