### ISSUE TITLE
Critical playback error

### ISSUE THREAD

**Issue by mckrvss** [Mastermindzh/tidal-hifi#146]
Hi. There is a problem with songs playback. Everytime I'm trying to play some music (singles, albums, playlists etc.) it loads for 1-2 seconds and then notification pops up saying "Failed to connect to the server. Check internet connection". I cleared cache, changed internet provider and that error still occurs.

![2022-06-12_160941](https://user-images.githubusercontent.com/79174374/173237346-9f2229d1-a96a-4bb5-807a-ec00001957cf.png)

**Comment by naeq** [comment]
I have the same problem.

**Comment by Mar0xy** [comment]
This tends to happen when TIDAL is currently broken and is nothing related to this app.

**Comment by Mar0xy** [comment]
> there was that problem too. 

Funny considering I don't have the issue at all.

**Comment by mckrvss** [comment]
Maybe it's related to different OS. I try to use this app on latest build of Windows 10.

**Comment by mckrvss** [comment]
Thanks for checking it! My built is Windows 10 21H2, compilation `19044.1766`

**Comment by Mastermindzh** [comment]
Works fine for me on a fully updated Windows box.
Have you tried a complete reinstall (cleared configs etc?)

**Comment by mckrvss** [comment]
> I cleared cache, changed internet provider and that error still occurs.
> 
Yes, I tried that before. I guess is something wrong with my account then...

**Comment by Mar0xy** [comment]
Since both are Polish could it some how be related to country (it's only happening in Poland)

**Comment by mckrvss** [comment]
It makes sense. In Poland we don't have a free Tidal plan so I was using American-made account. Web player and modded Android apk works very well with it, but e.g. Android TV version was unable to play any songs (app from Google Play and also direct Chromecast streaming).

It could be reason of this problem, but i deciced to make this thread anyway because I was using tidal-hifi few months before and everything was just fine. I guess that Tidal made some changes and now it blocks some functions for free accounts outside the US.

Anyway, thank you guys for checking it!

**Comment by Mastermindzh** [comment]
Thanks for confirming it also happens with the official app(s) @mckrvss.
Sorry to hear you have this issue though!

No problems for checking it out! 

Good luck!
