### ISSUE TITLE
Tidal-Hifi no longer shows track information in notification controls

### ISSUE THREAD

**Issue by AlexKF98** [Mastermindzh/tidal-hifi#148]
Since the latest update of Tidal Web (June 13), Tidal-Hifi no longer displays artist name and title track on the GNOME notification media controls, which only shows "unknown title" and "unknown artist".

**Comment by lolrepeatlol** [comment]
To be specific, this happens with the MPRIS player enabled.

**Comment by Mar0xy** [comment]
This could be due to Tidal probably changing the element which was used to get the info for MPRIS and Discord RPC causing the id/name to also change with the web update breaking both.

**Comment by Mastermindzh** [comment]
I'm currently quite ill (after returning from holiday) so I don't have much time to devote.

Will have a look when I'm feeling better.

**Comment by drom98** [comment]
I've read that tidal rewrote the playback feature in the latest update.

**Comment by Mar0xy** [comment]
> This might be effecting Discord RPC too, my status doesn't show my current playing song. ![image](https://user-images.githubusercontent.com/36741900/173816738-b04b58dc-2c17-4632-8814-efcae206ae18.png)

oh yeah odd when I tried it it worked now it doesn't anymore.

**Comment by Mar0xy** [comment]
update on the situation with discord it seems like tidal changed the way current and duration is given the player currently tries to access current-time and duration-time but both don't exist anymore resulting in it breaking.

the new fields are called just duration and current and they no longer provide normal numbers they now go P(don't know what this is suppose to stand for)M(Minutes)1S(Seconds)3.867(followed by microseconds)

**Comment by Mastermindzh** [comment]
> I've read that tidal rewrote the playback feature in the latest update.

Let's hope that they fixed some useful stuff as well then.
The PR is merged, working on a release now :)

**Comment by Mastermindzh** [comment]
Released in [3.1.1](https://github.com/Mastermindzh/tidal-hifi/releases/tag/3.1.1)
