### ISSUE TITLE
TIDAL-Hifi 3.1.0 has "disable hardware media keys" not working

### ISSUE THREAD

**Issue by lolrepeatlol** [Mastermindzh/tidal-hifi#149]
When attempting to turn on "disable hardware media keys," the setting does not save on 3.1.0 but saves and works fine on 3.0.0. 

(Tested on both the Flatpak and RPM package)

**Comment by Mastermindzh** [comment]
The flag accidentally updates "gpuRasterization" support instead. I have just fixed it and it will be available soon in 3.1.1.


Do note that the flag has moved to a flags section (from the red arrow, which is still there for backwards compat, to the green one):

![image](https://user-images.githubusercontent.com/4190290/174429807-bfca5830-8a18-460b-9730-fbca2c087fb3.png)

**Comment by Mastermindzh** [comment]
Released in [3.1.1](https://github.com/Mastermindzh/tidal-hifi/releases/tag/3.1.1)
