### ISSUE TITLE
Discord RPC not updating if a song auto plays.

### ISSUE THREAD

**Issue by Spencer-0003** [Mastermindzh/tidal-hifi#151]
Discord RPC functions correctly if you manually choose a song but if another one starts playing after that song, the RPC stays at 0:00 and shows the old song.
![image](https://user-images.githubusercontent.com/36741900/174451520-8fc52c33-e282-4595-a825-a1905ed2fc7c.png)

**Comment by Mar0xy** [comment]
Just tried it and it works fine for me like I previously mentioned it could glitch out sometimes but most of the time it works fine.

**Comment by Sowd0404** [comment]
Can you document that being the case because I am quite literally able to repro this from the title

**Comment by Spencer-0003** [comment]
This is happening after every song (100% reproducible in my case) using `tidal-hifi-bin` and `tidal-hifi-git` from the AUR but works fine if I clone the repo and run the start script.

**Comment by Mar0xy** [comment]
https://user-images.githubusercontent.com/8841466/174524766-c9f1eb34-6eac-42a3-a2ac-ae411b56f7ac.mp4

You can see it glitch out once in this video and working for most after (the time being fucky is due to me skipping ahead to the end of the songs)

**Comment by brianmsm** [comment]
> This is happening after every song (100% reproducible in my case) using `tidal-hifi-bin` and `tidal-hifi-git` from the AUR but works fine if I clone the repo and run the start script.

I have tried repo cloning, but the problem persists. This is weird and reminds me of the problem sometimes with the next, pause and back buttons, where sometimes they just don't work.

In both cases, after restarting my computer, they now work without a problem. I'm not sure what could be causing it. Right now it works with the aur package `tidal-hifi-bin`.

**Comment by Mastermindzh** [comment]
That makes it even weirder 🤔 , that is the regular zipped version from the release page.
Well, if it works then that's great for you anyway 😄 !
