### ISSUE TITLE
MPRIS player sometimes does not update when changing track

### ISSUE THREAD

**Issue by AlexKF98** [Mastermindzh/tidal-hifi#154]
If I listen to some album, the title of a track sometime remains after it ends. The pause/play icon is also wrong at certain moments (showing play when the song is playing and pause when it is paused).

The MPRIS player only updates every 2 or 3 tracks, instead of always displaying the correct information about the current song.

![tidal](https://user-images.githubusercontent.com/12222211/178776103-bfba7eff-5844-4857-9d89-a2b9663e0ddf.png)
In this example, the notification controls still display the first track, "Needle in the Hay", when Tidal is actually playing "Clementine", the third song.

**Comment by arusahni** [comment]
I think I'm having a similar issue, but this is manifesting as the same song being scrobbled multiple times by `rescrobbled`.

**Comment by Mastermindzh** [comment]
I have been having similar issues on and off. I have been thinking of a fix but I don't have much time to get started with it.
Will try my best :)

**Comment by Mastermindzh** [comment]
Version [4.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.1.0) was just released with a fix for this issue 😄

**Comment by aalhitennf** [comment]
im still having this problem, using flatpak 

> tidal-hifi com.mastermindzh.tidal-hifi 4.1.0

**Comment by vincens2005** [comment]
I think it might have to do with background throttling, which holds back intervals for significant periods of time to save on resources, and therefore prevents the function to update the current song from being called. I'm going to make a PR soon, assuming my hypothesis is correct

**Comment by vincens2005** [comment]
Yeah it's hard to say for sure, but it probably is fixed by this.
