### ISSUE TITLE
Cannot read property of undefined (reading "isVisible")

### ISSUE THREAD

**Issue by RickStanley** [Mastermindzh/tidal-hifi#158]
1. Open Tidal Hi-FI;
2. click "Toggle window";
3. see error;

Preview:
![grafik](https://user-images.githubusercontent.com/23178554/184573665-cb50576a-9596-49b1-a50e-a20f890e2c0d.png)

System:
KDE Plasma 5.25.4 (Wayland)
Kernel 5.19
EndeavourOS
Package: tidal-hifi-bin 4.1.0-2

**Comment by Mastermindzh** [comment]
@RickStanley, thanks for the report. I'll probably have some time to fix it tonight.

PS: Nice theme!

@Mastermindzh, you forgot to pass through the `mainwindow` argument.

**Comment by Mastermindzh** [comment]
Fixed in 4.1.1 :)

Enjoy!
