### ISSUE TITLE
Cannot run from snap pkg

### ISSUE THREAD

**Issue by Jihadist** [Mastermindzh/tidal-hifi#16]
Hello, i couldnt start app from snap package
```
cmd_run.go:927: WARNING: cannot start document portal: Expected portal at "/run/user/1000/doc", got "/home/ubuntu/.cache/doc"
Client is not authorized to connect to Server
(tidal-hifi:1587): Gtk-WARNING **: cannot open display: :1.0
```
Ubuntu 18.04 xfce

**Comment by Mastermindzh** [comment]
What environment are you running?

- x?
- Wayland?

Did you configure snap so that it has permission to start GUI apps?
Does the .tar.gz version give you the same result?
