### ISSUE TITLE
DRM issue

### ISSUE THREAD

**Issue by thanasistrisp** [Mastermindzh/tidal-hifi#160]
I have signed up for a free account. In desktop official app it works perfectly but at your app version at windows 11 it throws this message after couple seconds of playing:
```
Your browser does not support DRM or you have disabled it. Please enable DRM to play music in your browser or download the desktop app to play there
```
Main browser: Brave with widevine enabled (it works perfectly in browser). I have not installed google chrome.

**Comment by Mastermindzh** [comment]
Hey @thanasistrisp,

Haven't heard this one yet.
I don't currently have a Windows 11 license so I'll have to look at how I can test this 😛.

**Comment by mas21** [comment]
I also have this problem on Windows 11 after the last update.
The app worked great before that.
Thought the cause was having Edge (chromium) removed.
Installed Edge didn't fix the problem.
This notification ensures that you cannot listen to music.
After 6 seconds, the song will stop playing.
The official Tidal app does not have this problem.

**Comment by naeq** [comment]
I have the same problem on Windows 10 from the beginning, although I use a modified version of windows called "ReviOS". Maybe that's where the problem is.

**Comment by mas21** [comment]
> Hey @thanasistrisp,
> 
> Haven't heard this one yet. I don't currently have a Windows 11 license so I'll have to look at how I can test this 😛.

Windows 11 Pro	VK7JG-NPHTM-C97JM-9MPGT-3V66T


Windows 11 Enterprise XGVPP-NMH47-7TTHJ-W3FW7-8HV2C

**Comment by kblovett** [comment]
This literally just started happening to me in the Linux app (installed via snap)

**Comment by MitchTurner** [comment]
Same issue. It's not unique to tidal-hifi, though. It's happening on browser (Firefox) too.

**Comment by hestonhoffman** [comment]
Looks like it's working again :man_shrugging:

**Comment by arynor96** [comment]
I do also have the same issue.

**Comment by Mastermindzh** [comment]
I have tested it on Windows 11 now and it seems to function without issues.
From what I gather in the rest of the thread it seems Tidal is (once again...) having some weird issues on their side.

We'll keep this open for a bit to see what happens I guess.
