### ISSUE TITLE
resources.tidal.com DNS requests

### ISSUE THREAD

**Issue by prinzhoefte** [Mastermindzh/tidal-hifi#163]
Since an update a few Weeks ago, the domain resources.tidal.com will do a DNS request almost once every half second.
I think this is some kind of bug. 

![b2bcfb24bdc054000680b2d25daf0650](https://user-images.githubusercontent.com/44341594/186545720-be9edaeb-4a2e-4eb7-b213-c69865d31e11.png)

**Comment by Mar0xy** [comment]
We have no control over how many requests are being sent as we just use tidal's web player I also checked it and the only times resources.tidal.com was called was when loading images.

**Comment by prinzhoefte** [comment]
Hm thats strange. But still thank you :)

**Comment by aalhitennf** [comment]
I noticed this same thing. If i open web player from official site in firefox, this spam doesn't happen. Then i open flatpak version and its spams 4 times a second to resources.tidal.com.
