### ISSUE TITLE
Wrong shortcut hint for settings

### ISSUE THREAD

**Issue by Dasdar990** [Mastermindzh/tidal-hifi#174]
The actual, working shortcut is "CTRL + =" as indicated in the project description

![Screenshot from 2022-10-07 16-57-45](https://user-images.githubusercontent.com/56268536/194585293-c910213e-abbf-4b4a-b37c-c7015fd74f1d.jpg)

**Comment by Mastermindzh** [comment]
Hey @Dasdar990,

We changed it somewhere along the road and forgot to update this bit!
Thanks for the mention!
