### ISSUE TITLE
Choose the disk/Directory to save downloads

### ISSUE THREAD

**Issue by albesco** [Mastermindzh/tidal-hifi#176]
Hi

I'm running tidal-hifi on a Linux Mint 20.3 laptop.
It has a USB external hard disk where it could save the music, but... in tidal-hifi there's no option to choose the "save directory".
Is it possible to add this functionality?
Thanks

Alberto

**Comment by Mar0xy** [comment]
TIDAL HiFi doesn't offer music downloading nor does TIDAL's web app only the official apps do(which this is not) so this wouldn't even be required.

**Comment by Mastermindzh** [comment]
Thanks for the answer @Mar0xy, spot on as always!

Sorry @albesco !
