### ISSUE TITLE
Enlarge the input buffer

### ISSUE THREAD

**Issue by albesco** [Mastermindzh/tidal-hifi#177]
Hi

In the town where I live we don't have a good internet connection, so Tidal music sometimes stops for a while.
Ils it possible to enlarge the input buffer, so there'll be a more stable and fluid listening?
Thanks a lot

Alberto

**Comment by Mar0xy** [comment]
This is something you would have to ask TIDAL themself under https://support.tidal.com/hc/en-us as this is not an app made by TIDAL nor can this app influence the way TIDAL's web app works

**Comment by Mastermindzh** [comment]
Thanks for the answer @Mar0xy, spot on as always!

Sorry @albesco !

**Comment by albesco** [comment]
Thank you anyway... You've made a great software!
