### ISSUE TITLE
Can't connect to Last.fm

### ISSUE THREAD

**Issue by sergiolen** [Mastermindzh/tidal-hifi#182]
I would like to connect my account to Last.fm but when I push the button it shows a blank window

![image](https://user-images.githubusercontent.com/44252880/198862935-4faec94f-402a-43e0-8a5b-edc97d2794cb.png)

**Comment by Mar0xy** [comment]
https://github.com/Mastermindzh/tidal-hifi#lastfm-doesnt-work-out-of-the-box-use-rescrobbler-as-a-workaround

**Comment by Mastermindzh** [comment]
I recently learned that you can also disable the sandbox temporarily whilst you login to last.fm.
To do so start tidal-hifi with the `no-sandbox` flag once and login, then restart without the flag.

`tidal-hifi --no-sandbox`

![image](https://user-images.githubusercontent.com/4190290/198905929-52eac562-f6a2-45a5-8d06-4b7b11f7b599.png)
