### ISSUE TITLE
Tidal-Hifi is not showing in Gnome's Notification Settings

### ISSUE THREAD

**Issue by peterge1998** [Mastermindzh/tidal-hifi#184]
Hi, this app is awesome!
I have one problem: I can't find it in Gnome's (on Fedora) Notification Settings. Other Flatpak Apps (Like Spotify) show up there.
I would like to disable notifications in general, and I can do that in this menu.
The app shows up in the app drawer and the installed section in software:
![image](https://user-images.githubusercontent.com/47355238/203146665-95b59f96-bb74-4307-90d5-578cb8ea0b53.png)

Or is this doable via the MPRIS Integration (which I have enabled)?
This is the menu where it does not show up:
![image](https://user-images.githubusercontent.com/47355238/203146153-d4a5c63d-7cbd-4579-a235-e8d3c3d8a46c.png)
![image](https://user-images.githubusercontent.com/47355238/203146133-12f19673-5c11-4bdc-ad1b-97cc940b90db.png)

**Comment by peterge1998** [comment]
![image](https://user-images.githubusercontent.com/47355238/203147175-98c18bec-20c1-4cac-afef-ac3200154964.png)
I cant read.

**Comment by Mastermindzh** [comment]
Thank you @peterge1998,

Enjoy the software!
