### ISSUE TITLE
Mouse back/forward navigation not working

### ISSUE THREAD

**Issue by altosys** [Mastermindzh/tidal-hifi#187]
Navigating back or forward using mouse buttons doesn't seem to work in the desktop application. \
Seems to work fine in a regular browser when testing.

Should be easy to replicate by just opening the app and clicking some links to browse into albums/artists or whatever and then pressing `back` on the mouse and see that nothing happens.

Running this from AUR on Arch when experiencing the issue.

**Comment by Mar0xy** [comment]
Works fine for me on OpenSUSE.

**Comment by Mastermindzh** [comment]
I too can successfully navigate with the forward/backward buttons on my mice.
