### ISSUE TITLE
can't unhide menu bar

### ISSUE THREAD

**Issue by bonds** [Mastermindzh/tidal-hifi#188]
I hid the menu bar using the builtin option, but now I need it back but I don't see a way to get it back. Feature request: add some UI for getting the menu bar back, maybe by holding down the alt key like Firefox does.

**Comment by 1nikolas** [comment]
had the same problem. Alt should make it visible again (temporary), as in all electron apps. That's what I was expecting by enabling this option but it did not work..

**Comment by Mastermindzh** [comment]
Hey,

I can look into adding "alt" support later this week (probably) but.. the "intended" way is through the settings that you can reach with `ctrl+=`.

You can also dig into the config file to fix it by setting the "menuBar" feature to true:

```
...
	"menuBar": true, 
...
```

**Comment by 1nikolas** [comment]
> I can look into adding "alt" support later this week (probably) but.. the "intended" way is through the settings that you can reach with `ctrl+=`.

I imagined there would be such shortcut but I didn't see it being mentioned anywhere
