### ISSUE TITLE
There was an unexpected error. Please contact support (S6007)

### ISSUE THREAD

**Issue by quuenton** [Mastermindzh/tidal-hifi#189]
This error appearing on 1-2 second of every track I am trying to listen, and in 20-22 there is no sound.
![image](https://user-images.githubusercontent.com/95988341/209997963-78bf01d5-15f8-44b3-aeea-d4cda9c90744.png)

OS: Windows 10 LTSC 21H2 (19044.2364)
Version: 4.3.1

**Comment by quuenton** [comment]
Tried:
Relog to account
Restart Tidal
Use a VPN

**Comment by acherifi** [comment]
Same error on my side. Ubuntu 22.04 with the app installed from package.

**Comment by Myned** [comment]
I was able to fix this error by reinstalling the app (in my case, through the AUR), though I cannot speak as to why this occurred in the first place.

**Comment by RobertGleaden** [comment]
Brand new user, Same issue 1-2 seconds and then the same error

**Comment by acherifi** [comment]
In my case it was fixed by rebooting the computer after a fresh install.

**Comment by Mastermindzh** [comment]
Hey all,

These things usually happen for Tidal when they do an update :/
The best thing to do is to restart the computer/software and if that doesn't help a reinstall might (it will clear some cached files).

A force reload can also do wonders (that clears the cache).

Unfortunately not something that can be solved by us.... it's a Tidal issue :/
