### ISSUE TITLE
Add download music feature with tidal-dl

### ISSUE THREAD

**Issue by dspacejs** [Mastermindzh/tidal-hifi#19]
Someone has made a nice package called [tidal-dl](https://github.com/yaronzz/Tidal-Media-Downloader). A version of it runs on the command line, meaning it could be interfaced with.

Perhaps this could be integrated into the app somehow to download music? I'm not sure how that'd work since the app is just the TIDAL web app embedded into Electron. Which means it might be difficult to alter the UI to add download functionality. But I do have an idea:

## Potential solution

Inject a download button into each playlist/your music library, like how the desktop app displays it (or something custom). You could read the DOM and just find the appropriate nodes, then inject it into there with custom HTML/CSS.

When the user turns the download on for something, it'll download it into a directory (like `~/Music/.tidal`). Only a single copy of each song will be kept, with a JSON file acting as a registry to say which song IDs have been downloaded (because if you download the same song in multiple places, you only want a single copy of it, I believe tidal-dl doesn't currently have this functionality).

To sync the music, just periodically call the API and compare the user's music with what has been downloaded. You could do it at startup, at an interval (say every 30 mins), plus it could be manually triggered in the settings. If a song is in the API response but not stored locally, it'll download it. And if it's local but not in the API response, it'll delete it.

As for how it will get the music from a given playlist/album/library, you could:

1. Scrape the DOM and get the song details (problem is you need to scroll through the entire thing to get all the info)
2. Based on the playlist/album/library's name or ID, you could make a call to the TIDAL API and get the info from it this way (this would be most reliable)

When the user plays a song, check to see if it's downloaded based on its id. If it is, override the media play controls on the app to play the local file (probably by adding an invisible layer on top of the buttons, which is hooked up to a custom event handler). If it's not downloaded, then use the web app's normal playback functionality.

As for the toggling the play/pause button when it's playing a local song. You can probably find the HTML node for play/pause, and replace it based on the play status. And for the volume, you could probably somehow hook up the app's system volume to sync with the downloaded song's playback volume.

Also in the settings, enable the user to specify which quality they want for downloads (tidal-dl supports up to hifi, which is good enough, IMO master quality is unnecessary and isn't really any different to hifi).

Obviously this is very hacky. But given the fact there's no official TIDAL app for Linux, this would at least provide us with an alternative. I doubt they're going to add an app, their support team is honestly pretty trash in my experience. Being able to download music is important, this would be a decent workaround.

**Comment by Mastermindzh** [comment]
I have no idea whether we would be allowed to do this. Would have to look into it.
Do the Windows/Mac apps let you download music? Is it encoded at all? (the way I see it: if the other apps allow it and you get a plain unencrypted .mp3/flac/whatever then it's all fair game...)

The overall concept isn't too complicated, the way tidal-hifi works at the moment is by scraping dom info for all it's functionality (including play/pause :wink: )


I was thinking of adding two things in the near future:

- Songwhip integration
- "bash/powershell" integration

The second one could be used to do this, albeit without the tracking of the songs.
The second one really would just call a script with the current song URL as the first param, allowing anyone to do anything with it.

I'll keep this open, see how much of an interest in it there is.

**Comment by dspacejs** [comment]
@Mastermindzh it depends on the user's country. If you look at the README of tidal-dl it says this:

> It may be illegal to use this in your country, so be informed.

Therefore I think this should be a toggleable feature, which the user can use at their own risk. Since this is open-source software, I think it's probably exempt from a lot of the laws a company would typically have to jump through. Because it's not exactly illegal, it's a gray area, and whether it's legal or not depends on which country it's used in. Otherwise tidal-dl wouldn't even be on GitHub, it'd have been taken down by now.

I think a lot of users would be willing to take this risk. Especially because if the company is going to be a pain and not even bother to support Linux users, they're not really giving them any other options besides a subpar UX that doesn't let you download songs.

> Do the Windows/Mac apps let you download music? 

Yep.

> Is it encoded at all?

Not sure. The files are probably stored with DRM.

**Comment by Mastermindzh** [comment]
I'll add it on the list. I'll solve the bug + integrations first and then I'll add this in various stages.

I just have to figure out why it can't build on Linux for now.. stupid 403...

**Comment by dspacejs** [comment]
I just realised another problem:

If the user doesn't have an internet connection, the TIDAL web app won't load at all. Which means they won't be able to use it as a media player for offline music. Therefore I'm not sure if this idea makes any sense besides providing a GUI for users to download their music (which they could they play with another media player if they don't have an internet connection).

And if that's the case, an additional solution would need to be provided for exporting playlists. So they can be imported into another media player. 

So I'm not sure if this is worth implementing, to be honest. Perhaps if we just get enough of us to hammer their support team with requests for a Linux app, they will listen to us and build it.

**Comment by Mastermindzh** [comment]
Mmm, yeah you are right about the app not loading at all.
I'll work on the Songwhip integration this weekend and that'll give a great basis for this extension as well. (at least the "simple" download)

List of priority atm:

- Songwhip start
- fix 403 (this will also give media API support ...)
- dl

**Comment by dspacejs** [comment]
@Mastermindzh woah, didn't even know Songwhip was a thing. I've been looking for an app like that for ages

**Comment by Mastermindzh** [comment]
Yep it's awesome! Most people don't use tidal so having a way to easily share my tidal stuff is a blessing.

Didn't have much time but I did figure out that actions are plain weird...

This one succeeded: https://github.com/Mastermindzh/tidal-hifi/actions/runs/250723377
This one failed: https://github.com/Mastermindzh/tidal-hifi/actions/runs/253383057

Exact same code...

But on master the code seems to build on Linux so I can debug the 403 properly next time :)

**Comment by B1tterSw33t** [comment]
@Mastermindzh instead of songwhip, you could try https://song.link which has an api for free, or you could email them and get a token to get faster responses.

**Comment by B1tterSw33t** [comment]
Where can I enable the songwhip integration??

**Comment by Mastermindzh** [comment]
@B1tterSw33t , It hasn't been integrated at all yet

**Comment by Mastermindzh** [comment]
Songwhip integration will be available in the next release :)
