### ISSUE TITLE
playback control from your app to android Tidal app

### ISSUE THREAD

**Issue by 9acca9** [Mastermindzh/tidal-hifi#190]
Hi. I need to control the play things (choose music, next song, etc....) from your app, but that the music sounds from the cellphone app. 
I mean, just use the interface of your app for control, but the play is made in the cellphone (android). Because i allways connect my cellphone to a big good speaker, and i want to control that from the notebook.
Thanks.

**Comment by acherifi** [comment]
This is issue cannot be adressed here. Remote control has not been implemented by Tidal themselves meaning that the feature does not exist at all. 
We have to push this on the Tidal side before third party apps can use it

**Comment by 9acca9** [comment]
oh, yep sorry, i found that after asking here.... incredible this dont exist in Tidal...
