### ISSUE TITLE
Not supported in this browser

### ISSUE THREAD

**Issue by gaarysn** [Mastermindzh/tidal-hifi#192]
Hi, I have an issue after install on ubuntu 22.04.1 lts.

![image](https://user-images.githubusercontent.com/11197895/211566723-c5ad1079-bacd-4366-9d8a-dc125805e9ae.png)

**Comment by Mastermindzh** [comment]
This happens from time to time (it's a Tidal thing) and a reload usually helps (sometimes you have to clear caches etc).
You can reinstall and it should go away, alternatively if you wait a few days or have a few restarts it usually sorts itself out as well.
