### ISSUE TITLE
Improvement: left-clicking the tray icon should display the main window

### ISSUE THREAD

**Issue by xileF1337** [Mastermindzh/tidal-hifi#193]
Hi, thanks for this cool app bringing Tidal to the desktop on Linux. I have a suggestion to improve the behavior of the app when using the tray icon in conjunction with the "Minimize on close" option. It is related to, but not identical to #143. 

Please make a left-click on the tray icon restore (and possibly raise) the application window if it is closed. This is what other applications/widgets usually do and is much quicker than having to right-click -> "Toggle Window" every time. Alternatively, a double-click could do this if you don't like a single left-click trigger the window (but why else would I click on the tray icon if not to restore the window?). 

Another idea to consider: when left-clicking the tray icon takes over the "toggle window" function, it would probably be sensible to  change the "Toggle window" context menu entry of the tray icon into a  "Quit" item? Currently, it is buried in the File sub-menu, but it is the only option to quit the application when using "Minimize on Close". Having it on the first level is also what I am used to from other applications.

I am using Tidal HiFi on KDE Neon 5.26 (KDE v5.26.5, Frameworks v5.102.0, Qt v5.15.8). 

Thank you so much for considering these suggestions!

**Comment by Mastermindzh** [comment]
Hey @xileF1337,

I personally don't like the single-click but I can see it's use so I'll make that an option in the settings.
Just have to see whether 1-click or 2-click is the default so I'll test some tray icons of other apps myself as well and draw a conclusion.

I should start working on Tidal-hifi again in the near future (I'm aiming for the weekend at latest) so I'll see what I can do.
Good enhancement!

**Comment by xileF1337** [comment]
Hey Rick, I just updated my Tidal-HiFi flatpak to 4.4.0 and, well, it works like charm! Thank you so much for your quick support!
