### ISSUE TITLE
[FR] tray icon hide if focused

### ISSUE THREAD

**Issue by farfromrefug** [Mastermindzh/tidal-hifi#196]
Would be awesome to be able to do that.
Also as there is a quit from right menu on tray icon. Maybe we could have an option to remove app from dock?

**Comment by Mastermindzh** [comment]
Whether applications are shown on docks is out of the control of the app itself.

Do you mean that the tray icon should disappear whenever the app is not minimized 🤔?
I've never seen an app behave quite like that tbh.

**Comment by farfromrefug** [comment]
@Mastermindzh no i mean if you click on the tray icon if the app is in focused, right now it does nothing. Would be nice for it to hide the app in that case
