### ISSUE TITLE
Ability to skip ads by going to the end of ad track

### ISSUE THREAD

**Issue by thanasistrisp** [Mastermindzh/tidal-hifi#197]
Maybe, there could be a way to simulate ad blocking in the app. Skipping of course does not work neither sliding to the end inside app, as it is not allowed in free plan. However, when an ad is playing, I could slide the progress bar to the end through the KDE plasma media center (in ad track, I could not go to the next track through KDE media center). So instead of waiting about 30 seconds of inactivity (by muting), a function could be implemented to go at the end of the track somehow, if it is possible to be implemented and be generalized for other desktop environments too.

**Comment by Mastermindzh** [comment]
There is no free tier in the Netherlands so I wouldn't be able to properly test this.
Besides that I have (still) not taken a stance on ad-blocking in this app tbh.

**Comment by Mastermindzh** [comment]
You would (most likely) need to use `mpris` as that is probably what KDE is getting its info from:

- https://wiki.archlinux.org/title/MPRIS
- https://www.npmjs.com/package/mpris-service

**Comment by thanasistrisp** [comment]
> You would (most likely) need to use `mpris` as that is probably what KDE is getting its info from:
> 
>     * https://wiki.archlinux.org/title/MPRIS
> 
>     * https://www.npmjs.com/package/mpris-service

the above works 
```
playerctl position [ad track duration -1] -->seconds or immediately 29 as I think it is stable
```
from terminal, but I don't know how to call it asynchronously from the app. This function `muteArtistIfFoundInMutedArtistsList` is getting called every time to update status. Neither seek command seems to work. Do you know how can I print log messages or even debug npm (I don't have experience to js)? As `console.log("String");` does not seem to work at least in the above function but it works in main e.g.
