### ISSUE TITLE
Disable Media Session API when MPRIS is enabled

### ISSUE THREAD

**Issue by 1nikolas** [Mastermindzh/tidal-hifi#198]
I don't know if this is even possible but it would be great if Media Session API gets disabled when MPRIS is enabled. On KDE it shows both. The problem with TIDAL's Media Session API is that it doesn't have a cover art (for some reason) that's why I have MPRIS.

Thanks

MPRIS:
![image](https://user-images.githubusercontent.com/30593419/215336666-10cc5916-5d99-4a10-ba3d-10a8ce785663.png)

Media Session API:
![image](https://user-images.githubusercontent.com/30593419/215336679-e14f1414-29f8-481b-8118-2077cecafd4c.png)

**Comment by Mastermindzh** [comment]
No idea whether I can disable it, I do see I can change the metadata (and probably the image): 

https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API


I'll have a look

**Comment by 1nikolas** [comment]
Is it supposed to show cover art on 5.1.0? Because it's not 😕

![image](https://user-images.githubusercontent.com/30593419/235327590-f2c199c8-82c8-48b9-99b0-e25bc83763ba.png)

Still only MPRIS has cover art

**Comment by Mastermindzh** [comment]
Hey,

Yeah probably. I updated the media API with the correct info manually so it should've displayed if that is really what KDE shows by default.

Do you have environment info? I could go and check it again :)

**Comment by 1nikolas** [comment]
> Do you have environment info?
What do you mean?

**Comment by Mastermindzh** [comment]
The distro you are on, the DE you are using (version of KDE) and where I can find that menu that you open up 😄

**Comment by 1nikolas** [comment]
Oh okay
![image](https://user-images.githubusercontent.com/30593419/235535681-115f5878-f507-40f3-9490-ccddee2913a4.png)

There is an icon on the right of the taskbar when you start playing any music. If you click it, it opens the menu

**Comment by Mastermindzh** [comment]
Will be fixed in 5.9.0 😄 

see: https://github.com/Mastermindzh/tidal-hifi/issues/338
