### ISSUE TITLE
connect to last.fm not loading the last.fm sign in page

### ISSUE THREAD

**Issue by kepek2222** [Mastermindzh/tidal-hifi#202]
gets stuck on a white screen
reloading doesnt do anything, same with force reloading
![image](https://user-images.githubusercontent.com/98672851/215812950-9a97d642-7633-490c-9a8d-f41f3844e0c9.png)
edit: forgot to mention, i use wayland

**Comment by Mar0xy** [comment]
to connect last.fm run the app with --no-sandbox as a flag once to connect after that you don't need to use that flag again

**Comment by Mastermindzh** [comment]
Thanks for answering @Mar0xy!

I've made a wiki page to link in the future: https://github.com/Mastermindzh/tidal-hifi/wiki/Known-issues---workarounds#1----white-lastfm-login-page

Closing now 😄
