### ISSUE TITLE
Deepin and Tidal - not working

### ISSUE THREAD

**Issue by ikey-ru** [Mastermindzh/tidal-hifi#205]
![Скриншот_20230203164007](https://user-images.githubusercontent.com/47115676/216617948-b7172373-3e35-48a9-8272-7a99436cb79a.png)
![Скриншот_20230203164121](https://user-images.githubusercontent.com/47115676/216617964-959ff7ce-ffbc-4f14-adad-847f1971b731.png)
I don't know which browser to install. Pressing the button does nothing.

**Comment by Mastermindzh** [comment]
Hey,

It's a known issue, nothing to do with the app, unfortunately... just Tidal being a bit of a twat 😄 
See: https://github.com/Mastermindzh/tidal-hifi/wiki/Known-issues---workarounds#2-tidal-hifi-cant-launch--browser-incompatible
