### ISSUE TITLE
Doesn't work without a notification manager

### ISSUE THREAD

**Issue by tylort69** [Mastermindzh/tidal-hifi#212]
my wm : https://aur.archlinux.org/packages/hyprland-nvidia-git
the app : https://aur.archlinux.org/packages/tidal-hifi-git
the issue : it launches but doesn't always load all gui elements and is non functioning at all (edit: it never works even when gui fully loads) (unresponsive to any user interaction). Using the wm shortcut to killactive does nothing and I need to send sigterm on multiple PIDs before it will close.

my env settings in hyprland.conf :  
```
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm #comment out for firefox to work
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
```
/etc/modprobe.d/nvidia.conf contains :
```
options nvidia NVreg_RegistryDwords="PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
```
system info :
```
OS: Arch Linux x86_64
Kernel: 6.2.8-arch1-1
Packages: 1465 (pacman)
Shell: bash 5.1.16
Resolution: 2560x1440
DE: Hyprland
Terminal: alacritty
CPU: Intel i9-9900K (16) @ 5.000GHz
GPU: Intel CoffeeLake-S GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce RTX 2070 SUPER
Memory: 5012MiB / 31940MiB
```
The package https://archlinux.org/packages/extra/x86_64/xorg-xwayland/ is installed

[SOLVED]
```sudo pacman -Syu dunst```
add the line `exec-once = dunst` to my `hyprland.conf`

it was crashing without a notification manager.

Notification manager should be listed as a dependency .

**Comment by Mastermindzh** [comment]
[5.0.0](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=tidal-hifi-git&id=2098f174e9ceddbb21e1f10669c5be744bb7383f) fixes this by adding libnotify as the standard library.
