### ISSUE TITLE
Seems to work but no sound (Ubuntu LTS 20.04 with Gnome 3)

### ISSUE THREAD

**Issue by Virtualtrax** [Mastermindzh/tidal-hifi#22]
If someone encounter this problem try to check Settings>Applications>tidal-hifi and verify if play and record sound is activated.

I don't know why but by default the app can have this permission disable just enable it and log out and it should work after.

You can close the issues I just made this in case someone encounter the same problem as I have.
Great work and thank you it work perfectly fine for me now!

**Comment by Mastermindzh** [comment]
Thanks! This should help some people!
