### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by felphhh** [Mastermindzh/tidal-hifi#220]
been listening for 6 hours and the memory usage just keep rising, song by song
![Screenshot_20230425_200518](https://user-images.githubusercontent.com/64710324/234433703-ed498f89-26c0-4f10-bdbe-41df0bcf7f9c.png)

**Comment by Mastermindzh** [comment]
Hey,

Could you verify whether it's the app or Tidal by running [listen.tidal.com](listen.tidal.com) in a browser and seeing what happens?
The last time we had one of these it turned out to be on Tidal's website rather than the app so best to rule that out straight away.

Would appreciate ❤️

**Comment by felphhh** [comment]
been playing music for 4 hours now via firefox, as the screenshot shows the memory usage is about 500mb, at the begining of the session it was near 900 megs but after an hour or so it went down to 500 and stayed that way, hope this helps! 
![Screenshot_20230427_222517](https://user-images.githubusercontent.com/64710324/235039552-69a066c7-64e7-4d29-b87b-17872514949e.png)

**Comment by Mastermindzh** [comment]
I tried it myself yesterday and wasn't able to reproduce it.
Will try again on Saturday or Sunday with the new 5.1.0 release and hope to see it reproduced

**Comment by felphhh** [comment]
Well, I'm using wayland and nvidia proprietary drivers.
If you can't recreate it that could be the issue  ☝️🤓

**Comment by Mastermindzh** [comment]
I'm currently using arc +xorg, but i can try Nvidia and Wayland later too.

**Comment by Mastermindzh** [comment]
I've run the newest (unpublished) version of tidal-hifi for days without exceeding 600MB in usage.
I'm confident the issue has been fixed in release 5.2 which will come out next week.

I will make a pre-release with a few files for you to test later.

**Comment by Mastermindzh** [comment]
I believe it to be fixed with release 5.2.0, if not please reopen :)
