### ISSUE TITLE
Flatpak isn't updated

### ISSUE THREAD

**Issue by MiMillieuh** [Mastermindzh/tidal-hifi#221]
Hello,

I've noticed that tidal-hifi-5.0.0 has been released since 4 days but it hasn’t been pushed to flathub repos...
Is it planned ?

Thanks for your hard work !

**Comment by Mastermindzh** [comment]
Hey @MiMillieuh,

@Mar0xy usually takes care of these so I've kinda been relying on her (sorry @Mar0xy!) 
I'll have a look at making the PR tomorrow.
Sorry for the delay 😢!

**Comment by MiMillieuh** [comment]
> Hey @MiMillieuh,
> 
> @Mar0xy usually takes care of these so I've kinda been relying on her (sorry @Mar0xy!) I'll have a look at making the PR tomorrow. Sorry for the delay cry!

That's fine :) thanks for the info I was just wondering :)

Thanks again for everything !

**Comment by Mar0xy** [comment]
I have had no internet the entire month at home as i need to make a new
contract which is taking a while

MiMillieuh ***@***.***> schrieb am Mi., 26. Apr. 2023, 17:01:

**Comment by Mastermindzh** [comment]
@Mar0xy,

Don't worry, I got it.

@MiMillieuh, PR for 5.1.0 (the latest, released just now) is running builds: https://github.com/flathub/com.mastermindzh.tidal-hifi/pull/3#issuecomment-1525762500

**Comment by Mastermindzh** [comment]
And merged!

Should be available soon @MiMillieuh.
Thanks for the wait!

**Comment by MiMillieuh** [comment]
> And merged!
> 
> Should be available soon @MiMillieuh.
> Thanks for the wait!

Great news !

Thanks again for everything !

**Comment by Mar0xy** [comment]
Just as an note I have internet again at home and updated the AUR package aswell as the RPM package on Open Build Service for OpenSuse

**Comment by Mastermindzh** [comment]
Great news @Mar0xy!
I'm working on some exciting things but after that, I'll be sure to write some release & contribution guidelines etc so we can smoothen this release track 😄 

Many thanks for your help again!
