### ISSUE TITLE
The tidal web player is not supported in this browser

### ISSUE THREAD

**Issue by voedev** [Mastermindzh/tidal-hifi#224]
I downloaded the linux-unpacked.zip for Fedora 37.

When I run the application, I get this message:

![screen](https://user-images.githubusercontent.com/42519520/235130982-0b0a0597-ffb5-4756-8e09-308baca79ea7.png)

Restarting my computer does not help. Can you please tell me how to fix this?

**Comment by Mar0xy** [comment]
Please check this comment https://github.com/Mastermindzh/tidal-hifi/issues/192#issuecomment-1396609365
