### ISSUE TITLE
Support for pulseaudio cork module

### ISSUE THREAD

**Issue by TomaszBelina** [Mastermindzh/tidal-hifi#23]
It is possible to automatically stop music playback when user starts the call on skype or teams or other applications like this. Technique is described here: http://www.webupd8.org/2013/06/how-to-automatically-mute-music-when.html. I've tested it with tidal and teams and it works. Here is a simple patch:
`diff --git a/build/linux/arch/tidal-hifi.desktop b/build/linux/arch/tidal-hifi.desktop`
`index 5bd5b81..f198d26 100644`
`--- a/build/linux/arch/tidal-hifi.desktop`
`+++ b/build/linux/arch/tidal-hifi.desktop`
`@@ -10,3 +10,4 @@ Terminal=false`
 `Type=Application`
 `Categories=Network;Application;Audio;Video`
 `StartupWMClass=tidal-hifi`
`+X-PulseAudio-Properties=media.role=music`

**Comment by Mastermindzh** [comment]
Hey @TomaszBelina , 

I have no problems including this, seems great! 
Do you want to make the pr yourself or want me to take the diff and make the changes?

**Comment by TomaszBelina** [comment]
I can do the PR - the change is in the branch ready to be pushed - I just need to get permissions to do it.

**Comment by Mastermindzh** [comment]
Did you make the PR on the AUR version? It is in sync with the files in this repo and will be updated on release ;)

**Comment by TomaszBelina** [comment]
I think I can't push anything into this repository. The change is only in my locally cloned git repository in branch created from master branch.

**Comment by Mastermindzh** [comment]
No worries friend, I've already made the changes and will release a new version shortly :)

**Comment by TomaszBelina** [comment]
Thanks. World is little better place now. 😃

**Comment by Mastermindzh** [comment]
Fixed in [v1.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/1.1.0).
Please open a new issue if an issue arrives.

PS: I also just pushed to the AUR. Enjoy!
