### ISSUE TITLE
Album artwork becomes green and distorted

### ISSUE THREAD

**Issue by bengiff** [Mastermindzh/tidal-hifi#231]
Hello,

Somewhat recently, various album artwork fails to load, distorts, and/or turns green after entering/exiting album pages or while searching. Any ideas as to what might cause this or what the fix might be?

Examples:
![Screenshot from 2023-05-24 13-59-13](https://github.com/Mastermindzh/tidal-hifi/assets/113922107/06ca3c99-5a7e-4274-8e75-d74faef19426)

![Screenshot from 2023-05-24 14-01-25](https://github.com/Mastermindzh/tidal-hifi/assets/113922107/ef9f4cd0-39c5-4f81-a802-001e10fe272b)

**Comment by Mastermindzh** [comment]
Hey @bengiff,

This looks a **lot** like a hardware acceleration issue that Chrome sometimes has issues with 😄.
In chrome, you can fix it with the flag "hardware acceleration", In Tidal-hifi we have something similar in the advanced settings:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/0bb4d234-c67c-413e-babd-ec39b30562e6)

Try flicking that (make sure to restart tidal-hifi fully and see if that makes a difference 😄

**Comment by Mastermindzh** [comment]
Nothing I can do I'm afraid. Haven't been able to reproduce.
I'll go ahead and close it. @madditt 's reply will help the others :)
