### ISSUE TITLE
White screen + CPU usage

### ISSUE THREAD

**Issue by flo333** [Mastermindzh/tidal-hifi#232]
Hi,

Not sure what happened since yesteday - opening up tidal-hifi only results in a white screen and constant 8% CPU usage. I'm running the `tidal-hifi-bin 5.1.0-1` package from the AUR. Same behavior with a fresh config folder in `~/.config`.

I don't think the console log is related:
```
enabling command line switch enable-gpu-rasterization with value undefined

(tidal-hifi:65349): Gtk-WARNING **: 15:14:04.621: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(tidal-hifi:65349): Gtk-WARNING **: 15:14:04.621: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
```

Anyone else having this issue?

**Comment by bengiff** [comment]
I'm getting the same issue. Tried uninstalling and reinstalling from a different source, and no luck.

`[2:0605/092207.222231:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed`

```
enabling command line switch enable-gpu-rasterization with value undefined
[8367:0605/092405.601367:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

**Comment by flo333** [comment]
Very interesting, it seems works fine again now. I didn't do anything, so...nevermind, I guess?

**Comment by flo333** [comment]
Tidal must've changed something on their side, I suppose. The normal web player at listen.tidal.com was working, I was using that in the meantime...very strange indeed. I'm closing this issue, sorry for ping.

**Comment by Mastermindzh** [comment]
I think we all had the same issue 😄...
My music stopped and has since resumed!
