### ISSUE TITLE
DRM Error on Windows 

### ISSUE THREAD

**Issue by Das-Kampfnudelholz** [Mastermindzh/tidal-hifi#238]
Im getting an DRM error (S6007) on Windows 10 

Have tried multiple ways of fixing it but wont allow me to playback my music 

[https://happy.signed.host/jWzqEvUAM8mlCntw1y.png](https://happy.signed.host/jWzqEvUAM8mlCntw1y.png)

**Comment by Mastermindzh** [comment]
DRM doesn't work under Windows, you should use the officially supported app for that instead 😄 .
Sorry!

**Comment by rexjohannes** [comment]
Why provide Windows releases then?

**Comment by Mastermindzh** [comment]
Hey @rexjohannes,

They used to work but the WideVine implementation (CastLabs) we use is currently not working on Windows in most countries.
Tidal is working on removing the custom DRM as well which would make this work again.

We will keep releasing Windows builds but I'll add some clarification on the release pages.
Sorry for the inconvenience.
