### ISSUE TITLE
[Bug] Hotkeys not working

### ISSUE THREAD

**Issue by Edu4rdSHL** [Mastermindzh/tidal-hifi#250]
I'm currently using Tidal HiFi 5.3.0 on ArchLinux and the hotkeys aren't working, I can't pause/reproduce, skip, etc., using the hotkeys.

The hotkeys works fine in other apps, it's just an issue on Tidal HiFi. I'm currently using XFCE, in case that does matter.

**Comment by Magsamm** [comment]
Same issues here. I also cannot enable gpu rasterization, or restart the app via settings menu.
on POP_OS! using the deb package.

**Comment by Mastermindzh** [comment]
Restarting the app hasn't worked for a good long while now.
I can look into the hotkey bug more this weekend. Do you have any specific info?

Hotkeys (custom ones) work fine for me once they are enabled.

**Comment by Edu4rdSHL** [comment]
Hey, @Mastermindzh, thanks for the prompt reply. I have already given you the more specific info (desktop environment, etc.), the hotkeys are just the default for me, like, enabling the switch and that's it.

Here's a screenshot of the setting that I have enabled:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/32582878/a1ba982d-3051-4c38-9bc6-e8ddf2dac68e)

**Comment by Mastermindzh** [comment]
Thank you. The screenshot rules out that the settings screen isn't loading the items from disk (none of the switches would be saved)

I'll have a look tomorrow. Let's hope I can find it :)

**Comment by Edu4rdSHL** [comment]
Thank you, I really didn't get the last part (about the settings load), I have already closed/opened the app many times and the switch’s state is loaded.

However, now that I remember, at some point when the app was updated they were not being saved, like, I enabled Hotkeys, et al., and they reverted to the previous state, but after I deleted my `$HOME/.config/tidal-hifi` folder it started working again.

**Comment by Mastermindzh** [comment]
@Edu4rdSHL,

Can you send me your config file?
I just ran the app and hotkeys seem to be working just fine for me 🤔.

Can you try `ctrl + =` or `ctrl + 0` to open the settings screen?

**Comment by Edu4rdSHL** [comment]
Hey, @Mastermindzh.

> Can you send me your config file?
```
❯ cat .config/tidal-hifi/config.json 
{
	"adBlock": false,
	"api": true,
	"apiSettings": {
		"port": 47836
	},
	"customCSS": [],
	"disableBackgroundThrottle": true,
	"disableHardwareMediaKeys": false,
	"enableCustomHotkeys": true,
	"enableDiscord": false,
	"flags": {
		"gpuRasterization": true,
		"disableHardwareMediaKeys": false
	},
	"menuBar": true,
	"minimizeOnClose": true,
	"mpris": false,
	"notifications": false,
	"playBackControl": true,
	"singleInstance": true,
	"skipArtists": false,
	"skippedArtists": [
		""
	],
	"theme": "none",
	"trayIcon": true,
	"updateFrequency": 500,
	"windowBounds": {
		"width": 1340,
		"height": 770
	},
	"__internal__": {
		"migrations": {
			"version": "5.3.0"
		}
	}
}
```

> Can you try `ctrl + =` or `ctrl + 0` to open the settings screen?

Yes, `ctrl + 0` open the settings.

**Comment by Mastermindzh** [comment]
Thanks for the config.
We now verified that:

1. Hotkeys can work (e.g ctrl +0)
2. Your config isn't messed up
3. Settings are applied

That left me with 2 options:

1. I don't know exactly what you're doing... so I might be testing wrong
2. Tidal messed up (e.g changed) something again

I explored option 2 and they seem to have changed a fair few css selectors:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/26ad651e-4365-4716-88f5-fc735bc2fe2e)

As you can see, I've figured out the new ones and updated the list, and then tested all keyboard shortcuts (and they all work, woohoo!)


Patch will be available in the next release. (along with Songwhip integration)

**Comment by Edu4rdSHL** [comment]
Sadly, I still have the same problem :(

**Comment by Magsamm** [comment]
Yeah i tried the new release and it has the same issues.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Edu4rdSHL** [comment]
As I said initially, there's not much I can share, I'm basically installing the app, login in, enabling hotkeys and that's it... there's nothing else, no weird setup, no weird anything... have you tried exactly on a XFCE setup?

**Comment by Mastermindzh** [comment]
Yes. I've tried it in xfce, it works there too.

Honestly, gou guys are not giving me anyyhing to go on. For all I know you're pressing hotkeys that do not exist, pressing them while in another application all together or something wild.
Why are you unable to share any additional info?

Just tell me what you do, which keys you press and what you expect to happen.
Clearly the settings hotkey is working, you've confirmed as much, so the others not working for you whilst they work for the other users would be very weird.

Or install simple-screen-recorder / peek along with screenkey to show me what you're doing.

Without a reproduction on my end there is nothing to be done.

**Comment by Magsamm** [comment]
Ok so. i think it works for me now. i cleared my tidal-hifi folder in .config, and enabled MPRIS in the integrations tab, and i can now skip song and pause normally. gpu rasterization is also enabled in now under advanced. just like for him i suppose. 

> Thank you, I really didn't get the last part (about the settings load), I have already closed/opened the app many times and the switch’s state is loaded.
> 
> However, now that I remember, at some point when the app was updated they were not being saved, like, I enabled Hotkeys, et al., and they reverted to the previous state, but after I deleted my `$HOME/.config/tidal-hifi` folder it started working again.

**Comment by Edu4rdSHL** [comment]
Thanks, @Magsamm, I confirm that enabling MPRIS makes it work again.

Maybe the reason it worked before was because it was enabled by default ¿?, anyway, thank you and @Mastermindzh!
