### ISSUE TITLE
Direct scrobbling implementation for ListenBrainz

### ISSUE THREAD

**Issue by Mar0xy** [Mastermindzh/tidal-hifi#253]
I have been thinking about this for a while now that implementing direct scrobbing for ListenBrainz instances would be a nice move so that you don't have to run stuff like rescrobbler seperately.

Instead you would provide a url to a ListenBrainz api(since you can run your own instances) or leave the url part empty for the default api and then the api key that is found in user settings which would allow it to post scrobbles to the api.

**Comment by Mastermindzh** [comment]
Not familiar with it, but sounds like a good idea 😄

**Comment by Mar0xy** [comment]
Some useful links:
https://listenbrainz.readthedocs.io/en/latest/users/api/core.html#post--1-submit-listens
https://listenbrainz.readthedocs.io/en/latest/users/json.html#submission-json

in the JSON submission examples there is `additional_info` as the name suggests it's just additional information and doesn't need to be provided

**Comment by Mastermindzh** [comment]
Fixed in 5.5.0
