### ISSUE TITLE
Playback cannot be resumed after network disconnect/reconnect

### ISSUE THREAD

**Issue by spikespaz** [Mastermindzh/tidal-hifi#256]
When my system (NixOS) is put to sleep, the network adapter is disabled and then re-enabled after waking. When this happens, or I manually disable the network adapter, Tidal loses network connectivity and displays error `S1002`.

After a network connection has been re-established, playback of the current track cannot be resumed.

The program must be restarted before I can resume playback, and it does not remember the last seek position of the current track (perhaps a separate issue).

**Comment by Mar0xy** [comment]
Keep in mind that this is just running the web version of tidal which means any issue related to playback errors are on Tidal's end and not the project's end

**Comment by spikespaz** [comment]
> playback errors are ... not [on] the project's end

Fair enough, but perhaps there is a workaround?
I notice that if I pause before I turn off the network adapter, and then resume it when reconnected, the playback will continue from the beginning of the track.

A workaround would be to use a combination of pausing on a DBus message (or something) when network connectivity drops, and restoring the seek position with a hack. Maybe even throw in one more thing: disable player controls when there is no network.

**Comment by Mastermindzh** [comment]
Hey,

This is indeed an upstream issue that also happens on the main clients.
We could find a hacky workaround to try and intervene but that is more work than it's worth (for me...) t.b.h.

Obviously, anyone is free to add it, but I probably won't work on it myself, sorry!

**Comment by spikespaz** [comment]
Understood, close the issue if you wish, or leave it open for others to reference (Tidal employees that happen to use Linux maybe?)

**Comment by Mastermindzh** [comment]
@spikespaz,

Let's go ahead and close it.
As for Tidal employees using Linux... I guess there might be some out there... would be interesting to hear from them on whether we can expect a Linux client now that they are slowly moving away from MQA to better compete with their competitors.

Cheers!
