### ISSUE TITLE
Inhibit system idle timeouts

### ISSUE THREAD

**Issue by spikespaz** [Mastermindzh/tidal-hifi#257]
While playing, the program should inhibit idle deamons.

On Xorg/X11, this can be accomplished with the DBus messages:
<https://www.freedesktop.org/wiki/Software/systemd/inhibit/>

On Wayland, this can be done by utilizing the `idle-inhibit-unstable-v1` protocol:
<https://wayland.app/protocols/idle-inhibit-unstable-v1>

If implementing support for Wayland protocols is too much effort, you could get away with using the freedesktop-compliant inhibit messages over DBus, because us Wayland users have a tool called [idlehack](https://github.com/loops/idlehack) to make the two inhibit protocols inter-compatible.

**Comment by Mastermindzh** [comment]
I'll have a look whether we can send a "sleep" inhibitor whilst music is playing 😄

**Comment by Mastermindzh** [comment]
Electron offers [PowerSaveBlocker](https://www.electronjs.org/docs/latest/api/power-save-blocker) for this. 

I will implement it for the next release.

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/f102ec37-628d-41ae-950e-3ad6da347dad)

**Comment by dinotheextinct** [comment]
This doesn't seem to work for me under wayland, when using swayidle and playing anything from tidal its not accepting the idle. I tried deactivated the MPRIS option, but I didn't change the behaviour.
