### ISSUE TITLE
Settings dont save

### ISSUE THREAD

**Issue by aalhitennf** [Mastermindzh/tidal-hifi#259]
I open settings by pressing alt -> settings -> do changes like enable discord rpc etc -> restart tidal-hidi -> go back to settings -> all changes made are reverted to defaults.

I have used tidal-hifi-bin 5.4.0 from AUR and flatpak version, same happens with both of them.

**Comment by aalhitennf** [comment]
I deleted `$HOME/.config/tidal-hifi`,  logged in again and it solved the problem :+1:

**Comment by aalhitennf** [comment]
Problem still occurs with flatpak version. All settings are set to false and changing them does nothing.

**Comment by aalhitennf** [comment]
And this can be fixed by removing `$HOME/.var/app/com.mastermindzh.tidal-hifi`  :grapes:

**Comment by Mar0xy** [comment]
This could have been linked with the fact that settings.json inside the .config/tidal-hifi was corrupted/one setting not following the expect format as I mentioned in this PR https://github.com/Mastermindzh/tidal-hifi/pull/258

@Mastermindzh I think there should really be a safeguard put in place to make sure that all the store settings are the valid type and if not they get corrected

**Comment by Mastermindzh** [comment]
I don't know whether the store offers any safeguards but yeah, these things started happening since we added some settings like custom css and artists.

Will check.
