### ISSUE TITLE
Rename Tidal Hifi to Tidal Max (or just Tidal)

### ISSUE THREAD

**Issue by Nyabinary** [Mastermindzh/tidal-hifi#261]
Tidal recently released a new update renaming the quality options and simplifying the quality options there—low, High, and Max. Tidal finally supports Linux fully as well since Masters are going away slowly.

**Comment by Mastermindzh** [comment]
Hey @Nyabinary,

Unfortunately, that is only half the truth that Tidal keeps pushing 😄.
Been watching this change closely and basically "Max" means "either FLAC or MQA, or the best we have available".

This article covers it nicely
https://www.digitaltrends.com/home-theater/tidal-hi-res-lossless-flac-max-annoying/

I will make the preparations to rename the app though!

**Comment by saku-bruh** [comment]
Opened the app a few hours ago but the Master and HiFi were still there. Opened it now and we just got Max and High!
![image](https://github.com/Mastermindzh/tidal-hifi/assets/67262050/70714a26-204a-4d4f-846b-5fa4fadf18da)

**Comment by muznyo** [comment]
> Opened the app a few hours ago but the Master and HiFi were still there. Opened it now and we just got Max and High! ![image](https://user-images.githubusercontent.com/67262050/258256802-70714a26-204a-4d4f-846b-5fa4fadf18da.png)

I don't know if it actually uses [Max quality](https://www.reddit.com/r/TIdaL/comments/15iqlw2/max_available_on_web_however_as_a_ubuntulinux/) though...

**Comment by saku-bruh** [comment]
> > Opened the app a few hours ago but the Master and HiFi were still there. Opened it now and we just got Max and High! ![image](https://user-images.githubusercontent.com/67262050/258256802-70714a26-204a-4d4f-846b-5fa4fadf18da.png)
> 
> I don't know if it actually uses [Max quality](https://www.reddit.com/r/TIdaL/comments/15iqlw2/max_available_on_web_however_as_a_ubuntulinux/) though...

Interesting... might be a limitation with Chrome itself? or maybe they've just blocked it lol but it doesn't say that it's blocked like it did before so...

**Comment by Mastermindzh** [comment]
After giving it some thought I don't think we should update the name actually. 

Tidal's main website still promotes "hifi" all over the place.
Any opinions on keeping the name the same?

**Comment by Nyabinary** [comment]
They probably haven't updated it yet, to be fair. Also, Tidal Max sounds cooler but that's just me.

**Comment by Mastermindzh** [comment]
They use in the most recent website changes as well:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/4a5d3023-63df-471d-ad58-e115c5c7edf6)

Still, high fidelity (or hifi) was never really tied to the audio tier "hifi" but to Tidal's higher fidelity audio as compared to others.
As such, tidal-hifi is just a marketing name for this specific open-source version.

@Nyabinary, I will update the readme & description to include max since it is indeed cool 😎

**Comment by Nyabinary** [comment]
Nice!
