### ISSUE TITLE
Native Wayland Support

### ISSUE THREAD

**Issue by Nyabinary** [Mastermindzh/tidal-hifi#262]
This should be simple since it's just passing a flag to Electron ``--ozone-platform-hint``
https://github.com/electron/electron/issues/33810
https://github.com/electron/electron/pull/34937
Support for this flag was added last year.

**Comment by Mastermindzh** [comment]
Hey @Nyabinary,

Not a problem!
Can you confirm things work as expected? Are there any bugs if you enable the flag?

There are a couple of big things I want to do in the coming month or so:

- Look at theming again (some errors in my theme files)
- Implement plugins (requested)
- Implement flag management (this + some other questions)

If this flag results in little/no bugs it could move upwards in priority (though the list is unordered atm)

Thanks for the help anyway!~

**Comment by Mastermindzh** [comment]
I'll just load up Gnome next to my i3 instance and test from there when I add it.
Glad to hear everything seems to work, that means this is quite minor.

I recommend you change your .desktop file to include the extra parameters for now and I'll see when I can add a "wayland support" flag :)

**Comment by Nyabinary** [comment]
Yeah, I checked everything, and no bugs only thing is "Manage Subscription" pop-up window is broken, but it's also broken in X11 as well.

**Comment by Nyabinary** [comment]
I just realized this solved the weird bug I had when in GNOME. The app didn't show up in the taskbar as, well.
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/6c74b46a-946b-4167-a516-2112b2d7bae5)

**Comment by Mastermindzh** [comment]
Ah... so Wayland also does something for the icons in the (now wayland backed...) taskbar. Gotcha.


Idk what you're talking about with manage subscriptions (I am on the highest tier so I have no need to go there...).
Can you tell me what you encounter where? Might be an additional bug that we can solve along the way somewhere 😄 

Thanks for the detailed responses! Very helpful!

**Comment by Nyabinary** [comment]
Going over here and clicking managing subscription pops up an additional window on both X11 and Wayland, but both windows show the fixed menu bar and title bar(even if you have the fixed menu bar enabled or disabled), the body of the window itself is blank.
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/2b239be3-a389-496b-8b5f-1315c278d3b7)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/ba2215dd-42d6-4179-9868-9c50e17a4237)

**Comment by Nyabinary** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/5c456eb7-9302-425d-be94-4defa1669b1e)
Another thing to note, when I use the X11 version, this pops up in the terminal (the last line specifically)

**Comment by Mastermindzh** [comment]
@Nyabinary Chrome rendering errors showing up are... normal 😄.

Also... I just fixed flag parsing... (was messed up..) and also added Wayland support:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/1d9dc15a-d826-4179-b7da-77e78e5802d9)

Will be available in the next release that will be released later this week 😄
