### ISSUE TITLE
Add TidalTags

### ISSUE THREAD

**Issue by muznyo** [Mastermindzh/tidal-hifi#263]
Since new Tidal update, we don't know if the music is MQA, or FLAC or even both.
This [extension](https://github.com/Inrixia/TidalTags) solves that.

It would be a nice addition.

**Comment by Mastermindzh** [comment]
I can research this.
It seems like all the results I get are "LOSSLESS" when I look at the HTTP calls though :)

**Comment by Mastermindzh** [comment]
Unfortunately, this won't be possible.
The extension uses the unofficial API which I don't want to rely on.

Sorry.
