### ISSUE TITLE
Unable to select High audio quality

### ISSUE THREAD

**Issue by HurleybirdJr** [Mastermindzh/tidal-hifi#264]
I'm not able to select the **`High`** audio quality setting at all in both the main page and the streaming settings. 
Shown in the photos below, the **`High`** setting is greyed out and when I hover over it it shows a not-allowed icon. <img src="https://github.com/Mastermindzh/tidal-hifi/assets/45840763/c797607f-67ae-4f42-bcf2-b0dd2203b96c" width="16" height="16">

I've checked to see if this was an account issue but on the https://listen.tidal.com website on my Firefox browser, it works as intended, and additionally shows my username and subscription type in the settings and top left, whereas in the tidal-hifi version, these are blank or missing.

I've tried reinstaling and logging-out and both and nothing seems to fix the issue :(

<img src="https://github.com/Mastermindzh/tidal-hifi/assets/45840763/f9be7e24-f052-455a-9279-148c10da6978" width="40%" height="40%">
<img src="https://github.com/Mastermindzh/tidal-hifi/assets/45840763/7eb8e285-b632-4016-b397-f512b6e8ca74" width="40%" height="40%">
<img src="https://github.com/Mastermindzh/tidal-hifi/assets/45840763/cbd08db2-7b77-4612-a377-1dd15f13806a" width="40%" height="40%">
<img src="https://github.com/Mastermindzh/tidal-hifi/assets/45840763/a8604531-dce8-49db-9fed-35db8930555d">

**Comment by Mastermindzh** [comment]
Do you have any environment info?
I am working on tidal-hifi right now and am sitting at max:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/3e02da80-57b6-4045-af0a-3a39b8d77a5c)

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/c01c17d4-e930-44b2-b0da-22df825da291)
can also actually play max

**Comment by HurleybirdJr** [comment]
> Do you have any environment info? 
> I am working on tidal-hifi right now and am sitting at max:

Where and how should I look to find my environment info? I'm not especially adept with Linux yet, what details would be useful to know?

**Comment by Mastermindzh** [comment]
There is definitely a way to clear the cache files, if you just upgraded your account that might help 😄.

To clear all the cache (including custom config + login info) you can run:

`rm -rf ~/.config/tidal-hifi/`

When you are asked for environment info on Linux you are (usually) expected to provide the following things:

- desktop environment (e.g gnome, kde, whatever)
- shell (e.g. bash, if running from cli)
- flavor (e.g. Ubuntu, arch linux)
- version of flavor (e.g. Ubuntu 21.04)
- kernel version (e.g. 6.4.4)

You can gather them all separately by using a few commands, or by using a single tool like `neofetch` to provide them all at once:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/7d348774-5209-4877-84aa-b240d1bf1b3a)

Separate commands would look something like..:

```sh
# desktop environment
echo "$XDG_CURRENT_DESKTOP"

# shell
echo "$SHELL"

# flavor + version
# you can use cat /etc/os-release to get most info or use the next command for A LOT:
cat /etc/*release

# kernel version
uname -a
```

Doing that all gives you the following: (ignore the `-p` on cat... I'm using `bat` as a `cat` replacement):

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/df02b8bb-89da-41a0-8172-7979f1021fa6)

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/6569e357-3c86-4df5-ba70-159a02ae4b6a)

`Notice - Moe shop` (got that from your title bar) should support at maximum `High`

**Comment by Mastermindzh** [comment]
I guess it has to do with the subscription btw, since mine displays the subscription correctly:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/c181b825-4095-439f-bfaf-f8b72200e5c9)

**Comment by HurleybirdJr** [comment]
Awesome, thanks for the advice and wisdom!

Here's the result of `neofetch` on my system:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/45840763/2d238510-231e-4334-91e8-77894b1b8e43)

I also cleared cache using the command you provided and that seems to have fixed the issue ✅.  I'm unsure as to what caused the problem as I haven't recently upgraded or changed from my current subscription. Everything now appears and works as normal, showing username and subscription correctly :)

From what I recall, I remember having slow internet so reduced the quality to save bandwidth and then couldn't change back after the fact.

### Many thanks for the help though, I appreciate it greatly and for the advice regarding environment info, that makes much more sense now <3

PS: Yeah the album art certainly is very detailed, I'm personally just an enjoyer of the music style itself as opposed to the anime vocalist, but nonetheless it's groovy track I enjoy :p

**Comment by HurleybirdJr** [comment]
OK, just tried recreating the problem on my end again, and it's consistent with what happened last time.

These were the steps I took that caused it:
- Select low quality (320kpbs) on any track.
- Change to another track to make changes take effect.
- Close tidal-hifi
- Reload and now High quality is greyed and account details are missing.

Using `rm -rf ~/.config/tidal-hifi/` to clear cache, etc... fixes the problem after logging back in.

**Comment by Mastermindzh** [comment]
No problem 😄, glad I could help.

Seems it is yet another Tidal browser cache issue, I'm sure they'll get it sorted out relatively quickly (as with all the other High/Max issues that are going on).

Great that there is a workaround though.

Enjoy the tunes!

**Comment by seanlowe** [comment]
Any thoughts on a potential solution for when there is no `~/.config/tidal-hifi/` directory?

**Comment by Mastermindzh** [comment]
`~/.config` is the default config location on most Linux distros but it can be changed.

So remove or look for the cache files in the place where your distro stores its application specific config files :)
