### ISSUE TITLE
Tidal-HiFi isn't passing bits perfect streaming to my USB DAC on an Arch Linux Box. 

### ISSUE THREAD

**Issue by bruce-awareit** [Mastermindzh/tidal-hifi#266]
Max available on Tidal-HiFi. However, as a Linux user, Tidal-HiFi isn't passing High Res FLAC to my USB DAC.

Only 48KHz flac passed to my USB DAC.  But the DAC works fine with other music players, deadbeef ...,etc.

**Comment by Mar0xy** [comment]
This is a duplicate of #244

**Comment by Nyabinary** [comment]
@Mar0xy https://www.reddit.com/r/TIdaL/comments/15iqlw2/max_available_on_web_however_as_a_ubuntulinux/
Nope this is an issue with Electron/Chromium it works fine on Firefox.

**Comment by Mastermindzh** [comment]
I can test with my DAC tomorrow.
It's gone above 48khz when MAX just launched though but on a VERY limited set of songs from their "new hi-res" playlist.

**Comment by Mastermindzh** [comment]
tidal-hifi uses a patched chromium instance making this possible, see [Castlabs' website](https://castlabs.com/) for more details.

Can you verify your output is actually set and capable of receiving higher-quality output?
I use `pacmd list-sinks` for that and get:

```
 * index: 0
	name: <alsa_output.usb-Klipsch_Klipsch_HP_Amp-00.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE
	priority: 9049
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 0.00 ms
	max request: 0 KiB
	max rewind: 0 KiB
	monitor source: 1
	sample spec: s16le 2ch 192000Hz
	channel map: front-left,front-right
	             Stereo
```

This shows that, at least, my DAC/amp is set up correctly for Linux. I can also use `cat /proc/asound/card5/pcm0p/sub0/hw_params` (find `card5` by using `cat /proc/asound/cards`) to see the hardware params.

You can also use `pacmd list-sink-inputs` whilst tidal-hifi is playing to see what it is claiming to send to your amp/dac, in my case:

```
2 sink input(s) available.
    index: 8
	driver: <protocol-native.c>
	flags: START_CORKED 
	state: CORKED
	sink: 0 <alsa_output.usb-Klipsch_Klipsch_HP_Amp-00.analog-stereo>
	volume: front-left: 53127 /  81% / -5.47 dB,   front-right: 53127 /  81% / -5.47 dB
	        balance 0.00
	muted: no
	current latency: 189.23 ms
	requested latency: 75.00 ms
	sample spec: float32le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	resample method: speex-float-1
	module: 15
	client: 206 <Firefox>
	properties:
		media.name = "AudioStream"
		application.name = "Firefox"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "11390"
		application.process.user = "mastermindzh"
		application.process.host = "linux-ryzen"
		application.process.binary = "firefox"
		application.language = "C.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "5fb2b0eb1ba54e48a9932d8c5fe7e5e0"
		application.process.session_id = "2"
		application.icon_name = "firefox"
		module-stream-restore.id = "sink-input-by-application-name:Firefox"
    index: 9
	driver: <protocol-native.c>
	flags: START_CORKED 
	state: RUNNING
	sink: 0 <alsa_output.usb-Klipsch_Klipsch_HP_Amp-00.analog-stereo>
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	muted: no
	current latency: 33.94 ms
	requested latency: 21.33 ms
	sample spec: float32le 2ch 192000Hz
	channel map: front-left,front-right
	             Stereo
	resample method: copy
	module: 15
	client: 239 <Chromium>
	properties:
		application.icon_name = "chromium-browser"
		media.name = "Playback"
		application.name = "Chromium"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "8042"
		application.process.user = "mastermindzh"
		application.process.host = "linux-ryzen"
		application.process.binary = "tidal-hifi"
		application.language = "C.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "5fb2b0eb1ba54e48a9932d8c5fe7e5e0"
		application.process.session_id = "2"
		media.role = "music"
		module-stream-restore.id = "sink-input-by-media-role:music"
```

also note that the `resample method` is `copy for tidal-hifi`, which can change when pulseaudio is actually resampling things itself (e.g. when multiple things are playing) but when it says copy it's sending things straight to the dac!

I tested with these two things:

- [Youtube](https://www.youtube.com/watch?v=8AHCfZTRGiI)
- [Tidal](https://tidal.com/browse/track/309177518)

My amp/dac also reflects these changes (PS: sorry for the grime on the button, I just saw that LOL):

Youtube:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/9e80e25a-059b-467f-a2ae-18d5746a15cd)

Tidal-hifi:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/40d77a22-9a59-4bc2-ae8e-92cd258ad815)

This is roughly the way I have always analyzed these things.
Unfortunately, my DAC doesn't show whether sound is uncompressed or not 😄

**Comment by bruce-awareit** [comment]
> tidal-hifi uses a patched chromium instance making this possible, see [Castlabs' website](https://castlabs.com/) for more details.

Here is my DAC infomations and I use pipewire-pulse over pipewire on my linux box.

$ cat /proc/asound/card3/stream0 
PureAudio Lotus DAC5 at usb-0000:00:14.0-10, high speed : USB Audio

Playback:
  Status: Running
    Interface = 1
    Altset = 1
    Packet Size = 72
    Momentary freq = 48000 Hz (0x6.0000)
    Feedback Format = 16.16
  Interface 1
    Altset 1
    Format: S32_LE
    Channels: 2
    Endpoint: 0x01 (1 OUT) (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
    Data packet interval: 125 us
    Bits: 24
    Channel map: FL FR
    Sync Endpoint: 0x81 (1 IN)
    Sync EP Interface: 1
    Sync EP Altset: 1
    Implicit Feedback Mode: No
  Interface 1
    Altset 2
    Format: S16_LE
    Channels: 2
    Endpoint: 0x01 (1 OUT) (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
    Data packet interval: 125 us
    Bits: 16
    Channel map: FL FR
    Sync Endpoint: 0x81 (1 IN)
    Sync EP Interface: 1
    Sync EP Altset: 2
    Implicit Feedback Mode: No
  Interface 1
    Altset 3
    Format: SPECIAL
    Channels: 2
    Endpoint: 0x01 (1 OUT) (ASYNC)
    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
    Data packet interval: 125 us
    Bits: 32
    DSD raw: DOP=0, bitrev=0
    Channel map: FL FR
    Sync Endpoint: 0x81 (1 IN)
    Sync EP Interface: 1
    Sync EP Altset: 3
    Implicit Feedback Mode: No

#when I played an 192000 kHz track.

$ cat /proc/asound/card3/pcm0p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 192000 (192000/1)
period_size: 512
buffer_size: 32768

![圖片](https://github.com/Mastermindzh/tidal-hifi/assets/88933609/a1aadd2a-a129-4d4e-8114-9749f789a858)

**Comment by artudytu** [comment]
Not only it doesn't play MQA which I guess is expected (but tracks are still labeled as max), it doesn't even play flac - instead it says "high" on tracks that are normally labeled "max" (ie Shallow from A star is born soundtrack).

On my iphone it plays through DAC at 192k which I'm guessing is flac, because my DAC isn't MQA compatible, so I guess it plays MQA tracks only at 44k sample rate

Is it just me?

```
* index: 3
	name: <alsa_output.usb-LH_Labs_Geek_Out_HD_Audio_1V0-00.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: IDLE
	suspend cause: (none)
	priority: 9049
	volume: front-left: 26375 /  40% / -23.72 dB,   front-right: 26375 /  40% / -23.72 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 2008.92 ms
	max request: 1500 KiB
	max rewind: 1500 KiB
	monitor source: 4
	sample spec: s32le 2ch 96000Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 0
	configured latency: 2000.00 ms; range is 0.50 .. 2000.00 ms
	card: 5 <alsa_card.usb-LH_Labs_Geek_Out_HD_Audio_1V0-00>
	module: 25
	...
```

**Comment by Mastermindzh** [comment]
Pulseaudio tends to output at a single rate and intermixes everything else into it.
It's all very complicated and messy, unfortunately.

Bruce-awareit's setup seems to be working now but doesn't send the actual **bit perfect** stream to his DAC which I have no way of verifying with my gear but I also don't find too important for my own use case.

However, yours looks like standard pulse issues, which are a b*tch to figure out!

**Comment by mkogan1** [comment]
Having same problem on Fedora 38, specifically, think it's because PipeWire introduces another level of complication.
Has anyone achieved bit-perfect with PipeWire and can provides some tips how to achieve it with PipeWire configuration please?

**Comment by bruce-awareit** [comment]
> Having same problem on Fedora 38, specifically, think it's because PipeWire introduces another level of complication. Has anyone achieved bit-perfect with PipeWire and can provides some tips how to achieve it with PipeWire configuration please?

There is a good reference. Please refer to the "setting Sample Rates" section.
https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PipeWire#setting-sample-rates

But this just works on Firefox and some media players, such as deadbeef. And it does not work on Tidal-hifi and Chrome.

The problem seems to be introduced by Chrome or Electron. Then Tidal-hifi just not works.

**Comment by mkogan1** [comment]
for future reference, hope will be useful to someone and in context of Tidals FLAC support

Bit Rate:
ref:
https://discussion.fedoraproject.org/t/how-to-change-sampling-rate-and-bit-depth/75935 – How to change sampling rate and bit depth?
https://discussion.fedoraproject.org/t/standard-s-for-accessing-pipewire-configuration-for-audio-software/67597 – Standard(s) for accessing pipewire configuration for audio software?
https://wiki.archlinux.org/title/PipeWire – PipeWire
```
ls -ld ~/.config/pipewire

cp -vrf /usr/share/pipewire ~/.config


cd ~/.config/pipewire

ls -l

cp -v ./pipewire.conf ./pipewire.conf.BAK
vim ./pipewire.conf
...
    ## Properties for the DSP configuration.
    #default.clock.rate          = 48000
    default.clock.rate          = 192000
    #default.clock.allowed-rates = [ 48000 ]
    default.clock.allowed-rates = [ 44100, 48000, 88200, 96000, 192000 ]
...
:x


systemctl --user restart pipewire pipewire-pulse


pw-top
RATE    WAIT    BUSY   W/Q   B/Q  ERR FORMAT           NAME
S   28      0      0    ---     ---   ---   ---     0                  Dummy-Driver
S   29      0      0    ---     ---   ---   ---     0                  Freewheel-Driver
S   39      0      0    ---     ---   ---   ---     0                  Midi-Bridge
S   51      0      0    ---     ---   ---   ---     0                  v4l2_input.pci-0000_00_14.0-usb-0_4_1.0
S   53      0      0    ---     ---   ---   ---     0                  v4l2_input.pci-0000_00_14.0-usb-0_4_1.2
S   55      0      0    ---     ---   ---   ---     0                  v4l2_input.pci-0000_00_14.0-usb-0_7.1.1_1.1
S   61      0      0    ---     ---   ---   ---     0                  alsa_input.usb-Generic_ASUS_AI_Noise-Cancelling_Mic_Adapter_201701110001-00.iec958-stereo
R   62   2048 192000  26.3us  12.7us  0.00  0.00    0   S32LE 2 192000 alsa_output.usb-Cayin_Cayin_N3Pro-00.iec958-stereo
R   66   4096 192000  10.1us  12.4us  0.00  0.00    0   F32LE 2 192000  + Google Chrome
              ^^^^^^
```

Resampling Quality:
ref:
https://wiki.archlinux.org/title/PipeWire#Sound_quality_(resampling_quality) – Sound quality (resampling quality)
```
cd ~/.config/pipewire

cp -v ./client.conf ././client.conf.BAK
cp -v ./pipewire-pulse.conf ./pipewire-pulse.conf.BAK

vim ./client.conf ./pipewire-pulse.conf
...
stream.properties = {
    #node.latency          = 1024/48000
    #node.autoconnect      = true
    #resample.quality      = 4
    resample.quality      = 10
...

systemctl --user restart pipewire pipewire-pulse
```

**Comment by Mastermindzh** [comment]
Thanks for all the info guys 😄.
This is turning out to be quite a repository of knowledge for audio administration.

**Comment by BlueManCZ** [comment]
@mkogan1 Now the main question is when you set `default.clock.rate = 192000` in pipewire config, is playback from TIDAL service really at the maximum possible sample rate, or is Chromium just upsampling everything to 192kHz? Because even when you switch to High - 44.1kHz, `pw-top` still shows 192kHz, so some upsampling must happen. And there is no guaranteed way of confirming that the Max quality is not just upsampled as well.

@Mastermindzh Aren't there some devtools for audio debugging inside the Chromium? Something that would show us at what sample rate the source is really playing before it goes out to the Linux system.

**Comment by Mastermindzh** [comment]
Hey @BlueManCZ,

Not that I know of, no.

**Comment by BlueManCZ** [comment]
@Mastermindzh This looks like something I was writing about: https://github.com/Mastermindzh/tidal-hifi/issues/244#issuecomment-1667317159 I'll try to investigate more when I get back to the Linux system. For now, it seems to be exactly the case I was worried about - that the Max quality is just a visual yellow badge playing internally at 44.1kHz and being upsampled to whatever is set in the system.

**Comment by Mastermindzh** [comment]
It might very well do that with pipewire. don't use pipewire so I have no clue about it.
We can reasonably assume that the Castlabs version of Chromium/Electron is actually built correctly, that is their entire business model 😄 .
From my tests in various topics (and those of some others) we can also reasonably assume that our systems aren't lying with pulseaudio or alsa in place.

**Comment by mkogan1** [comment]
> @mkogan1 Now the main question is when you set `default.clock.rate = 192000` in pipewire config, is playback from TIDAL service really at the maximum possible sample rate, or is Chromium just upsampling everything to 192kHz? Because even when you switch to High - 44.1kHz, `pw-top` still shows 192kHz, so some upsampling must happen. And there is no guaranteed way of confirming that the Max quality is not just upsampled as well.
 
It's a compromise, depends on ones music library preferences, if most of the preferred albums are in > 48 kHz than think that up-sampling to 192 kHz would be preferable and if not better to keep the default 48 kHz rate
That being said, still trying to hear the "improvement" in audio quality subjectively when listening to allegedly > 48 kHz tracks, yet for now subjectively can't tell unequally that can hear an improvement although think that should be able to...

**Comment by mkogan1** [comment]
after setting pipewire bit-rate with pipewire cli:
```
pw-metadata -n settings 0
pw-metadata -n settings 0 clock.allowed-rates '[ 44100, 48000, 88200, 96000 ]'
pw-metadata -n settings 0 clock.rate 96000
pw-metadata -n settings 0 clock.force-rate 96000
pw-metadata -n settings 0
```

checking with `pw-top` shows tidal web-player when using _tidal-hifi_ **is** streaming high bitrate to the DAC:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/31659604/a5fdc081-c43e-4777-9702-55c397ca1d93)

vs with chrome web-player it does not:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/31659604/15413832-e4ce-4c20-8733-ed7edfbbce5d)

**Comment by BlueManCZ** [comment]
I don't know how setting with pipwire cli is related, but in my case, with just normal pipewire config Google Chrome is streaming high bitrate to the DAC:

![obrazek](https://github.com/Mastermindzh/tidal-hifi/assets/17854950/52747241-387f-4169-8128-cce0f68d77e4)

```
» pw-metadata -n settings 0
Found "settings" metadata 31
update: id:0 key:'log.level' value:'2' type:''
update: id:0 key:'clock.rate' value:'192000' type:''
update: id:0 key:'clock.allowed-rates' value:'[ 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000 ]' type:''
update: id:0 key:'clock.quantum' value:'1024' type:''
update: id:0 key:'clock.min-quantum' value:'32' type:''
update: id:0 key:'clock.max-quantum' value:'2048' type:''
update: id:0 key:'clock.force-quantum' value:'0' type:''
update: id:0 key:'clock.force-rate' value:'0' type:''
```

**Comment by mkogan1** [comment]
> I don't know how setting with pipwire cli is related, but in my case, with just normal pipewire config Google Chrome is streaming high bitrate to the DAC:

@BlueManCZ  which OS may ask please?

**Comment by BlueManCZ** [comment]
> @BlueManCZ which OS may ask please?

It's Gentoo Linux. Google Chrome installed with [this ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/google-chrome/google-chrome-118.0.5993.117.ebuild).

**Comment by MobCode100** [comment]
When inspecting tidal-hifi using remote debugging, tidal-hifi indeed outputs the highest possible track at 96 Khz. Still pw-top shows the default sample rate at 48 Khz. I don't have a DAC yet to try but will buy a new one soon.

<img src=https://github.com/Mastermindzh/tidal-hifi/assets/66469454/4f43d0b5-d40d-4288-a11c-309f30016bcb width="50%" />
<img src=https://github.com/Mastermindzh/tidal-hifi/assets/66469454/1e0edbeb-bf1f-4130-942e-4b9b0a41e7ef width="50%" />

**Comment by mkogan1** [comment]
> Apparently, chromium browsers will resample to the default sample rate set, and is still [an open issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1385272&q=pipewire&can=2). For the time being while waiting chromium to fix this, I'll set the default sample rate to the max of my sound card. It's not bit perfect, but at least the audio playback will not lose quality.

FWIW for anyone interested, there been some updates to fedora _*wire*_ infras since last post, 
the way that currently configuring the sample rates on F39 is:
1. get the supported HW sample rates:
`grep -r -H -E 'Rates|Bits|Card' /proc/asound/card*`
```
/proc/asound/card0/stream0:    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
/proc/asound/card0/stream0:    Bits: 24
/proc/asound/card0/stream0:    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
/proc/asound/card0/stream0:    Bits: 16
/proc/asound/card0/stream0:    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
/proc/asound/card0/stream0:    Bits: 32
/proc/asound/card0/stream0:    Rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000
/proc/asound/card0/stream0:    Bits: 32
/proc/asound/card0/usbmixer:Card: Cayin Cayin N3Pro at usb-0000:00:14.0-7.2, high speed
```
2. configure them in in `~/.config/pipewire/pipewire.conf.d/pwrate.conf`
```
cat ~/.config/pipewire/pipewire.conf.d/pwrate.conf
{
  "context.properties": {
    "default.clock.rate": 96000,
    "default.clock.allowed-rates": [
      44100,
      48000,
      88200,
      96000,
      192000,
      352800,
      384000
    ]
  }
}
```
3. restart *wire*:
`systemctl --user restart wireplumber pipewire pipewire-pulse.service pipewire-pulse.socket`

**Comment by Mastermindzh** [comment]
Anyone interested in writing a docs article in the docs folder with a bit of a summary / approach?
I'd be happy to accep tit.

**Comment by Hirsebrei3** [comment]
Same problem here. Resamples to default-clock-rate in pipewire. As chrom(*) does.
mpd, pcm ans DSD run fine. Also deezer in Firefox (44.1kHz).
Is there still a solution?

**Comment by Hirsebrei3** [comment]
Same problem here. Resamples to default-clock-rate in pipewire. As chrom(*) does.
mpd, pcm and DSD run fine. Also deezer in Firefox (44.1kHz).
Is there still a solution?

**Comment by V0ID-Whisperer** [comment]
> 

https://github.com/Mastermindzh/tidal-hifi/issues/266#issuecomment-1757223763
Try setting that but with ur rates

**Comment by Hirsebrei3** [comment]
Thanks,
I tried this. This forces, as expected, samplerate generally to 96k, while song is e.g. 44.1kHz/24. 
Why the hell is Chrome resampling, what do the developer smoke...?
Firefox doesn't do this, but needs pulse(-emulation), unfortunately doesn't function with Tidal - under Linux, don't know about Windows.

**Comment by C-O-D** [comment]
When I play TIDAL in KODI with the tidal2 addon (on Manjaro) I can see how the sample rate jumps back and forth depending on the song. But I also like to use TIDAL Hifi and I would expect an app explicitly for TIDAL to display the corresponding features correctly, especially if it's a special version of Chromium in this case.
Pipewire offers all the necessary prerequisites for dynamic sample rate switching - setting the system to the highest possible sample rate so that everything else is resampled is a lazy compromise, or am I being too demanding here?

**Comment by Mastermindzh** [comment]
See: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2828

It seems that chromium is simply selecting the default if not explicitly set.

**Comment by Hirsebrei3** [comment]
No, it's a unfixed known issue for ALL chromium-based browsers. Tested without pipewire and native alsa.
Read somewhere that chrom*** does this per default. All other resampling is done by pw.

**Comment by C-O-D** [comment]
Bad didn't you say you're using a custom made version which is doing it right, @Mastermindzh?

**Comment by Mastermindzh** [comment]
@C-O-D ,

We're using Castlabs' electron version which enables DRM playback. It shouldn't change anything else.

I've been setting the default as described above/earlier and been calling it a day :)

**Comment by C-O-D** [comment]
I actually think it's a bit of a shame that you're content with that, not least because it means that I / we will continue to listen to a large proportion of upsampled music and not really use the possibilities that pipewire offers...

**Comment by Mastermindzh** [comment]
@C-O-D I'm not happy with it either but the community at large can't convince Google to change it so there's really no helping it :/

**Comment by nyabinary** [comment]
How would one fix it with NixOS?

**Comment by andresilva** [comment]
This is what I have on my NixOS config:

```nix
let
  resample-quality = {
    "10-resample-quality" = {
      "stream.properties" = {
        "resample.quality" = 10;
      };
    };
  };
in
{
  services.pipewire = {
    enable = true;

    alsa.enable = true;
    jack.enable = true;
    pulse.enable = true;

    extraConfig.pipewire = {
      "10-clock-rate" = {
        "context.properties" = {
          "default.clock.rate" = 96000;
          "default.clock.allowed-rates" = [
            44100
            48000
            88200
            96000
            176400
            192000
          ];
        };
      };
    };

    extraConfig.client = resample-quality;
    extraConfig.pipewire-pulse = resample-quality;
  };
}
```

I wrote this a long time ago so I don't really remember any details, but this makes electron default to 96kHz. If the content is 44.1kHz or 48kHz it will just resample, afaik there's no way to do dynamic sample rate switching with electron so you'll be stuck at 96kHz. Other sources (e.g. firefox or chrome), will switch to the appropriate sample rate (usually 48kHz for most content).

**Comment by mkogan1** [comment]
FYI, It's working with https://github.com/Nokse22/high-tide -- Libadwaita TIDAL client for Linux 

For example on Fedora 42 KDE:

1. Configured the DAC to IEC958:

![Image](https://github.com/user-attachments/assets/73268c81-f283-4a60-964c-9a4f6557b6ee)


2. Enabled the supported bit rates:

```
❯ grep -r -H -E 'Rates|Bits|Card' /proc/asound/card*
...
/proc/asound/card0/stream0:    Rates: 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000
...
/proc/asound/card0/usbmixer:Card: iFi (by AMR) iFi (by AMR) HD USB Audio at usb-0000:00:14.0-5.2, high speed
```

```
pw-metadata -n settings 0 clock.allowed-rates '[ 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000, 705600, 768000 ]'
```

3. configure High-Tide:

![Image](https://github.com/user-attachments/assets/02f936d5-dff1-4c05-83b3-40c13b93702e)


![Image](https://github.com/user-attachments/assets/a6c0b3e1-e287-48a1-855f-fcf39fd216f2)

**Comment by C-O-D** [comment]
@mkogan1 Hey, thanks for the tip - didn't know the programme yet and it works perfectly

**Comment by lucianoiam** [comment]
I finally fixed it by tweaking PipeWire config:

~/.config/pipewire/pipewire.conf.d/99-samplerate.conf

```
context.properties = {
    default.clock.rate = 192000 
}
```

~/.config/wireplumber/main.lua.d/50-alsa-config.lua

```
table.insert(alsa_monitor.rules, {                                              
  matches = {                                                                   
    { { "device.name", "matches", "alsa_card.< ALSA_CARD_ID >" } }   
  },                                                                            
  apply_properties = {                                                          
    ["api.acp.probe-rate"] = 192000                                             
  }                                                                             
})  
```

If 50-alsa-config.lua does not exist copy from /usr/share/wireplumber/main.lua.d/50-alsa-config.lua
ALSA_CARD_ID can be found using the `pw-dump` command

edit: removed the default.clock.allowed-rates line from 99-samplerate.conf, default.clock.rate seems to be enough.

**Comment by lucianoiam** [comment]
<img width="1360" height="252" alt="Image" src="https://github.com/user-attachments/assets/27c2d740-d35f-40f8-b19b-d21c5fc23e0c" />

**Comment by bruce-awareit** [comment]
@lucianoiam
Your configuration seem to use the fix sampling rate at 192000, not really pass the bits perfect streaming.

**Comment by lucianoiam** [comment]
That's right. Is the sample rate changing dynamically depending on the playing track, the expected behavior?
PipeWire default config is capping all three rows to 48000 Hz, at least on my system.

**Comment by worldowner** [comment]
Of course, this is expected behavior. However, Chromium-based software is unable to do that because Chromium itself resamples everything to whatever is set as the default (48 kHz in most cases).

**Comment by jiriks74** [comment]
Linking a comment from my issue https://github.com/Mastermindzh/tidal-hifi/issues/760#issuecomment-3649789355:

> For those that don't want to set a permanent high sample rate, you can run the following command to set the default sample rate to 192kHz at runtime:
> 
> ```bash
> pw-metadata -n settings 0 clock.rate 192000
> ```
> 
> Eg. you can keep your favorite default and run this just before you launch Tidal-HiFi to force it to 192kHz.

**Comment by C-O-D** [comment]
> Linking a comment from my issue [#760 (comment)](https://github.com/Mastermindzh/tidal-hifi/issues/760#issuecomment-3649789355):
> 
> > For those that don't want to set a permanent high sample rate, you can run the following command to set the default sample rate to 192kHz at runtime:
> > pw-metadata -n settings 0 clock.rate 192000
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Eg. you can keep your favorite default and run this just before you launch Tidal-HiFi to force it to 192kHz.

...and that means Chromium will not resample in this case if the source is also 192 kHz?
In other words, if Chromium is always involved in resampling processes anyway, the whole thing is worthless...

**Comment by HideMyUsername1** [comment]
Is there any other way to get Tidal running at 24bit 192khz without resampling?

**Comment by C-O-D** [comment]
> Is there any other way to get Tidal running at 24bit 192khz without resampling?

https://github.com/Nokse22/high-tide

**Comment by mkogan1** [comment]
> > Is there any other way to get Tidal running at 24bit 192khz without resampling?
> 
> https://github.com/Nokse22/high-tide

few more lossless playback linux clients:
* https://github.com/lullabyX/sone
* https://flathub.org/en/apps/dev.dergs.Tonearm

**Comment by Mastermindzh** [comment]
I've since added a guide how to setup your Linux system to at least use the correct up/down-sampling settings:

https://github.com/Mastermindzh/tidal-hifi/blob/master/docs/audio-quality.md
