### ISSUE TITLE
Intergrate Neptune inside tidal-hifi natively

### ISSUE THREAD

**Issue by Nyabinary** [Mastermindzh/tidal-hifi#268]
It would be cool to have Neptune integrated natively as, for now, there isn't a Linux installer for it, plus it can bring a lot more attention to Neptune as well; there should be a GitHub link though through the about me page or integration page or both!
https://github.com/uwu/neptune

**Comment by Mastermindzh** [comment]
Neptune is linked on the homepage readme and that's about as far as I'd like to take it honestly.

I tried offering more native integration to the dev in my discord but he never really replied, choosing instead to push his/her own additional installer much like better discord.

I also offered to include a plugin system straight into tidal-hifi before they got started but again, no reply.

If you'd like to see plugins feel free to open a feature request and I'll add them (just like we added native theming).

Thanks for the idea though!

**Comment by Nyabinary** [comment]
@Mastermindzh Installing Neptune and installing the experiment plugin causes Tidal to detect the client/ip as a bot and puts up a captcha, but the captcha doesn't appear in the native version of Tidal-Hifi. It does, however show up in the Flatpak version of Tidal-Hifi, which is currently versioned 5.5.0. 
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/2ae771bb-a0f6-4b8c-8774-a8bf5a739505)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/89c52ef4-f072-46cd-ac71-cbd0300c6b3c)

**Comment by twnlink** [comment]
https://www.youtube.com/watch?v=Mn6834_O1XM

**Comment by Mastermindzh** [comment]
@Nyabinary 

Yeah, all popups from the native version stay white for a reason I haven't figured out yet.

Truth be told, it hasn't really gotten in the way of useful features before (can't see your subscription details.. but other than that .. nothing we know of).

Let's make a new issue listing what is broken with the popups!

**Comment by Mar0xy** [comment]
>  It does, however show up in the Flatpak version of Tidal-Hifi, which is currently versioned 5.5.0.

It shows up in Flatpak cause I had to disable electron's sandbox to make it work on flatpak and it was already known that disabling the sandbox with `--no-sandbox` fixes the pop-ups

**Comment by Nyabinary** [comment]
Hmm is there a workaround without disabling sandbox?

**Comment by Mar0xy** [comment]
in case of Flatpak having it be disabled no cause of flatpak's own sandbox

in case of native versions I have no clue if it is possible

**Comment by Mastermindzh** [comment]
> > It does, however show up in the Flatpak version of Tidal-Hifi, which is currently versioned 5.5.0.
> 
> It shows up in Flatpak cause I had to disable electron's sandbox to make it work on flatpak and it was already known that disabling the sandbox with `--no-sandbox` fixes the pop-ups

I totally forgot, thanks for the reminder 😄

**Comment by ThatOneCalculator** [comment]
Are there any instructions on how to install Neptune into tidal-hifi?

**Comment by ThatOneCalculator** [comment]
Nvm: https://github.com/uwu/neptune/pull/25

**Comment by QuarTheDev** [comment]
Hey @ThatOneCalculator, if you'd like, you can add a flatpak section to your PR and replace the `cd /opt/tidal-hifi/resources` line with `cd "$(flatpak info --show-location com.mastermindzh.tidal-hifi)/files/lib/tidal-hifi/resources/"`. This will pull the correct location of the Flatpak, and then CD into the resources directory. The rest of the process remains the same. Tested on Fedora Workstation 40

![image](https://github.com/user-attachments/assets/fe3fb4ad-d1ef-4f5c-ab49-d873a7aadd27)

**Comment by ThatOneCalculator** [comment]
I don't think they're going to merge my PR anyway, but: https://github.com/uwu/neptune/commit/a91ff4d21fcc10e526f9570e8e40c55a58d78e36

**Comment by xaiyadev** [comment]
Neptune is officialy dead...
Is there a possibility that there could be native support now (for custom plugins)?
