### ISSUE TITLE
How can I disable the taskbar icon?

### ISSUE THREAD

**Issue by haydenjames** [Mastermindzh/tidal-hifi#27]
I'm using i3 and the status bar icon is bigger than the other icons. So I would like to just disable the icon. Esp since Tidi-hifi has its own workspace, so the taskbar icon isn't needed.

Thanks

**Comment by Mastermindzh** [comment]
What are you using? I'm using i3bar and it looks alright.

![image](https://user-images.githubusercontent.com/4190290/95168907-4fd71180-07b2-11eb-83bc-4c76f6f5fe26.png)

Either way, I could add an option to disable it outright.

**Comment by haydenjames** [comment]
Using default, bar that comes with manjaro i3. That would be awesome. I keep it in my scratchpad so really don't need it as in using keyboard anyway. 

Also when I select the option to disable menu bar, it does nothing. When I close and reopen settings the menu bar option is always enabled no matter how I try to toggle to disable. 

Thanks again

**Comment by Mastermindzh** [comment]
The latest version seems to have a few issues with the settings screen. I can't enable the menubar anymore either. It does still read my config correctly though (it has menuBar: false).
I'll look into this as soon as I have the time.

![image](https://user-images.githubusercontent.com/4190290/95186728-96386a80-07ca-11eb-8bc9-bf2e88f6c389.png)

**Comment by Mastermindzh** [comment]
I slightly overran my break time but I managed to work out some code...
I fixed the bug and added the toggle you desired.

Will update tonight.
![image](https://user-images.githubusercontent.com/4190290/95193918-dbfa3080-07d4-11eb-9d9c-57d341a61a68.png)

**Comment by haydenjames** [comment]
Awesome! Will find the donate link and buy you a coffee.

Hopefully the settings are obeyed in new update.

Thanks again

**Comment by Mastermindzh** [comment]
@haydenjames ,

I will hopefully release today. Didn't have time yesterday, my bad.

Donating is awesome but I don't accept donations to myself. If you **really** want to donate something anyway I suggest you donate to a charity I support: https://secure.kwf.nl/donation

**Comment by Mastermindzh** [comment]
I just released it and ran the update on my system. Hiding the icon works beautifully :)

**Comment by haydenjames** [comment]
Thanks! Works great indeed. Will donate.
