### ISSUE TITLE
polybar configuration working with flatpak?

### ISSUE THREAD

**Issue by sascha-wi** [Mastermindzh/tidal-hifi#270]
Hello I tried to copy paste your polybar config into my but sadly it doesn't give me what I was hoping for. When I run the tidal-cli script manually it throws:
```
bash .config/polybar/scripts/tidal-cli.sh                                                                               ✘ 2 15:28:58
tidal-cli doesn't know this command
```
Also the module on my bar just shows the blinking path of the script. Any idea what I am doing wrong?

**Comment by Mastermindzh** [comment]
To properly test whether it works do the following:

1. Start TIDAL Hi-Fi
2. Play a song
3. Go to the homepage in TIDAL Hi-Fi
4. Check whether the API is enabled and returns a correct value (visit: [http://localhost:47836/current](http://localhost:47836/current))
5. Check whether your polybar refreshes the block at a given interval (mine is 1, see pic)
6. If 5 still doesn't work... create a module that updates every second with a custom script and see if that DOES update


![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/b9eaaf06-4b36-4403-951c-4010de5a6c95)
