### ISSUE TITLE
Tidal-Hifi closing upon opening

### ISSUE THREAD

**Issue by Foffy-01** [Mastermindzh/tidal-hifi#280]
# Issue
## Cause
The issue started because I terminated the application by mistake, upon clicking a system (Manjaro KDE) pop-up, asking if I wanted the application to run in background, which force-closed it. After that, the application started closing automatically in a few seconds after being opened. I reinstalled the app multiple times but it doesn't help. 
## Platform
The app was installed using Flatpak.
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.9-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 7,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
## System Log
`27/08/23 18:31	plasmashell	[2:0827/183150.504167:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
27/08/23 18:31	plasmashell	[2:0827/183150.504399:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
27/08/23 18:31	plasmashell	[2:0827/183150.505091:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
27/08/23 18:31	plasmashell	[2:0827/183150.506583:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
27/08/23 18:31	plasmashell	[2:0827/183150.506870:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
27/08/23 18:31	pipewire	mod.client-node: 0x55daa88ed630: unknown peer 0x55daa890e7e0 fd:83
27/08/23 18:31	pipewire	mod.client-node: 0x55daa891ba40: unknown peer 0x55daa89160e0 fd:46
27/08/23 18:31	kded5	Service  ":1.312" unregistered
27/08/23 18:31	systemd	app-flatpak-com.mastermindzh.tidal\x2dhifi-9539.scope: Consumed 5.300s CPU time.`
## Additional Context
Additionally I installed the application using the pacman release, this seems to be working.

**Comment by Mastermindzh** [comment]
Hey,

Thanks for the report!
There is no helpful information in the system log, unfortunately.

My best bet would be an issue with the "state" of the chromium instance underneath TIDAL Hi-Fi.
I would remove "~/.config/tidal-hifi" to remove all state (your config/settings file is in there, might want to backup)

Unsure whether the FlatPak version stores its info somewhere else.

@Mar0xy, do you have a clue on the flatpak stuff :) ?

**Comment by Mar0xy** [comment]
Flatpak should store the configs in `~/.var/app/$app_id/$xdg_dir` so for tidal-hifi it would be `~/.var/app/com.mastermindzh.tidal-hifi/config`

**Comment by Foffy-01** [comment]
> Hey,
> 
> Thanks for the report! There is no helpful information in the system log, unfortunately.
> 
> My best bet would be an issue with the "state" of the chromium instance underneath TIDAL Hi-Fi. I would remove "~/.config/tidal-hifi" to remove all state (your config/settings file is in there, might want to backup)
> 
> Unsure whether the FlatPak version stores its info somewhere else.
> 
> @Mar0xy, do you have a clue on the flatpak stuff :) ?

Thanks for the quick response! I deleted the ~/.var/app/com.mastermindzh.tidal-hifi/config/ folder and reinstalled using flatpak, unfortunately the issue persists. I switched to the pacman release, which works better, but if you want to fix this issue I will continue to give you feedback, thanks!

**Comment by Foffy-01** [comment]
As additional information I can try to make a list of steps that lead to the issue:

1. Fresh install of Manjaro (KDE) minimal
2. Install Pamac Flatpak plugin
3. Install Tidal-Hifi using flatpak 
4. Open Tidal-Hifi
5. System notifies that Tidal-Hifi is running in the background, click on force-quit (or something like that)

**Comment by skryvel** [comment]
I guess I have the same symptoms. App installed manually via `flatpak --user`. Ran fine for half an hour until I restarted it. Now closes after opening. Uninstall/reinstall w/ `rm -rf .var/app....` in the middle did not work. Pipewire restart did not help. Reboot did not work. Went through all files modified in my home dir since I installed the app and removed a bunch of caches and nothing.

Logs of potential interest:
```
LaunchProcess: failed to execvp:
```

```
[37:0829/173508.525814:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

```
51344 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 44<UNIX-STREAM:[932708]>
51344 connect(44<UNIX-STREAM:[932708]>, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X1"}, 20) = 0
^ with a bunch of recvmsg failing afterwards
```

```
C3: -> org.freedesktop.DBus fake GetNameOwner for org.mpris.MediaPlayer2.tidal-hifi
B4: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C3
```

```
[2:0829/184316.646589:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

**Comment by reyquito** [comment]
I'm also having this issue with the flatpak version, running on Ubuntu 23:04. Snap and deb work fine.

**Comment by Mastermindzh** [comment]
Thank you guys for all the info.
I'm not well versed in the flatpak side of things unfortunately but I'll try my best with it next week.

**Comment by gitgrift** [comment]
Just chiming in to say I have had the same problem with this flatpak in fedora 38.

If I launch the app by clicking on its icon in gnome-shell, it will exit after ~5 seconds. However, if I open a terminal and `flatpak run com.mastermindzh.tidal-hifi` then everything works fine. 🤷

**Comment by skryvel** [comment]
Just noticed running `--devel --command=sh` _also_ gets a `SIGKILL` after a few seconds. This may mean this has nothing to do with the actual app.

**Comment by skryvel** [comment]
It's [this](https://bugs.kde.org/show_bug.cgi?id=473881) KDE issue. Downloaded `Flatseal` and unset `Background` permission and it already worked. I guess when I clicked the KDE popup for background activity it set the permission to false. Left it enabled now and it's all fine.
