### ISSUE TITLE
Toggle for "time left" on Discord RPC in settings

### ISSUE THREAD

**Issue by Valoriks** [Mastermindzh/tidal-hifi#282]
When I play music on Tidal the Discord RPC often shows how much of the song is left incorrectly. Since in the newest update there are customizations to it, it would be nice to add a toggle to remove it completely.

**Comment by Mastermindzh** [comment]
I'll look into both fixing the issue with time (if possible) and add the setting regardless of the result :)

Thank you!

**Comment by Mastermindzh** [comment]
I fixed the time issue (it now appears correctly all the time) but added the switch as well:

https://github.com/Mastermindzh/tidal-hifi/assets/4190290/a5d34b8d-f913-4d2c-ab71-6be290aeffff
