### ISSUE TITLE
Tidal Hi-Fi (code S6007)

### ISSUE THREAD

**Issue by asior1985** [Mastermindzh/tidal-hifi#283]
I'll get this:  There was an unexpected error. Try again later. (S6007)
![Screenshot](https://github.com/Mastermindzh/tidal-hifi/assets/112169489/6e7cc57f-1bc0-4cee-b675-3665717e4e27)

Any solutions ?

**Comment by Mastermindzh** [comment]
We no longer support Windows since support for DRM broke on Windows, see the known issues:

https://github.com/mastermindzh/tidal-hifi/#drm-not-working-on-windows
