### ISSUE TITLE
album art not showing in notification panel

### ISSUE THREAD

**Issue by nrbeaton** [Mastermindzh/tidal-hifi#284]
OS: Arch Linux
DE: Gnome 44.4 on X11
Tidal HiFi version: from the AUR

The album art is not showing in the GNOME notification panel thing. Pretty sure it was working maybe a few weeks ago.

I have enabled MPRIS in the settings. 

If I enable "Disable hardware built-in media keys" then nothing shows up in the notification panel at all, and the keyboard play/pause buttons don't work.

The other settings seem to have no effect.

(This is all with notifications disabled -- if I enable them the notifications (not the playback controls) do show up with art. But I don't want those notifications, I just want the playback controls.)

**Comment by Mastermindzh** [comment]
Haven't been able to reproduce this yet. I can try more next week.

Seems like the settings are working as intended :)

**Comment by nrbeaton** [comment]
Just checked KDE (Wayland) -- same problem, with both the AUR and Flatpak versions. Something is wrong with MPRIS? (I don't really know what MPRIS is...)

**Comment by TheEdgeOfRage** [comment]
@nrbeaton [MPRIS](https://wiki.archlinux.org/title/MPRIS) is a standardized way for different processes to exchange information about currently playing media. For example, your desktop env (KDE) will accept keyboard shortcuts to play/pause, skip tracks, etc. but it has to know to which process (i.e. player) to send that command to. MPRIS provides a way for players to register themselves on a global level as a media player and other processes can then interact with it

**Comment by nrbeaton** [comment]
@TheEdgeOfRage thanks :-)

I'm guessing this issue is the same as https://github.com/Mastermindzh/tidal-hifi/issues/285.

**Comment by TheEdgeOfRage** [comment]
Likely, yes

**Comment by Mastermindzh** [comment]
Thanks for the report @nrbeaton , let's follow along in #285 since it has some additional debugging info available already.
