### ISSUE TITLE
Custom MPRIS interface disappeared

### ISSUE THREAD

**Issue by TheEdgeOfRage** [Mastermindzh/tidal-hifi#285]
I used to be able to control tidal-hifi using the custom MPRIS interface (settings>integrations>MPRIS) and disabled the hardwarde built-in media keys. Since yesterday it stopped working tho, and `playerctl -l` shows "No players found"

There was an update from Tidal itself recently, so it could either be that, or the 5.7.0 release from two days ago.

OS: ArchLinux (tidal-hifi-bin AUR package)
Version: 5.7.0

Let me know if there's any additional information I can provide to help :)

**Comment by Mastermindzh** [comment]
Can you try using an older version like 5.6 or 5.5 ?

And if you'd be able to share DE details that would be lovely too <3

Thanks!

**Comment by AnttiRae** [comment]
Hello, I'm experiencing the same problem. After updating Tidal-hifi (to 5.7.0) the MPRIS setting turned off by itself and I no longer see the interface in my DE  to skip songs etc. Also trying to turn on the settings>integrations>MPRIS setting and restarting results in the setting getting reset to off position. 
My OS is Fedora 38 with the Gnome desktop. I'm using the Flatpak version.
I also tried running the flatpak from the terminal and some errors that might be related:

```
❯ flatpak run com.mastermindzh.tidal-hifi
Gtk-Message: 07:37:57.281: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:37:57.281: Failed to load module "pk-gtk-module"
Gtk-Message: 07:37:57.282: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:37:57.282: Failed to load module "pk-gtk-module"
LaunchProcess: failed to execvp:
xdg-settings
[2:0901/073757.370212:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0901/073757.370315:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0901/073757.370670:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0901/073757.371105:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0901/073757.371156:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Refreshing settings failed. 
[38:0901/073801.396591:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

Thanks for this awesome software and let me know if I can provide more info!

**Comment by TheEdgeOfRage** [comment]
@Mastermindzh Yep, after reverting to 5.6, it works again. I'm running i3 using xinit. It is pretty barebones, so that could be part of it.

I also tried the flatpak variant of 5.7 and it doesn't work either

**Comment by Mastermindzh** [comment]
Thanks. 

I'm gone for the day but I'll check this weekend.
Verification helps a lot.

**Comment by Mastermindzh** [comment]
Weekend didn't work, sorry. I'll get on it as soon as I realistically can :)

**Comment by thanasistrisp** [comment]
Me too I experience this. If the setting "Disable hardware built-in media keys", it appears as chromium instance. Mpris tidal-hifi player dissapeared. Also related to #284

**Comment by Mastermindzh** [comment]
So I checked yesterday (don't have much time this week, sorry) and confirmed:

- 5.6.0 seems to work fine, even if I revert the code (so something definitely broke haha!)
- code related to mpris wasn't **directly** updated
- no package updates happened to mpris and we are on the very latest version
- I have confirmed that the **setup** code of mpris throws an error (but it leaves the error object empty)
- The settings are applied correctly and mpris setup **is** executed (but again, fails)

Will have to debug further to evaluate exactly what is going wrong.

**Comment by Mastermindzh** [comment]
I was wrong. The name-change made this fail.
Mpris names/identities don't like capitals, spaces, etc.

Will revert mpris back to tidal-hifi and release a patch.

**Comment by Mastermindzh** [comment]
5.7.1 contains the fix :)
