### ISSUE TITLE
Since last patch the window is unresponsive after minimize

### ISSUE THREAD

**Issue by DSDV** [Mastermindzh/tidal-hifi#289]
Hi (: 
at first thank you so much for the app <3 
Since this patch https://github.com/Mastermindzh/tidal-hifi/issues/288#issuecomment-1718079365 the tidal app works again (: 
But if i minimize it into the dock (i am on fedora 38 /gnome) and get it back up i cant press anything anymore. Only way to get back control is close the app via dock right click > quit and reopen it again.

with kind regards

**Comment by DSDV** [comment]
That is a thing i have with every flat pack and would assume is not special tidal related

**Comment by MiMillieuh** [comment]
> That is a thing i have with every flat pack and would assume is not special tidal related

I only have this on TIDAL on my side, so maybe there is something more... it wasn't the case before

**Comment by Mar0xy** [comment]
>  would assume is not special tidal related 

This is indeed the case as the cursor work separately in wayland and x11 I also simply get this issue on normal apps but that is when the cursor's don't initialize properly in the app.

**Comment by DSDV** [comment]
> > That is a thing i have with every flat pack and would assume is not special tidal related
> 
> I only have this on TIDAL on my side, so maybe there is something more... it wasn't the case before
https://github.com/flatpak/flatpak/issues/709#issuecomment-1670708180 (: 

But if the dev reads this i would liek top point out that i still have an unresponsive window after minimizing tidal :/

**Comment by Mastermindzh** [comment]
Can you reproduce it on the other versions as well?
I haven't been able to reproduce it but I don't use flatpaks :)

**Comment by DSDV** [comment]
i only use the Flatpak version sorry :( 

but i just tested again. the whole window gets unresponsive even the minimize maximize and close button. 
i have the problem since the app broke so maybe it has sth to do with https://github.com/Mastermindzh/tidal-hifi/issues/288 ?

**Comment by MiMillieuh** [comment]
> i only use the Flatpak version sorry :( 
> 
> but i just tested again. the whole window gets unresponsive even the minimize maximize and close button. 
> i have the problem since the app broke so maybe it has sth to do with https://github.com/Mastermindzh/tidal-hifi/issues/288 ?

Could you try to disable Wayland in flatseal ? 

I noticed that wayland causes a lot of issues.

But even tho I use Ublue (fedora 38 silverblue basically) with gnome I don't have that issue in both configurations.

**Comment by DSDV** [comment]
That helped. 

![image](https://github.com/Mastermindzh/tidal-hifi/assets/5504857/87d9c141-70a1-40fc-b70a-15179f6dc68c)

via default both x11 and Wayland where set to true. 
i don't know what fallback x11 is. 

but with disabled Wayland it works. 
Tho x11 is a legacy bug hell :( i would love to see full Wayland support in the future since i think fedora will drop x11 soon.

**Comment by MiMillieuh** [comment]
> That helped.
> 
> ![image](https://user-images.githubusercontent.com/5504857/268623509-87d9c141-70a1-40fc-b70a-15179f6dc68c.png)
> 
> via default both x11 and Wayland where set to true. i don't know what fallback x11 is.
> 
> but with disabled Wayland it works. Tho x11 is a legacy bug hell :( i would love to see full Wayland support in the future since i think fedora will drop x11 soon.

Well I don't know what has happened but since the MPRISM bug fix wayland is kinda buggy and has a lot of issues... maybe there is something to do with flatpak SDKs since it doesn't seem to be exclusive to TIDAL (according to some people) however for me it's exclusive to TIDAL...

**Comment by DSDV** [comment]
hm .. i try to use flatpak as much as possible and aside from theming (which indeed is a little pita) all works great so far.

Except the current tidal issue. But the workaround brought music back into my life <3

**Comment by MiMillieuh** [comment]
> hm .. i try to use flatpak as much as possible and aside from theming (which indeed is a little pita) all works great so far.
> 
> Except the current tidal issue. But the workaround brought music back into my life <3

Yeah flatpak at least don't alter all the system... but theming works fine tho if you follow the good guide.

I always use this guide when I install a distro if you want to try it out : 

https://itsfoss.com/flatpak-app-apply-theme/

**Comment by DSDV** [comment]
I did that with flatseal (both paths and env variables) strange thing is it works for most apps but for example flatseal stays in the bright theme no matter what. 
Even tho it shows GTK_THEME=adw-gtk3-dark as environment variable when i click on it inside flatseal as application settings or global settings. 

to be honest i gave up on it since it worked on most of my applications ^^its just linux for me :P
