### ISSUE TITLE
Sound output device

### ISSUE THREAD

**Issue by mreho** [Mastermindzh/tidal-hifi#29]
`tidal-hifi` is outputing sound on the first device available from PulseAudio device list instead of using the default audio output device. Each time I need to switch default to the the first device, then to my selected output device, in order to listen music.

It would be great to let the user choose on which device he wants to play the music :smiley:

**Comment by Mastermindzh** [comment]
I am not able to reproduce this on any of my machines. Did you set your default device and fallback device to the correct one?

It always selects the default audio device for me. As seen in this picture I switched to the HDMI output (of which I was unaware it even had a speaker, but it does..)

![tidal-fallback](https://user-images.githubusercontent.com/4190290/96694661-062d2000-1389-11eb-86a3-56d2dcb190b7.png)
![tidal-1](https://user-images.githubusercontent.com/4190290/96694774-26f57580-1389-11eb-96b8-6304fb4839e9.png)

Allowing one to overwrite the speaker output would require system-level integration, not something I am a fan of if it can be avoided. (There is no real reason for tidal-hifi to KNOW which outputs are available)
