### ISSUE TITLE
tidal-hifi I can't login

### ISSUE THREAD

**Issue by lu5jzz** [Mastermindzh/tidal-hifi#290]
I can´t login in TIDAL HI-FI after last upgrade. I'm user off UBUNTU 22.04.3  with wayland.

**Comment by Mastermindzh** [comment]
Try clearing your caches, this happens from time to time 😄

**Comment by Mastermindzh** [comment]
Are you on the latest version of the app?
You can pass `--no-sandbox` to the tidal-hifi command to bypass any content restrictions due to sandboxing (which can result in a white screen)
