### ISSUE TITLE
Launching the program.

### ISSUE THREAD

**Issue by lis1991** [Mastermindzh/tidal-hifi#291]
There was a problem with running the program. 
It gives the error "Your browser does not support Tidal".

I am sure that this can be solved with the help of extension functions:
https://github.com/sorz/accept-language-per-site

With his help, everything worked in the firefox browser.

![Снимок экрана от 2023-09-14 21-39-59](https://github.com/Mastermindzh/tidal-hifi/assets/127238619/aed23cfe-dc66-4e82-85bf-b49a52e4f83c)

**Comment by Mastermindzh** [comment]
Tidal has this from time to time with people outside of the major areas (e.g. US).
This project makes a point of not modifying or using the existing TIDAL infrastructure though so we won't be implementing request modification, sorry 😄
