### ISSUE TITLE
Only plays back "High" quality audio even when settings are set to "Max" 

### ISSUE THREAD

**Issue by codewizkid** [Mastermindzh/tidal-hifi#292]
I know that my DAC can playback higher quality audio, I've been using qobuz for a while now, but for some reason non of the songs I play will have higher quality than "High". And I've tested songs that I know have higher quality because I've tested this on windows and it plays back higher quality just fine...

I did find another song that does playback in "FLAC" quality, but the sample rate is still only 48kHz. And again I know my DAC on Linux is capable of playing back up to 192kHz...

![2023-09-16-092311_1888x1022_scrot](https://github.com/Mastermindzh/tidal-hifi/assets/59891670/e0f2dc45-a5c9-4012-8b65-61735f74a80c)

**Comment by Mastermindzh** [comment]
See: https://github.com/Mastermindzh/tidal-hifi/issues/266 for help on setting up your audio solution.

As for HIGH vs MAX, when you set your streaming quality to "Max" TIDAL will automatically select the highest quality version available. This might still be the "high" version.

With everything set to max...
If I play the following song: https://tidal.com/browse/track/301708029

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/30cfe423-189c-4bdf-9179-d089e1e1df45)

Whereas, if I play:  https://tidal.com/browse/track/309054755

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/5407d2da-f278-473d-84f5-53740fad43e6)


Unfortunately, my DAC's 192K output will limit the lossless track.

Feel free to contribute in the other topic to get your setup figured out 😄 !
