### ISSUE TITLE
No Tray icon is shown on KDE plasma

### ISSUE THREAD

**Issue by muznyo** [Mastermindzh/tidal-hifi#297]
When i open the app, no tray icon is shown, so if i close the window, it's running in background and i have to kill the process with system monitor. (yes, i have tray icon option turned on)

When i used Fedora with GNOME, tray icon was showing. But since i switched to Nobara linux with KDE, it doesnt show. Other apps show tray icons (Mullvad, steam, etc.), but tidal doesn't.

I use a flatpak version.

**Comment by Mastermindzh** [comment]
Haven't been able to reproduce on the latest KDE.
Did you customize any of your settings in the tray icon viewer?

**Comment by muznyo** [comment]
No, I didn't.

**Comment by Kivarnis** [comment]
Can confirm on my fresh install, doesn't show up at all, this is under Fedora 38 and Wayland.

**Comment by Evpok** [comment]
Can also confirm on Manjaro, plasma 5.27.10 and Wayland

**Comment by SpyPower** [comment]
Can confirm on Pop_OS 22.04, wayland.

**Comment by Mastermindzh** [comment]
I can reproduce it on Fedora KDE and Arch (which I'm just gonna say is the same as Manjaro, don't shoot me for it 😆).

Will investigate.

**Comment by poltpolt** [comment]
I can confirm on Opensuse Tumbleweed with latest release of plasma 5 available.

Maybe it is related with Wayland - as I run wayland?

**Comment by thalskarth** [comment]
> I run Wayland too and I have the same problem. Even if it might not be ideal, I've enabled the session D-Bus in the Flatpak permissions as a workaround and I got the icon back.
> 
> ![image](https://private-user-images.githubusercontent.com/43271778/316977622-da6a6296-170e-454a-9e29-0688b4d7bf12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwMDEsIm5iZiI6MTcxMzAyMDcwMSwicGF0aCI6Ii80MzI3MTc3OC8zMTY5Nzc2MjItZGE2YTYyOTYtMTcwZS00NTRhLTllMjktMDY4OGI0ZDdiZjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Yjk3MDU2OTY2NmNhMDExZTZiNzcwNDYwM2NkNGU5ZDA2ZDBiYzk4ZTk4OWRjYmY3NjBmMmZhZDBkY2QzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4XZct7NA7mHIStar-izbyOEvtdqT6cZzV6doearSiHA)

I was having the same issue on Fedora 39 with GNOME and this solve it

**Comment by Mastermindzh** [comment]
On Plasma 6 it works again though the flatpak is having issues that we're looking into, see: https://github.com/Mastermindzh/tidal-hifi/issues/406
