### ISSUE TITLE
Master Quality

### ISSUE THREAD

**Issue by sandikata** [Mastermindzh/tidal-hifi#30]
Master quality not avalible, like described in description. 
Linux Ununtu 20.10 deb package.

**Comment by Mastermindzh** [comment]
I specifically avoided describing master quality as that is locked out by Tidal on anything but their whitelisted applications.

Unfortunately, there is nothing I can do about that.

Hifi still works though!

**Comment by criscola** [comment]
@Mastermindzh hey have you seen this article? https://medium.com/@lazvsantos/how-to-use-tidal-on-linux-f2e50e063f57
