### ISSUE TITLE
[FR] add mpris support

### ISSUE THREAD

**Issue by farfromrefug** [Mastermindzh/tidal-hifi#300]
Would be nice to add support for MPRIS on linux. https://wiki.archlinux.org/title/MPRIS

I found an electron project which did it https://github.com/twolfson/google-music-electron/blob/eec99851ef5119a947a50a5a0b99e51705e765c6/lib/mpris.js#L12
Hope you like the idea!

**Comment by farfromrefug** [comment]
My bad i just saw it is already working! Thanks a lot!

**Comment by Mastermindzh** [comment]
No problem!
Enjoy :)
