### ISSUE TITLE
Wrong dock icon in Snap installation on Ubuntu gnome

### ISSUE THREAD

**Issue by mcclure** [Mastermindzh/tidal-hifi#302]
Have a pretty fresh Ubuntu 23.10 install. I am using mostly-stock\* gnome. I installed 5.7.1 via the snap with the provided instructions. Wasn't sure how to boot it so I ran "tidal-hifi" and then did right-click-"pin to dock". The icon is a weird gear thing

![image](https://github.com/Mastermindzh/tidal-hifi/assets/277318/48d75d88-003f-41be-a401-320577c3e3f7)

Is this surprising? Not sure if related to #297

Anyway thanks for the app

\* Screenshot taken with dash-to-dock which pretty much just moves the dock to the bottom. No difference if I switch back to stock Ubuntu dock tho

**Comment by Mastermindzh** [comment]
Surprising... no...
Annoying... yes...
Wrong... yes...

We've been having issues with icons for a while now to be honest, can't quite seem to get them right on all platforms at the same time.
