### ISSUE TITLE
free subscribe

### ISSUE THREAD

**Issue by senolfndk** [Mastermindzh/tidal-hifi#305]
😒
![Ekran görüntüsü 2023-10-29 120608](https://github.com/Mastermindzh/tidal-hifi/assets/52818836/e1cd7ca1-f177-43da-81d8-fee191db10dc)

**Comment by Mastermindzh** [comment]
TIDAL isn't free for everyone. As far as I know the free subscriptions are limited to the US.

Nothing we can do about it, sorry 😁

**Comment by senolfndk** [comment]
> TIDAL herkes için ücretsiz değil. Bildiğim kadarıyla ücretsiz abonelikler ABD ile sınırlı.
> 
> Bu konuda yapabileceğimiz bir şey yok, üzgünüm 😁

No problem
![Ekran görüntüsü 2023-10-29 130726](https://github.com/Mastermindzh/tidal-hifi/assets/52818836/5acd3a31-5395-4a82-b755-3c30d9781636)
