### ISSUE TITLE
Freezes After a Few Hours

### ISSUE THREAD

**Issue by duncanam** [Mastermindzh/tidal-hifi#306]
I'm on a CentOS Stream 9 machine +Gnome, and after a couple of hours I hear the music stop and the whole interface is frozen. When I disable GPU acceleration, I at least maintain the graphics inside the window (frozen and unresponsive) but when GPU accel is on, it also replaces all content within the window with blank white. 

Restarting the application fixes everything. I'm going to continue to monitor and see if I can gather any more information- I'll launch from terminal to see if there's any feedback there today.

**Comment by duncanam** [comment]
Okay, so my terminal is giving me after crash:

ERROR:shared_image_manager.cc(99) SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.

**Comment by Mastermindzh** [comment]
Hey,

That just seems to point to something internally in chromium :/
Not sure how to reproduce at the moment :)

**Comment by Mastermindzh** [comment]
Had TIDAL playing all day yesterday, haven't seen the issue.
Which version are you using?

**Comment by duncanam** [comment]
> Hey,
> 
> That just seems to point to something internally in chromium :/
> Not sure how to reproduce at the moment :)

Well, i tried again and did not get that feedback message I posted earlier, but still crashing after a few hours. 

> What version are you using?

I am using the latest release off of git.

**Comment by lumpiluk** [comment]
I've had the same issue for a long time on two systems; one with Nvidia graphics card, the other a laptop with hybrid Intel and Nvidia graphics where I don't use the graphics card for Tidal.

**Comment by nobrayner** [comment]
I have seen similar, but always attributed it to loss of internet.

I turn off the wifi at night, and without fail it will be frozen/whited out the next morning after turning the wifi back on again, and waking my PC.
