### ISSUE TITLE
Cannot remove items from "My Collection"

### ISSUE THREAD

**Issue by seanlowe** [Mastermindzh/tidal-hifi#307]
**Problem:** Cannot remove items from "My Collection"

**Expected Result:** User is able to click the heart icon or use the right-click menu to remove an item from "My Collection"

**Actual Result:** Clicking the heart icon or using the right-click menu removes the item from the _list_ but does not actually persist the change. Closing and re-opening the app shows the item still in the list.

**Description:** Running into an issue where I cannot click the heart icon or use the right-click menu to remove a track from "My Collection". This works on the actual website but isn't working on the app. My usual "flow", if you will, is that I go to a radio, will save songs to my collection, and then add them to a short-list playlist of songs that I keep on rotate. After they are added to the short-list I remove them from the collection so that I only see the newest saved songs in there.

Here's some info from `screenfetch`, not sure if any of this is helpful.
OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 6.2.0-36-generic
Shell: bash 5.1.16
DE: GNOME 41.7
WM: Mutter
CPU: 11th Gen Intel Core i7-1185G7 @ 8x 4.8GHz [58.0°C]
GPU: Iris Xe Graphics
RAM: 8584MiB / 31812MiB

Installed via Flathub / flatpak if that's helpful as well. I also made sure it was fully up to date and confirmed this issue still exists.

[Screencast from 11-06-2023 12:28:44 PM.webm](https://github.com/Mastermindzh/tidal-hifi/assets/35589586/16dd3ad9-cea8-4e29-ba22-c64cdf04a786)

**Comment by Mastermindzh** [comment]
Hey,

Unfortunately, I cannot reproduce this issue. 
Does it still occur? Might've been something with internet/TIDAL itself.

My try at reproducing:

https://github.com/Mastermindzh/tidal-hifi/assets/4190290/3497168f-d80f-4ad2-aa7e-19c46433c7c7

**Comment by seanlowe** [comment]
Hi, thanks for taking the time to look into it. It's still happening on my end. If there's anything I can do to test or debug for you, let me know. I'm willing to help.

**Comment by Mastermindzh** [comment]
Could you try another install method?
I'll try it in flatpak this weekend (I tested the AUR version) since I don't have flatpak installed by default 😄
