### ISSUE TITLE
Dont install optional Dependencies Then you can use mpris-service

### ISSUE THREAD

**Issue by JarekToro** [Mastermindzh/tidal-hifi#31]
`npm install --no-optional`

Fortunately the abstract-socket is listed as optional in the `next-dbus` lib.

In my project. It seems to be working fine without it.

**Comment by Mastermindzh** [comment]
Thanks! I fixed the root cause as well though:

https://github.com/castlabs/electron-releases/issues/70

It's in the new 1.3.0 release if you wanted to make use of mpris-services. Don't forget to enable it in the settings!
