### ISSUE TITLE
WEB API is broken

### ISSUE THREAD

**Issue by Kajzer1** [Mastermindzh/tidal-hifi#310]
After entering IP address and port of the API in the browser, Application crashes

**Comment by Mastermindzh** [comment]
Hey, 

I'm unable to recreate this. Do you have more info?

Which version?
Which package?
Which OS?
Any oddities in your OS?

**Comment by Kajzer1** [comment]
Version 5.7.0
Package tidal-hifi-bin (from AUR)
Arch Linux
I don't think so
Here is screencapture showing what's happening

https://github.com/Mastermindzh/tidal-hifi/assets/28542973/bc2139ab-f3b7-4c4b-850f-a3392e961cc6

**Comment by Mastermindzh** [comment]
Thanks for the extra info.
I recreated your setup and for me, it simply works (note it shows the wrong version in the about.. we fixed that bug but didn't publish a new version 😉 )


https://github.com/Mastermindzh/tidal-hifi/assets/4190290/a48c251c-e553-4fa9-8e11-97340a8a6de1

Honestly, I can't really help you any further without a reproducible result.
I have no clue what it could be, sorry.
