### ISSUE TITLE
In CHROME web browser, too we can listen TIDAL in  MAX quality sound. 

### ISSUE THREAD

**Issue by lu5jzz** [Mastermindzh/tidal-hifi#312]
In ubuntu 22.04 too we can listen TIDAL in MAX quality sound. It has only one problem, and that is that the function of playing a single song, over and over again, does not work. When he gets to the end of the song, he gets stuck there.

**Comment by Mastermindzh** [comment]
Hey,

This project is only the Linux app version, not the official TIDAL client/site.

I don't work at TIDAL and as such can't look into the issue for you.
You can look at their contact/help pages for support:

https://tidal.com/help
