### ISSUE TITLE
Tidal mistakenly saying to upgrade SteamDeck

### ISSUE THREAD

**Issue by FrizzyCanadian** [Mastermindzh/tidal-hifi#321]
So I opened up Tidal on my Steam Deck, tried to play some music and realized that i can only play "low" quality audio. Any time I click on the audio quality settings it tells me to upgrade. So I checked my subscription and it's on the highest one. I checked tidal on all my other devices and I still have access to High and Max. I've updated the app, I've uninstalled it and logged out. I also restarted and updated my device and then I also tried the web player but I only have access to High on there.

**Comment by Mastermindzh** [comment]
Hey,

Unfortunately, we have no control over any of that.
You can still try to delete the cache files (`~/.config/tidal-hifi`) and restart though.

**Comment by FrizzyCanadian** [comment]
> Hey,
> 
> Unfortunately, we have no control over any of that. You can still try to delete the cache files (`~/.config/tidal-hifi`) and restart though.

Thank you, this worked!! I struggled to find the folder at first since it was hidden.
