### ISSUE TITLE
Please add hotkey or API for like/dislike (add/remove to  My Collection)

### ISSUE THREAD

**Issue by dionorgua** [Mastermindzh/tidal-hifi#323]
It would be cool to have hotkeys or web API calls to add/remove current song to My Collection (that `heart` icon)

Thanks!

**Comment by Mastermindzh** [comment]
Hey @dionorgua,

Would be a pretty simple addition and I can probably implement it later this week.
Is there any specific hotkey you had in mind?


Also, might as well make "block" available then as well so I'll work on that too.

**Comment by dionorgua** [comment]
Personally for me just API call would be enough :) Because I use custom shell script that sends actions to active player

**Comment by dionorgua** [comment]
Btw I've thinked more about this. 
Since it's global hotkey or API call, we should be able to get result somehow. For example if it's hotkey, then just notification like 'now playing'. Or just some HTTP status code if something was changed.

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/d8f75b75-ce7f-4523-9113-1e8afba7d537)

Included in the API now, all that's left now is creating an endpoint to set/unset it :)

**Comment by Mastermindzh** [comment]
Added to the API:

https://github.com/Mastermindzh/tidal-hifi/assets/4190290/91da658a-31f7-4ffe-8d77-1bfd6d3b34a0

**Comment by dionorgua** [comment]
Thanks a lot!.

**Comment by an0nfunc** [comment]
> Also, might as well make "block" available then as well so I'll work on that too.

Don't want to hijack this issue, but did you ever add blocking to the API? Would be really useful for daily mixes for example.

**Comment by Mastermindzh** [comment]
@an0nfunc, I never did, no.
I agree though, I too use daily mixes and sometimes it's just.... unbearable 😆 .

Mind making an issue? I'll have a look when I have time!

**Comment by an0nfunc** [comment]
Sure, thanks!
