### ISSUE TITLE
Update electron for better wayland support

### ISSUE THREAD

**Issue by andresilva** [Mastermindzh/tidal-hifi#325]
The latest electron versions (v27 or v28) have fixed several issues related to wayland support. tidal-hifi is using an old version of electron (v24) and frequently crashes on startup for no obvious reason, this is common among all electron apps that use older electron versions and as they updated these issues have disappeared. Currently I have reverted to using tidal-hifi in xwayland mode, but I believe updating electron would fix this problem.

**Comment by Mastermindzh** [comment]
Hey @andresilva,

I will be releasing a new version this coming weekend with a few small feature updates and some bugs.
I'll also look into including a newer version of Electron and circle back to you here.

Thanks!

**Comment by Mastermindzh** [comment]
Enjoy!

**Comment by andresilva** [comment]
Thanks!
