### ISSUE TITLE
Build for the raspberry pi

### ISSUE THREAD

**Issue by gebim** [Mastermindzh/tidal-hifi#329]
if possible (Widevine?). IMHO this would be highly appreciated, as for the pi are numerous high-quality DACs out and CPU-wise a pi4/5 is powerful enough...

**Comment by Mastermindzh** [comment]
Won't be available for the forseeable future, see: https://github.com/castlabs/electron-releases/issues/23

**Comment by Mastermindzh** [comment]
duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/329
