### ISSUE TITLE
Currently playing song is highlighted in white color so it's not obvious

### ISSUE THREAD

**Issue by new-penguin** [Mastermindzh/tidal-hifi#330]
OS: EndeavorOS w/ KDE and Wayland compositor
Version: Latest tidal-hifi-bin from AUR

Problem: Not a major issue but from a user accessibility perspective, it's an annoyance. When there's a long list of tracks, the currently playing song isn't so obvious in the list when focus is lost because it's highlighted in white, not the usual shade of green you see with the web player. It does have the white speaker icon but not the usual shade of green so it takes much more time to find the currently playing song in a list compared to the theme of the web player.

**Comment by Mastermindzh** [comment]
Hey,

Do you have any custom CSS loaded?
You can check in the settings menu under theming. Mine's configured like so:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/af3f70da-997c-4f33-8da6-0ebd2d81de47)

Which gives me the blue-ish focus color:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/18522e8b-04ad-4069-aa07-340e79ca0384)

**Comment by new-penguin** [comment]
No custom CSS, just the default theme. [This](https://i.ibb.co/rsbbrrH/Screenshot-20240107-071706.jpg) is what mine looks like. I've tried different KDE themes as well and it's still the same.

**Comment by Mastermindzh** [comment]
Yeah, that's really weird!

I reckon it's a cache thing again on TIDAL's side.
You can remove `~/.config/tidal-hifi` (make sure to backup the `config.json` from there if you want to keep your settings) and try again :)

**Comment by new-penguin** [comment]
That did it, thanks. Specifically I narrowed it down to the IndexedDB directory.

**Comment by Mastermindzh** [comment]
Great, enjoy the tunes!
