### ISSUE TITLE
Tidal magazine integration

### ISSUE THREAD

**Issue by gebim** [Mastermindzh/tidal-hifi#333]
Mastermindzh, 
first many thanks for this great SW. Not a bug but a feature request.

I like https://tidal.com/magazine/  as a good source of background information. The referred music there obviously links to https://listen.tidal.com/........
IMHO an implementation could be a tidal-hifi window of https://tidal.com/magazine/  and  https://listen.tidal.com/ links are opened in a second instance / or Tabs would be even more elegant.

**Comment by Mastermindzh** [comment]
Hey,

It's difficult to manage multiple windows with TIDAL since it only allows for 1 active player instance at a time on most (/all) plans.
I can include a button to open the magazine, though, so that's a good place to start I reckon.

I'll see what I can do.


> first many thanks for this great SW. Not a bug but a feature request.

No problem, glad you enjoy :)

**Comment by gebim** [comment]
yes, not easy to implement but  https://tidal.com/magazine/ does not require a login into tidal. Would it be possible to open a second window/tab "magazine window" without login?

**Comment by Mastermindzh** [comment]
@gebim, oh yeah, for sure. And we can also probably catch clicks on links and route that to the main window without actually requiring any multiple players or even a "custom protocol" (e.g. tidal:// which doesn't work atm)

I don't know when I have time for this but it's definitely something that's possible.

**Comment by Mastermindzh** [comment]
@gebim ,

Sorry, this took me waaaay too long to get to, it's available in the next release though...
You can find it in the menubar or navigate to it with `Ctrl + M`

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/ec5fcf08-9ae0-465f-936c-3b079f8e97dc)
