### ISSUE TITLE
Can't type in any program

### ISSUE THREAD

**Issue by svandragt** [Mastermindzh/tidal-hifi#334]
Thanks for making this app, I like it a lot!

Since last week, whenever I have TIDAL running, I cannot type in any program. the application seems to capture all keyboard input and I can't use any system shortcuts (such as alt tab), type any text in programs such as slack, or even lock my screen.

Let me know if I can help provide additional info to help fix this bug :) 

Linux PC (elementary OS 7.1 Horus x86_64 (Ubuntu 23.04 Jammy based)
Version 5.8.0

**Comment by Mastermindzh** [comment]
Hey,

Tidal version (I take that is the 5.8.0?) and install method would be good to know.
I can't reproduce it locally, I am able to alt-tab and whatever just fine.

Do you have any system settings that might enhance focus on a single window? (e.g. zen mode)
