### ISSUE TITLE
Frequent SSL Certificate Errors 

### ISSUE THREAD

**Issue by slpysiren** [Mastermindzh/tidal-hifi#335]
Running from the RPM on Nobara/Fedora 39. This error comes up at nearly every song change stating:

> The server has failed the authenticity check () 
> The host name did not match any of the valid hosts for this certificate

![image](https://github.com/Mastermindzh/tidal-hifi/assets/77393788/d187d289-5394-415f-9100-d1538d40f030)
![image](https://github.com/Mastermindzh/tidal-hifi/assets/77393788/0416255f-7c7d-4da4-a981-9431c1877a93)

So far I have only tried logging out and back in to tidal-hifi and restarting the system.

**Comment by Mastermindzh** [comment]
Hey,

All of the SSL is handled by TIDAL itself.
Are you sure you are keeping your local ssl database up to date?

**Comment by slpysiren** [comment]
Logging into TIDAL in a browser seemed to fix this. Thanks for your time.
