### ISSUE TITLE
Error S6007 using tidal desktop on linux.

### ISSUE THREAD

**Issue by schuleke** [Mastermindzh/tidal-hifi#336]
Since today I am not able to play any song longer than ~10 seconds using the tidal-hifi desktop app (electron) on linux.
I always get the following error:

`There was an unexpected error. Try again later. (S6007)`

Searching this repo I only found matching issues regarding windows OS.

tidal-hifi version: 5.8.0
OS: Ubuntu 22.04.3 LTS 64-bit
Gnome Desktop 42.9

Using the web browser ( brave 1.62.153 ) it works perfectly fine.

**Comment by Mastermindzh** [comment]
Hey, 

Please try removing the local cache (except config.json) which should be at `~/.config/tidal-hifi/`

**Comment by schuleke** [comment]
Thanks this solved the issue. I first tried removing only the pure cache-related folders but this didnt't solve the problem. Removing everything including cookies, storage, etc. fixed it.

**Comment by bhelm** [comment]
Had the same issue, this was enough for me to resolve it:
```
$ rm -rf .config/tidal-hifi/Cache/
$ rm -rf .config/tidal-hifi/Code\ Cache/
```
Thanks for the help!

**Comment by davidsansay** [comment]
I tried removing the cache folders, but it didn't fix the issue.
So, I just removed the folder .config/tidal-hifi

1. Close Tidal-Hifi
2. Remove the folder .config/tidal-hifi
```
rm -rf ~/.config/tidal-hifi
```
3. Start Tidal-Hifi & Login again.

Finally, it works.
