### ISSUE TITLE
Firefox slows down massively while tidal-hifi is playing music

### ISSUE THREAD

**Issue by TheEdgeOfRage** [Mastermindzh/tidal-hifi#337]
I know that this will likely just be a can't reproduce, but I guess I can try. I've installed tidal-hifi as a flatpak (tho I have tried the AUR version as well). When I play music, firefox often becomes almost unusably slow. there's a 100-200ms lag to any click/scroll, fps in firefox goes to <10 and just becomes a horrible mess. As soon as I pause the music (I don't have to close tidal-hifi), it works perfect again.

System:
Intel i5-12600K
RTX 3080
ArchLinux
X11 + proprietary nvidia drivers
plain i3 with no compositor

I'm happy to provide any logs that could help, just let me know.

**Comment by Mastermindzh** [comment]
@TheEdgeOfRage,

Very weird!
Two things you could try:

- hide the window (instead of minimize, minimize it to tray), see if that works
- Enable/disable GPU rasterization options in settings.

Other than that it's definitely a hard thing to reproduce.

**Comment by TheEdgeOfRage** [comment]
I've enabled minimize to tray and closed the window (since i3 doesn't have normal minimize). This seems to help actually, music plays and firefox behaves normally. GPU rasterization on/off doesn't change anything, it still slows down firefox while the window is open.

I guess minimizing the window is a decent enough workaround for now. I've just bought an AMD GPU and plan to move to wayland with it, so hopefully there won't be issues there.

**Comment by Mastermindzh** [comment]
Yeah, seems to be a compositing issue more than an app issue.
Glad the workaround is sufficient for you 😄!

Enjoy the tunes 🎵
