### ISSUE TITLE
Update Mpris Identity

### ISSUE THREAD

**Issue by Batwam** [Mastermindzh/tidal-hifi#338]
Hello,

I am using/contributing to a [gnome extension](https://github.com/Moon-0xff/gnome-mpris-label) to control Tidal Hi-Fi and noticed that the app's sound identifies as `chromium` which prevents the extension from being able to link the app and the corresponding sound "stream". Is there any way for the app to not identify the sound stream as `chromium` or this is hard coded somehow? Ideally, this list should show "TIDAL Hi-Fi" and the app mpris Identify be updated to match. 

I can't really change the code to control anything called `chromium` as this could also affect the sound of the user's browser...

![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/bd24e143-a33a-45b4-a302-ca7cbd9d4555)

**Comment by Mastermindzh** [comment]
Hey,

The chromium instance from Electron will always show up, we haven't found a way to disable it yet.
But... if MPRIS is configured correctly it should show a "tidal-hifi" entry which is manually controlled by the app:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/d1c1fc40-2029-4be1-ad4b-bc64aa1fe5b2)

**Comment by Batwam** [comment]
Thanks for the response. The Identity field is fine (although it should probably be "TIDAL Hi-Fi") to match the project name while DesktopEntry would remain as `tidal-hifi` to match the .desktop. 

All mpris function work just fine, the challenge is to identify the corresponding VolumeMixer sound "Streams" in Gnome since the player identifies as `chromium`. I have seen similar behaviour on chromium-based browsers which also all identify as `chromium` so it looks like it's impossible to know which VolumeMixer stream matches which mpris source. 

Anyway, it doesn't look like it's fixable unfortunately so we can probably close this Issue. Thanks again for the quick reaponse.

**Comment by Mastermindzh** [comment]
mpris doesn't allow the name `TIDAL Hi-Fi`, which is why we had to keep "tidal-hifi".
Can't you change volume through mpris + playername:

`playerctl --player=tidal-hifi volume 100`

Come to think of it, we might not even have support for that command in TIDAL.

**Comment by Batwam** [comment]
that's right, you don't have support for that in tidal-hifi:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/784b9397-5582-4ddb-9824-323f093e74aa)

We found this to be the case for a number of mpris sources. Spotify for instance only works with 100 and 0 for some reason:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/130099de-5cb1-468f-8f43-bd9d61cc2e08)

This is why we decided to instead identify the VolumeMixer Stream (by name) and adjust that instead.

**Comment by Batwam** [comment]
> mpris doesn't allow the name `TIDAL Hi-Fi`, which is why we had to keep "tidal-hifi".

by the way, in what way mparis doesn't allow this? I note that Firefox has a space in its `Identity` and works just fine:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/d7cadf71-79fa-4185-94a6-8302b571b29a)

**Comment by Mastermindzh** [comment]
@Batwam, I'd have to check precisely what it doesn't allow, we've had issues with MPRIS not working when we changed the name, see: https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.7.1

I think it was capitalization.


Anyway, I have researched the possibility of removing the chromium client, and that doesn't seem to be possible.
I could try to implement volume control, but I have no idea whether that would help you any further.

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/6445162b-f5b8-479b-b7cb-647ac0ea284a)

😄

**Comment by Batwam** [comment]
That seems promising. Do you know how the player is going to show in the Gnome Volume Mixer by any chance?

**Comment by Mastermindzh** [comment]
I do not. It should just be the same as the current "mpris" interface (so `tidal-hifi`).
I will be able to publish it tonight, but you can also build it yourself to check it out if you want 😄

**Comment by Batwam** [comment]
No worries, I'll wait for it to get published and let you know. Some (all) chromium based browsers identify as `chromium` and have a different `Identity` so it's quite possible that tidal_hi-fi will be same.

**Comment by Batwam** [comment]
Hey, the version on flathub is still 5.8. Is there a plan to update it?

**Comment by Batwam** [comment]
No worries, just checking as my free Tidal trial is going to expire soon so I won't be able to test anymore 😅

**Comment by Mastermindzh** [comment]
@Batwam , it's waiting to be merged: https://github.com/flathub/com.mastermindzh.tidal-hifi/pull/21

You can install it from testing if you want 😄.
Interested to know your follow-up.

**Comment by Batwam** [comment]
ok, it shows as tidal hi-fi under mpris but still Chromium in the Volume Mixer
![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/71ced8c4-3738-41eb-ae6c-e27c15fd76df)

![image](https://github.com/Mastermindzh/tidal-hifi/assets/56710655/c2b4eee2-53f2-43f0-90d2-570050a9c32a)

**Comment by Mastermindzh** [comment]
Alright, well then idk what the volume mixer is picking up, probably got some deeper integration than just mpris 😄.
Thanks anyway!
