### ISSUE TITLE
Next song shortcut called three times

### ISSUE THREAD

**Issue by AlexandreCollet** [Mastermindzh/tidal-hifi#34]
Hello ! 

I tried the next song shortcut with "Ctrl+right" and noticed that it is called three times. 
So i looked the source code and in preload.js the hotkey is added twice.
 
But .. i don't understand why it is called three times on my desktop. If i remove all next song hotkeys, the shortcut is always called once.

By the way thanks for the repository :) 
I will be happy to create a pull request but for now i'm not sure if the problem is just on my desktop.

**Comment by Mastermindzh** [comment]
The third one is probably the Tidal window also catching the shortcut, that didn't use to work (hence hotkeyjs).
I'll remove the duplicate hotkey tomorrow (it's late now..) and see whether I can reproduce the third trigger.

I'll add shortcuts behind a setting tomorrow anyway so people have a chance to disable them.

Thanks for the feedback 😄

**Comment by AlexandreCollet** [comment]
I'm not sure for the tidal window because the "previous song" shortcut works perfectly ! 
Good idea for the settting :)

**Comment by Mastermindzh** [comment]
This issue should be solved in [version 2.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.0.0)

Thanks for the notice and enjoy!
