### ISSUE TITLE
Tidal-hifi opening on linux thousand times notification.jpg

### ISSUE THREAD

**Issue by nairamk** [Mastermindzh/tidal-hifi#342]
Hi,

I see on my laptop that tidal-hifi opens the notification.jpg file thousands of times - in my case exactly 6622 and growing ...
... up to "to many open files"

$ lsof +D /home/xxxxxx|grep notification|wc -l
6622

$ lsof +D /home/xxxxx|grep notification
tidal-hif 166977 xxxxxx   50w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   51w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   52w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   58w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   59w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   60w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
tidal-hif 166977 xxxxxx   61w   REG              259,2        0 1083540983 /home/xxxxxx/.config/tidal-hifi/notification.jpg
...

$ uname -a
Linux black 5.19.0-46-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 13:30:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"

$ apt list|grep hifi

tidal-hifi/now 5.7.1 amd64

**Comment by Mastermindzh** [comment]
Currently without power (my entire city) so I can't build and release a new version but I've narrowed down why this happens and will fix it.

Thanks!
