### ISSUE TITLE
About - links open in About window, not external browser

### ISSUE THREAD

**Issue by gerbrent** [Mastermindzh/tidal-hifi#346]
In the `About` window (much improved now! #275 ) the links to Github, Report an Issue, etc open in the current About window, not an external browser as indicated.

![about - links open in about window, not external browser](https://github.com/Mastermindzh/tidal-hifi/assets/7018928/d3735314-b6a4-42ac-b0de-6e2cbc346cc1)

**Comment by Mastermindzh** [comment]
Oh. Woops 😄 !

Good catch!

**Comment by Mastermindzh** [comment]
Fixed in 5.10.0
