### ISSUE TITLE
image selector changed

### ISSUE THREAD

**Issue by AlexandreCollet** [Mastermindzh/tidal-hifi#35]
Hello :) 

When i'm tried to make my polybar integration i noticed than the current song is always empty.
So i have looked at why and i found than the "image" selector is no longer good. 
I replaced it only with "img" and it's ok. 

But maybe we should also resolve the promise if the image is null to still have the title and artists availables ? 

Sorry for my english.

**Comment by Mastermindzh** [comment]
Agree on the resolve, will fix that.
Will have to look into the image/img thing. Worst case I'll search for both :)

Thanks for the feedback.

PS: your English is fine.

**Comment by Mastermindzh** [comment]
Dear @AlexandreCollet,

I have been ignoring you. I can think of lots of excuses but they would be of no use.
I will work on this when I have time. I am guessing that will be on Sunday. Stay tuned.

My apologies for the delay.

**Comment by Mastermindzh** [comment]
This issue should be solved in [version 2.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.0.0)

Thanks for the notice and enjoy!
