### ISSUE TITLE
 get the full experience

### ISSUE THREAD

**Issue by snowloveme** [Mastermindzh/tidal-hifi#352]
Completely installed but cannot play music and error shown  get the full experience....

**Comment by Mastermindzh** [comment]
What OS are you on?
Do you have a screenshot or something to go on?

**Comment by HMSAngelo** [comment]
I got the same issue.
![image](https://github.com/Mastermindzh/tidal-hifi/assets/161199282/078111a5-f243-4474-a312-8992d3353e01)
Running on Windows11

**Comment by Mastermindzh** [comment]
@HMSAngelo, did you pay for the service?

Also, on Windows the DRM it doesn't work see: https://github.com/Mastermindzh/tidal-hifi?tab=readme-ov-file#drm-not-working-on-windows
