### ISSUE TITLE
MPRIS pause not returning the paused signal

### ISSUE THREAD

**Issue by grizeldi** [Mastermindzh/tidal-hifi#356]
Whenever I try to pause tidal-hifi playback through gnome's music player controls, the music does stop playing, but the pause button in the gnome dock doesn't turn into a play button, so gnome still thinks the music is playing. Most of the time this isn't more than a mildly annoying but otherwise harmless UI issue, as clicking the "pause" button resumes the track again in 80% of cases, but it does break things like GSConnect, which keep track of the current seek position in the song internally, as they do not receive the paused signal and just keep counting.

Ubuntu 23.10
tidal-hifi 5.9.0 from flathub

**Comment by DatLem0n** [comment]
This also prevents Play/Pause shortcuts from working so media keys bound to that do not work

6.7.9-arch1-1
Plasma 6.0.1 (Wayland)
tidal-hifi 5.9.0 (aur)

**Comment by hajosattila** [comment]
same here

6.8.1-AMD-znver3
sway 1.9
Waybar v0.10.0
tidal-hifi-5.9.0 (AppImage)

**Comment by Mastermindzh** [comment]
Will check this weekend 😄

**Comment by Mastermindzh** [comment]
Pretty sure it's the same cause as this one: https://github.com/Mastermindzh/tidal-hifi/issues/370.
WIll test today
