### ISSUE TITLE
ListenBrainz scrobbling is not working

### ISSUE THREAD

**Issue by xplosionmind** [Mastermindzh/tidal-hifi#357]
Hello, even though I successfully added my API key, the ListenBrainz scrobbler does not seem to work. Is there a way to debug this?

**Comment by Mastermindzh** [comment]
You have 2 ways of doing so:

- Run from source and set breakpoints / add loggers (user `Logger.log`)
- Look at HTTP traffic with devtools or software like wireshark


I just tried it on my machine with 5.9.0 and it seems to scrobble fine:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/74059a5c-0cd6-439e-9acb-20dc9a8bcce8)

**Comment by HiWayChile** [comment]
I have a problem adding listenbrainz token. I added a token from [https://listenbrainz.org/settings/], but it doesn't seem to work. No scrobling to listenbrainz and when I exit tidal it seems that the token is not saved.

**Comment by Mastermindzh** [comment]
@HiWayChile,

can you make a video of what is happening for you as I am utterly unable to replicate the issue?
Last.fm support is included in the base TIDAL app, you can get to it through your account settings:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/63b8af0a-cf47-4a05-9928-fbf9e536acc4)
