### ISSUE TITLE
Bug on Ubuntu

### ISSUE THREAD

**Issue by Fandyfr** [Mastermindzh/tidal-hifi#362]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/135007919/0c069578-bb0a-4d0f-84da-f717090d58d8)

**Comment by Fandyfr** [comment]
i'm use ubuntu version 23.10

**Comment by alexandrdera** [comment]
I have the same problem. Have you found a solution?

**Comment by Mastermindzh** [comment]
@alexandrdera what version are you using? Flatpak? .deb?

I can only try to reproduce when I have that info.
I have time to work on it this weekend so would be great if you could have these details for me before that time.

Also, what country are you in?

**Comment by billieto** [comment]
Hello same problem here ubuntu LTS snap install, i am from greece

**Comment by billieto** [comment]
Solved it downloading via flatpak

**Comment by alexandrdera** [comment]
> Solved it downloading via flatpak

![IMG_20240320_203535.jpg](https://github.com/Mastermindzh/tidal-hifi/assets/5359160/2f029a67-e950-486f-b8aa-e8c55fed9def)

I have same problem via flatpack too.

**Comment by alexandrdera** [comment]
I'm using ubuntu studio 23.10![IMG_20240320_201029.jpg](https://github.com/Mastermindzh/tidal-hifi/assets/5359160/e51f93ea-457c-4b3a-9dab-33553675bc89)

**Comment by alexandrdera** [comment]
Also a see JavaScript error in About menu![IMG_20240320_195331.jpg](https://github.com/Mastermindzh/tidal-hifi/assets/5359160/deb454a6-9676-4bad-aa12-31a5869e5cb6)

**Comment by alexandrdera** [comment]
Flatpak install:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/5359160/a4d7237f-5d87-443c-86af-60df9b9bd8cc)

**Comment by Mastermindzh** [comment]
@alexandrdera I have no clue what you're doing wrong. I can't replicate it on my end and it doesn't seem to be a country restriction according to your testing which was what my guess was.

I will give it more thought but I don't think I can help :/

**Comment by alexandrdera** [comment]
@Mastermindzh , Hi!
I have success install Tidal by flatpak on new installed Ubuntu Studio 23.10 on VirtualBox. Importent! First run Tidal must be with europien VPN!

In first case, on my first operation system, first run was without VPN, thats why I have trouble message.

But how me reinstall Tidal on my previous OS?

**Comment by alexandrdera** [comment]
Decision problem for Russia is VPN and:
```
cd ~
rm -rf .config/tidal-hifi/
LANGUAGE=en LANG=en_US.UTF-8 tidal-hifi
```

@Mastermindzh , thank you for work!

**Comment by Mastermindzh** [comment]
@alexandrdera that's what I was thinking but couldn't verify :/

Thanks for your debugging and sucks that you have to run it with a workaround for living in Russia 😄.
