### ISSUE TITLE
Hotkeys stop working after computer Suspend/Resume

### ISSUE THREAD

**Issue by Akryum** [Mastermindzh/tidal-hifi#368]
After I suspend my computer and wake it up, Tidal doesn't respond to hotkeys (like Play/Pause) anymore. I need to fully exit it then launch it again then hotkeys start working again. Refreshing the page in the electron window doesn't work.

Tidal Hifi version 5.9.0

```
  System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
    Memory: 28.91 GB / 62.70 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
```

**Comment by Mastermindzh** [comment]
Interesting... what command do you use to suspend?
I haven't tested any suspend behaviour and I don't use the media hotkeys so I never encountered this.
