### ISSUE TITLE
How to setup through ALSA?

### ISSUE THREAD

**Issue by mmpty** [Mastermindzh/tidal-hifi#37]
There's such a way to setup tidal-hifi output through ALSA?

**Comment by ingvarr777** [comment]
I second this

**Comment by mmpty** [comment]
@ingvarr777 since tidal-hifi is a PWA.. I did as follows.
![Screenshot_20210320_142320](https://user-images.githubusercontent.com/54506685/111880043-fb5ed180-89a0-11eb-9cd5-4f8f2ba4ced5.png)
