### ISSUE TITLE
Media key integration and playback status issues with tidal-hifi

### ISSUE THREAD

**Issue by Darogirn** [Mastermindzh/tidal-hifi#376]
Environment:

Operating System: Nobara Linux 39
Desktop Environment: KDE Plasma 6.0.3
Qt Version: 6.6.2
Kernel Version: 6.7.6-201.fsync.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 15.5 GiB RAM
Graphics: AMD Radeon RX 6750 XT
tidal-hifi Version: 5.9.0 (Flatpak)

Issue Description:
The pause/play media key on the keyboard is not working as expected with the tidal-hifi app. The key only functions once to either pause or play a song. After the initial use, the pause/play key stops working, and I have to manually control playback using the media control widget or the tidal-hifi app itself.

Additionally, when the pause/play key is used, the media control widget in the taskbar or notification area does not accurately reflect the current playback status. For example, if a song is paused using the media key, the media control widget continues to show the song as playing, even though the audio has been paused.

Steps to Reproduce:

Launch the tidal-hifi app.
Start playing a song.
Press the pause/play media key on the keyboard.
Observe that the song is paused or played as expected.
Press the pause/play media key again.
Note that the media key no longer functions to pause or play the song.
Also, observe that the media control widget in the taskbar does not reflect the correct playback status after using the media key.

Expected Behavior:
The pause/play media key should work consistently to control playback in the tidal-hifi app, without any limitations on the number of times it can be used. 

Please let me know if you need any further information or if you have any additional details that could help diagnose and resolve this issue.

**Comment by TheRockYT** [comment]
Thanks @Darogirn  for the detailed description. I can reproduce the problem on GNOME.

I found that the global shortcut in electron, which is currently used to provide the functionality, doesn't work well with the media buttons, but it does work consistently with other shortcuts like `CmdOrCtrl+x`.

I also saw that there is a custom implementation for media sessions in the preload script, which is usually used to provide the shortcuts and OS integration for media playback on websites.

Media Session API: [mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API)

There is already an implementation for media sessions on listen.tidal.com, but both (custom and official) are disabled by the `disable-features` -> `MediaSessionService` flag, as a fix for #338.

I don't use the MPRIS interface so I removed the global shortcuts and custom media sessions, and enabled the MediaSessionService flag in my fork. This restores the behaviour as in Chromium, but may break some parts of MPRIS.

I will be testing my changes for a few days and may submit a PR, trying not to break issues that have already been solved.

**Comment by Mastermindzh** [comment]
Thanks for looking into it @TheRockYT, I am willing to revert/reconfigure the fix for mpris if it breaks this too.
The fixes for MPRIS didn't lead to the desired result and can always be put behind a few flags.

**Comment by SonGoku90** [comment]
Hello, I have the same problem with shortcuts in Fedora 40 gnome on Wayland.

**Comment by Mastermindzh** [comment]
Fixed in [5.11.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.11.0)
