### ISSUE TITLE
Discord RPC for Tidal HIFI is not working

### ISSUE THREAD

**Issue by bubasekdev** [Mastermindzh/tidal-hifi#377]
Discord RPC for Tidal HIFI is not working. I use Fedora and I have Discord RPC setting on Tidal HIFI app turned on and is not working. Can you fix it, please?

**Comment by Deewens** [comment]
Same using flathub package

**Comment by Mastermindzh** [comment]
Yep, you need to enable some extra permissions in Flatpak to get this working, all other versions have the integration working 😄.z
I have heard that "flatseal" might be able to set some settings.

But I'm not a Flatpak user so I really am not sure 😓

**Comment by bubasekdev** [comment]
> Issue is probably due to Flatpak packaging (maybe others? Idk). I guess, some permissions needs to be set, but I am not sure. It works with the .deb version, so I think it should work with the rpm also.

I don't use flatpak version discord, I'm using tar.gz and rpm discord doesn't exist i guess. so I want know what permissions do I need. (sorry for my bad english😂)

**Comment by bubasekdev** [comment]
> Yep, you need to enable some extra permissions in Flatpak to get this working, all other versions have the integration working 😄.z
> I have heard that "flatseal" might be able to set some settings.
> 
> But I'm not a Flatpak user so I really am not sure 😓 

okay, i'll try flatpak version

**Comment by Mastermindzh** [comment]
You'd be best off installing both natively i.m.o, app isolation/sandboxing is great in theory but I have yet to see it pay off.
If you install both rpms you should be fine.

Here's a guide to install Discord using RPM: https://itsfoss.com/install-discord-fedora/
