### ISSUE TITLE
Remember volume and repeat/shuffle

### ISSUE THREAD

**Issue by pawel-szopinski** [Mastermindzh/tidal-hifi#38]
Hi,

Is there any way for the app to remember your last used volume level and state of buttons like repeat or shuffle from your last session? Currently, when I close the app and I had, let's say volume set to max, it does not get saved, since when I open it again it sits at default 50%.

Thanks!

**Comment by Mastermindzh** [comment]
Hey @pawel-szopinski,

Do you have any additional info? I can't seem to replicate the problem on Arch.
What version are you using?

**Comment by pawel-szopinski** [comment]
Well, it seems like restarting it a couple of times and restarting laptop did the trick. Apologies for bothering you with this and thanks for bringing the HiFi quality audio to Linux. Awesome work!

**Comment by Mastermindzh** [comment]
No problem my friend! Glad to hear it now works as expected.
Appreciate the kind words. Have a great day 👍🏻
