### ISSUE TITLE
Change to use universal media links on discord rpc button press

### ISSUE THREAD

**Issue by DatLem0n** [Mastermindzh/tidal-hifi#383]
I'm suggesting changing the functionality of the RPC button to use the new Tidal universal media links. This feature would improve compatibility with discord users who don’t use Tidal.

Currently the listen along button gives a link directly to Tidal, whereas Tidal recently started supporting universal links that can redirect to spotify etc.

The only change needed is to append "?u" to the end of the media url to use the universal link.
e.g. instead of https://tidal.com/browse/track/3146735 
you would get https://tidal.com/browse/track/3146735?u

Minor change, but I'm sure this would be appreciated by many :+1:

**Comment by Mastermindzh** [comment]
Hey,

I didn't know TIDAL offered universal links 😄, been using Songwhip for it.
Will add this to the app soon!

**Comment by Mastermindzh** [comment]
Fixed in [5.11.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.11.0)
