### ISSUE TITLE
Unable to change volume with playerctl

### ISSUE THREAD

**Issue by Shringe** [Mastermindzh/tidal-hifi#387]
With Strawberry music player playerctl works as expected, but with Tidal-hifi the volume controls do not work at all. `playerctl status` shows it is recognized, `play-pause`, `next`, and likely the others function as normal. `playerctl volume` gives me a value of `0.000000`, and if I try to set with `playerctl volume 0.5` nothing changes under Tidal nor `playerctl volume` value.

Let me know if I can provide any additional info on the issue if it's not replicable.

**Comment by Shringe** [comment]
Likely related to #384.

**Comment by Mastermindzh** [comment]
This is a known issue that we haven't had the time to solve yet.
Marked it as a bug & enhancement since the implementation of this feature isn't done at all 😄

**Comment by Mastermindzh** [comment]
Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/199
