### ISSUE TITLE
tidal-hifi crashes when not invoked from terminal

### ISSUE THREAD

**Issue by bjornpijnacker** [Mastermindzh/tidal-hifi#389]
I noticed recently that Tidal Hifi crashes a few seconds after starting. In an attempt to debug it, I ran it from a terminal to see logging; however, I noticed this made the problem go away. In general: Tidal Hifi crashes when started in Gnome from the `.desktop` file but not when invoked from my terminal. A screencapture below shows the issue:

https://github.com/Mastermindzh/tidal-hifi/assets/35508080/66480e6c-d368-441e-b567-05df6026ea51

As you can see, the first instance, running from Gnome launcher does not work. It crashes soon after starting. The second instance, running from the terminal, works fine. This is something I can reliably reproduce.

The desktop file is as follows (at /var/lib/flatpak/app/com.mastermindzh.tidal-hifi/current/active/export/share/applications/com.mastermindzh.tidal-hifi.desktop):
```
[Desktop Entry]
Name=TIDAL Hi-Fi
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.mastermindzh.tidal-hifi com.mastermindzh.tidal-hifi
Terminal=false
Type=Application
Icon=com.mastermindzh.tidal-hifi
StartupWMClass=tidal-hifi
Encoding=UTF-8
GenericName=TIDAL Hi-Fi
Comment=Tidal on Electron with widevine(hifi) support
StartupNotify=true
Categories=AudioVideo;
X-PulseAudio-Properties=media.role=music
MimeType=x-scheme-handler/tidal;
X-Desktop-File-Install-Version=0.27
X-Flatpak-RenamedFrom=tidal-hifi.desktop;
X-Flatpak=com.mastermindzh.tidal-hifi
```

Using the same `Exec` command to run from terminal does not crash Tidal Hifi. I have not made any changes to the flatpak application using tools such as Flatseal or similar.

**Comment by Mastermindzh** [comment]
I've just tried to reproduce this and am unable to.
Can you use one of the other builds and check those?

**Comment by bjornpijnacker** [comment]
I've tried AppImage and RPM and those both work fine. In testing just now I tried reinstalling the Flatpak using the `--delete-data` flag which seems to have fixed the issue :+1:.

**Comment by Mastermindzh** [comment]
Thanks for the update @bjornpijnacker!

Glad it works as expected now.
