### ISSUE TITLE
[Feature Request] Additional Data/Endpoints in API

### ISSUE THREAD

**Issue by ThatGravyBoat** [Mastermindzh/tidal-hifi#393]
As it currently stands the API endpoints do not give all the information something that wants to interface with it may need.
Here are a few that I currently need as I want to add support in a Minecraft mod I work on called [Craftify](https://modrinth.com/mod/craftify) where several requests for Tidal support have been requested.

The following are what I need but cant find in the API as it currently is:
- In data returned by current the current state of the player ie. shuffle, repeat, and volume
- In endpoints
= Setting shuffle state
= Setting repeat state
= Changing volume

There are also some problems with the data is not reliable in the sense of durations and artists being strings when they should be a number and a list respectively. Currently for me to get the actual duration as I need it for a progress bar I need to parse the `current` and `duration` fields

**Comment by Mastermindzh** [comment]
I can implement most of this pretty easily in the coming days.

- Changing the volume might not be possible for now, probably part of a bigger feature that involves volume control in general.
- Tidal Reports the artist as a single field, not a list of collaborators. We are just sending whatever TIDAL says is the `Artist`.

Will be available soon.

**Comment by ThatGravyBoat** [comment]
> * Tidal Reports the artist as a single field, not a list of collaborators. We are just sending whatever TIDAL says is the `Artist`.

Ahh okay that makes sense, not that big of a deal 👍

**Comment by Mastermindzh** [comment]
I rewrote the entire API to be a bit clearer (and the code much cleaner) and also to use the correct HTTP verbs as well now.
The old (now: legacy) endpoints still work and I have no plans of removing them.

New `POST` endpoints:

- `/player/play`
- `/player/favorite/toggle`
- `/player/pause`
- `/player/next`
-  `/player/previous`
-  `/player/playpause`
-  `/player/shuffle/toggle`
-   `/player/repeat/toggle`

Also 1 new `GET` endpoint:

- '/current/image'`

I also updated the mediaInfo with most of what you wanted, durationInSeconds & currentInSeconds are now available as integers as well:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/2084f083-dac2-48af-a4d5-1c352916bbe4)

**Comment by Mastermindzh** [comment]
Fixed in [5.11.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.11.0).

If you want to promote your mod you can make a PR adding it to the README if you wish :)
