### ISSUE TITLE
Max isn't available

### ISSUE THREAD

**Issue by codelikeachode** [Mastermindzh/tidal-hifi#399]
With the change in Tidal's subscription plans, Max is available for everyone now. But I can't select it from within the app. The screenshots attached shows the difference. The first one is the application, second is the Tidal web player. I thought max quality was supposed to be available though.

![tidal-hifi-bin1](https://github.com/Mastermindzh/tidal-hifi/assets/90079899/9b7b0082-ae9e-4d36-9691-2f8339b2d44c)

---

![tidal-web-player](https://github.com/Mastermindzh/tidal-hifi/assets/90079899/4339c7dd-0a46-4d25-bc6a-272c7ea907a1)

**Comment by Mastermindzh** [comment]
Hey,

As long as you're paying a subscription you should be able to access it now 😄.
Though, TIDAL is stubborn with logins etc so it might be best to remove all cache and relog.
You can do so with the following commands:

```sh
# safeguard the config
cp ~/.config/tidal-hifi/config.json ~/tidal-config.json

# delete the caches/login/browser info
rm -rf ~/.config/tidal-hifi/

# you can start tidal here with the default config, or copy it back first
cp ~/tidal-config.json ~/.config/tidal-hifi/config.json

# you can remove the config file from your home directory that we used as a backup:
rm ~/tidal-config.json
```

**Comment by codelikeachode** [comment]
Thanks, all is good now!
