### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'shuffle')

### ISSUE THREAD

**Issue by spikespaz** [Mastermindzh/tidal-hifi#403]
After updating today, the app fails to load.

Blocker for: https://github.com/NixOS/nixpkgs/pull/311841

All I have is a GTK dialog:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/12502988/7e00d0be-28e0-43cc-a376-2f8e36afd1aa)

**Comment by spikespaz** [comment]
This issue went away after two re-launches.

**Comment by Swipe650** [comment]
Mine went away but came back again

**Comment by antznin** [comment]
I have this too. It went away after a few clicks, but comes back after a reboot. It does not seem to reappear if I close and re-open the app. It takes a few clicks on "Ok" to get rid of the error, but then after that it's gone for good (until the next reboot).

**Comment by Mastermindzh** [comment]
I'll make sure to test the latest release this weekend.
I didn't verify the latest build much myself as the impact from the last PR seemed small and was tested by a trusted member of the community.

Sorry for the inconvenience 😄 !
