### ISSUE TITLE
Upper-left corner of screen becomes uninteractable when tray icon is enabled

### ISSUE THREAD

**Issue by Raindrac** [Mastermindzh/tidal-hifi#406]
I'm running Fedora 40 Kinoite; that's Plasma 6, with Wayland enabled. I'm using the Flatpak.

When Tidal Hi-Fi is opened and the tray icon is enabled, the upper left corner of my screen, roughly a 30x30px square, becomes uninteractable. Minimizing, resizing or moving the window has no effect, the issue occurs across all virtual desktops while the program is open, and the issue occurs even when another application is in fullscreen. 

My cursor becomes an x if I hover it over the uninteractable area. There's also a smaller area, roughly 15x15, where clicking will switch the window focus to Tidal Hi-Fi (if it's not in focus) or minimize it to the tray (if it's already in focus). Minimizing the program to the tray and then maximizing it again resolves the issue until the next launch, so it's an effective workaround. 🙂

This might be an upstream issue with Plasma, but I can't be sure of it. xwaylandvideobridge causes the same issue while minimized to tray and it affects an even larger area, roughly 30x100. So either both Tidal Hi-Fi and xwaylandvideobridge have a similar bug, or there's a bug with Plasma that's the root cause of both issues. I dunno.

**Comment by Mastermindzh** [comment]
@Raindrac tomorrow I'm going to work on some fixes and can at least try to replicate.

Does it happen with any of the other versions as well?

**Comment by Raindrac** [comment]
Alrighty, I tried out the appimage and .rpm and couldn't replicate the issue. It appears to only affect the flatpak, and only while the tray icon is enabled! That narrows it down.

Incidentally, I also happened to notice that the tray icon is much clearer on the appimage and rpm versions. While running the flatpak, it's considerably blurrier.

Here is how it looks while running the rpm or appimage:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/151923221/c8bc916f-11ae-49c8-b249-3ffa0c710b34)

And here is how it looks while running the flatpak:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/151923221/364d8f0c-cd81-4cdf-bd8c-72ae3417a89e)

I could file this under a separate bug report if you'd like.

**Comment by Mastermindzh** [comment]
I don't think it's necessary to create a new issue, thank you!

Friend of the project @Mar0xy packaged the Flatpak version, let's see if she knows why this behaviour is happening 😄.

@Mar0xy, is there a specific reason for the Flatpak tray icon to behave differently from the others?
Later today I'll do a bugfix & feature release, I could replace the icon as well but that won't fix the weird tray issue yet.

**Comment by Raindrac** [comment]
Good news, I was reading through [this blog post](https://pointieststick.com/2024/05/25/this-week-in-kde-triple-buffering-and-other-sources-of-amazingness/) when I found a relevant line:

> On Wayland, when any apps that have System Tray icons are running, there’s no longer a little invisible square in the top-left corner of the screen that eats input

So, I checked it out, and yeah, [it was an upstream issue after all!](https://bugs.kde.org/show_bug.cgi?id=433079) It's fixed in Plasma 6.1.

**Comment by Mastermindzh** [comment]
Nice! Enjoy all your interactable space again @Raindrac!
