### ISSUE TITLE
Its that time again! Album is gone from metadata for playlists again...

### ISSUE THREAD

**Issue by jonseppanen** [Mastermindzh/tidal-hifi#412]
```
playerctl -a metadata
tidal-hifi xesam:title               Dig
tidal-hifi xesam:artist              Mudvayne
tidal-hifi xesam:album               
tidal-hifi mpris:artUrl              https://resources.tidal.com/images/ee2a064d/79a9/4c05/ae08/5c44b644c667/640x640.jpg?cors
tidal-hifi mpris:length              30000000
tidal-hifi mpris:trackid             '/org/mpris/MediaPlayer2/track/1781155'
```

I know this one is annoying and recurring. Could we get another fix for this one please?

**Comment by Mastermindzh** [comment]
I'll have time to look at it this weekend, probably another change in how they present albums 😄.

**Comment by jonseppanen** [comment]
I recently (almost) built an ags widget service for deezer till their lack of track progress made me jump back to tidal...
If you can point me to the function that should be pulling album art I can try take a look. Deezer flatpak doesnt supply album or album art so I had to do some trickery with the api to get it. Can probably use something similar.

**Comment by Mastermindzh** [comment]
@jonseppanen, album is working correctly for me.
The only time it doesn't show up is if you're playing something from a playlist but don't have the playlist open, then the window doesn't actually display an albumName and we are using the DOM to gather our info (so no info on screen === no way to get it)

Can you verify?

**Comment by jonseppanen** [comment]
I can verify quite easily!
Latest flatpak shows this: 
![2024-06-09-222422_hyprshot](https://github.com/Mastermindzh/tidal-hifi/assets/10136068/bdfe9d6f-ed56-4ca1-8aa8-c6df6b34e9f1)

Top bar using MPRIS for data (just polls it)

Should look like this:
![2024-06-09-222711_hyprshot](https://github.com/Mastermindzh/tidal-hifi/assets/10136068/a4bc5331-40d2-4f07-be88-e9597c643896)

Album shows up if playing an album directly. Once album is finished, and it wanders to other music, album disappears, even though its visible in the html.

**Comment by jonseppanen** [comment]
It doesnt _always_ break though. Only about 1/3rd of the time after I let album finish. Its weird.

**Comment by Mastermindzh** [comment]
Go back to the home page, does it show back up again?

We aren't handling the "Queue" screen explicitly for albums so it doesn't work there, but it works on the regular album view:
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/3c20872e-51fc-4a5d-a9da-6cdc15b188e6)

I can probably add code to check the queue screen as well.
Though for your integration you might want to look at the "playingFrom" field instead, that'll always show where you're playing from (e.g. either album, mix, or playlist name):

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/e44486a3-db6d-4680-aa19-8f7de3b2c61a)

PS: Good choice in music, I like wardruna too 😄

**Comment by Mastermindzh** [comment]
Gotta go visit my parents in a bit, but I got it fixed in the queue screen as well:

![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/19ef13e1-aaba-47e8-8a71-ecb65cec1449)

**Comment by Mastermindzh** [comment]
We should probably make all the info from the API also available through mpris, what do you think?

**Comment by Mastermindzh** [comment]
![image](https://github.com/Mastermindzh/tidal-hifi/assets/4190290/4167af00-0ac3-4a22-b308-2676b9318695)
There we go, now I gotta run 😄

**Comment by jonseppanen** [comment]
You are an absolute legend! Thanks for this!

**Comment by Mastermindzh** [comment]
No worries, might take a bit for the flatpak to be updated though.
Didn't have time to do it today but will probably have some time tomorrow evening 😄
