### ISSUE TITLE
DOCS: markdown link in monospace section

### ISSUE THREAD

**Issue by Seth-Buchanan** [Mastermindzh/tidal-hifi#421]
In the "Using source"  section of the docs the git clone link is a markdown link in a mono space section. This shows the link twice in the github front page. I'm also too lazy to do a pull request to fix it.

**Comment by Mastermindzh** [comment]
Appreciate the honesty and the fact that you made a ticket.

Fixed it with: https://github.com/Mastermindzh/tidal-hifi/commit/c63e05357e985f5fd25fa546fe440a27fa1b8069
