### ISSUE TITLE
v5.14.1 - S6007 errors on all songs

### ISSUE THREAD

**Issue by dbecker801** [Mastermindzh/tidal-hifi#428]
I just installed v5.14.1 on Windows 11. Songs play for about 10-12 seconds before popping up the following error message: "There was an unexpected error. Try again later. (S6007)". This happens regardless of quality settings. This is not an issue playing through a web browser (Firefox 127).

**Comment by Mastermindzh** [comment]
Hey @dbecker801,

This is a known issue, see: https://github.com/Mastermindzh/tidal-hifi?tab=readme-ov-file#drm-not-working-on-windows

Nothing we can do for now, sorry.

**Comment by PascalDognaux** [comment]
I am getting this error as well on Ubuntu Linux (22.04 Kernel 6.8.0-48), so I installed the latest version of Tidal-hifi 5.17.0 and still getting the error after playback of about 15 to 20 seconds.  I get  "There was an unexpected error. Try again later (S6007)" The problem above was on Windows. Is that the same issue?
Thanks
Pascal

**Comment by Mastermindzh** [comment]
Hey @PascalDognaux,

Yeah it's a **given** on Windows but it sometimes also happens on Linux.
Unfortunately there is nothing I can do to fix it, since S6007 is a refusal from the server to stream the media.

Usually removing the config and restarting or relogging helps, but for some it never gets fixed. (People from Russia seem to be filtered too...)

**Comment by sahandv** [comment]
> I am getting this error as well on Ubuntu Linux (22.04 Kernel 6.8.0-48), so I installed the latest version of Tidal-hifi 5.17.0 and still getting the error after playback of about 15 to 20 seconds. I get "There was an unexpected error. Try again later (S6007)" The problem above was on Windows. Is that the same issue? Thanks Pascal

A full purge of the deb and installing the snap worked for me. Unsure how long it will keep working. Maybe it's worth a try?
