### ISSUE TITLE
[Feature Request] - TIDAL Staging

### ISSUE THREAD

**Issue by wont-stream** [Mastermindzh/tidal-hifi#437]
Was digging through DNS records and found `listen.stage.tidal.com` which as implies, seems to be the beta version of the web app.

I can't find any mentions of it, and only change I can visibly see is a beta badge at the top left.

I was wondering if you had any info on this, and if it was in your interest to add some type of toggle for it?

**Comment by wont-stream** [comment]
I've found another difference -- in the apps settings it has another tab "Debug Menu" which seems to be a native way to toggle experiments, like the [neptune plugin  made by toonlink](https://github.com/twnlink/neptune-plugins?tab=readme-ov-file#experiments).

**Comment by Mastermindzh** [comment]
@wont-stream ,

Definitely interesting, will be adding this in the near future (and switching to it myself lol)

**Comment by Mastermindzh** [comment]
![image](https://github.com/user-attachments/assets/1f19325e-f5bb-43dd-b5de-f7bf3f7d22e2)


in the release pipelines now.

**Comment by Mastermindzh** [comment]
Delivered in 5.15.0: https://github.com/Mastermindzh/tidal-hifi/releases/tag/5.15.0
