### ISSUE TITLE
Remove from My Collection does not work

### ISSUE THREAD

**Issue by The24KFool** [Mastermindzh/tidal-hifi#440]
The "Remove from My Collection" acts like it works, but when you navigate away and back the item is still there.
This was reproducible with both Album and Tracks.
Using Linux Mint 21.3 with Flatpack 5.14.1

**Comment by Mastermindzh** [comment]
Can't reproduce, see:

https://github.com/user-attachments/assets/6e775eaf-80b9-4ae1-9072-36d5d3e56eed
