### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by PocketGlove** [Mastermindzh/tidal-hifi#441]
After a fresh install from KDE Discover, the log in/sign up screens are fully white.

**Comment by Mastermindzh** [comment]
We don't control the login screen and its actions at all.
That's all TIDAL's doing 😄 

Some countries have trouble using TIDAL though, we've had Russian users who needed to employ workarounds (like VPNs)

**Comment by PocketGlove** [comment]
Yeah I assumed, but most of the time I can't even get to the login screen cause it's just all white

And TIDAL worked perfectly for me before, so it's not the country.

Somehow it worked this time, but I have had it happen before. Mild annoyance at most.
