### ISSUE TITLE
setting up Max res

### ISSUE THREAD

**Issue by progdev66** [Mastermindzh/tidal-hifi#442]
I really like the app, it is great to be able to use Linux. I am still learning about Linux audio so I may be missing something obvious. The issue I am seeing is that when the data going to my new DAC (FiiO K5 Pro ESS) is above CD quality it changes the LED color on the front of it from blue to yellow. After finding the right configuration I am able to see this work in the Audacious music app by playing my vinyl rips (24/96). So when I play a Tidal song that shows as Max it should change the LED but it does not. So it looks like I am stuck with CD class audio. Have I missed a configuration setting that would allow hi res?

**Comment by Mastermindzh** [comment]
see: https://github.com/Mastermindzh/tidal-hifi/issues/266
