### ISSUE TITLE
Discord RPC on Vesktop

### ISSUE THREAD

**Issue by OmriPH** [Mastermindzh/tidal-hifi#444]
When using Vesktop (custom discord client) the discord rpc integration does not work.
Both Vesktop and tidal-hifi are installed as rpm on fedora 40

**Comment by corngoblin** [comment]
It does work, just not on the tidal-hifi flatpak. I can't figure out why. 
If you use the appimage, or have it directly installed and have vesktop installed as a flatpak, run
`ln -sf $XDG_RUNTIME_DIR/{.flatpak/dev.vencord.Vesktop/xdg-run,}/discord-ipc-0 `
This will allow it to work until next reboot.

The only thing that isn't working for me is the time displayed on discord.

A similar issue was talked about here
[#314](https://github.com/Mastermindzh/tidal-hifi/issues/314)

**Comment by MiMillieuh** [comment]
I have a dumb fix for flatpak version... maybe it would be applicable to you ? 
https://github.com/Mastermindzh/tidal-hifi/issues/314#issuecomment-2330099415

**Comment by rubiigen** [comment]
![image](https://github.com/user-attachments/assets/09497030-d833-4326-ae28-489fe8feffbc)
works fine for me on nixos, webcord-vencord and vesktop, and tidal-hifi installed through nixpkgs. time doesnt iterate but i have that issue using rpc on windows, too.

**Comment by ungive** [comment]
You can have a Discord status for tidal-hifi in Vesktop (via Flathub) on Linux with [Music Presence](https://github.com/ungive/discord-music-presence), including "Listening to" and a proper progress bar. There's no stable Linux release yet, I'm currently working on that, but if you wanna test some Linux previews with me (I'm the dev) and other users, feel free to join the Discord: https://discord.gg/musicpresence
