### ISSUE TITLE
Blocked artists still recommended

### ISSUE THREAD

**Issue by hoodust** [Mastermindzh/tidal-hifi#445]
Block artist (can verify the block option changes to unblock):
![image](https://github.com/user-attachments/assets/bb450576-5824-4876-b081-371e8a3fb729)

tidal-hifi still recommends:
![image](https://github.com/user-attachments/assets/0fab250b-163e-4002-a6c6-1a66db013bea)

Android app for comparison (doesn't recommend):
![Screenshot_2024-07-21-10-14-36-61_04e03425392fc155c003bf4da0c67f74](https://github.com/user-attachments/assets/42499745-0061-44cd-b2bf-5da5376e0d33)

Also still shows artist in playlists:
![image](https://github.com/user-attachments/assets/e4864a54-69a2-4b78-9682-7e2fd533c6e3)

**Comment by fijar-lazuardy** [comment]
![image](https://github.com/user-attachments/assets/1f8bc77a-7b61-43e8-8eee-dabe9eeef56c)

it will be in everything you mentioned, but automatically skipped

**Comment by Mastermindzh** [comment]
Indeed, something that TIDAL itself handles, nothing we can do about that I'm afraid.

You could add the artist to the settings as a `skipped artist` ensuring that tidal-hifi won't play any songs by said artist.
You will still see them in mixes etc, but it won't play.

**Comment by hoodust** [comment]
Yes, tidal-hifi skips tracks of blocked artists, but the official apps also don't show them in playlists or recommendations. I just kinda hoped for the same experience.

**Comment by fijar-lazuardy** [comment]
This is not unofficial app, it's web version (listen.tidal.app) that is being wrapped with electron. And what you mean as official app is native app (which is currently only available for macOS and windows for desktop)

**Comment by hoodust** [comment]
> This is not unofficial app, it's web version (listen.tidal.app) that is being wrapped with electron. And what you mean as official app is native app (which is currently only available for macOS and windows for desktop)

Android too, but I see what you mean. It seems the web version (and therefore tidal-hifi) behaves a bit differently, so it's an upstream issue. Thanks.

**Comment by Mastermindzh** [comment]
Thanks for the clarification @fijar-lazuardy.
@hoodust, exactly, might be wise to file a bug report with TIDAL directly though.
