### ISSUE TITLE
Cannot Open Settings Page

### ISSUE THREAD

**Issue by privacytime101** [Mastermindzh/tidal-hifi#446]
I am not able to open the settings page for the app (not TIDAL's web player settings). Clicking the settings menu under File>Settings does not respond, neither does clicking the Settings menu directly. However, on GNOME, right clicking the app in the dock and clicking All Windows does show an empty box labelled "TIDAL Hi-Fi Settings". The issue is that nothing is displayed.

Zorin OS 17.1 Core, TIDAL Hi-Fi 5.15 (.deb)

**Comment by Mastermindzh** [comment]
Are there any warnings or errors when you launch it from the terminal?
I'm on the latest version as well and have no issues opening it:

![image](https://github.com/user-attachments/assets/ac9e530d-67e0-4a40-8973-040c01937b08)

Things you can try:

- run tidal-hifi with the `--no-sandbox` flag
- clear the config directory (maybe there's mistakes in your config?) `~/.config/tidal-hifi`

**Comment by privacytime101** [comment]
Hi, I tried installing via the Flatpak again, but this time I manually disabled Wayland usage through Flatseal. 
The settings page is working again on the Flatpak version with this change, so I think it's safe to assume that this issue is coming from the Wayland implementation.

**Comment by Mattan1999** [comment]
> Hi, I tried installing via the Flatpak again, but this time I manually disabled Wayland usage through Flatseal. The settings page is working again on the Flatpak version with this change, so I think it's safe to assume that this issue is coming from the Wayland implementation.

Thanks! This solved the problem for me as well.
I'm running Nobara Linux 40 (GNOME Edition, v46)
TIDAL Hi-Fi 5.15 flatpak
