### ISSUE TITLE
Cannot Login on Flatpak Version

### ISSUE THREAD

**Issue by privacytime101** [Mastermindzh/tidal-hifi#447]
I am not able to log in to my TIDAL account on the Flatpak version of the app. After entering my email, I get a TIDAL error saying "Something went wrong. Please try again. If the error persists, contact customer support.". 
On another note, the "Continue with Google" button is unavailable. Neither of these issues affect the .deb version.

Running the Flatpak through the CLI gave me no useful logs, so I am not sure what the issue is.

Zorin OS Core 17.1, TIDAL-HiFi 5.15 (Flatpak)

**Comment by privacytime101** [comment]
> After I changed the password, I also encountered the problem.

Well I discovered the solution shortly after posting and I forgot to update. It looks like TIDAL might have this app flagged as suspicious, and blocks logins done through datacenter IPs. This does not happen on the official iOS app. If you use a common VPN, it will just block your login attempt and your session. I'm not sure if it was specifically the few IPs I tried that were blocked, but I'm assuming they're using one of those proper anti-VPN APIs.

My workaround was to route specifically my TIDAL DNS requests through a residential proxy, and this worked for me.

**Comment by Mastermindzh** [comment]
Hey,

Yep, we've been having loads of people report that it doesn't work while using a VPN.
Often ending in the weird error message as you two describe 😄.

> On another note, the "Continue with Google" button is unavailable. Neither of these issues affect the .deb version.

This is fully controlled by TIDAL, nothing we can do about that I'm afraid.
