### ISSUE TITLE
Wrong artist info (and double notifications) on the home page.

### ISSUE THREAD

**Issue by Mastermindzh** [Mastermindzh/tidal-hifi#45]
When on the "home" page tidal-hifi 2.2.0 will still show the wrong artist info:

![image](https://user-images.githubusercontent.com/4190290/116002054-0b994a80-a5f8-11eb-8b85-a76ad82f4db1.png)

As this doesn't happen on the other pages (search, music lists, playlist, etc) this is marked as low priority at the moment as it shouldn't really have a big impact.

PS: Going to any other page in which the artist will be fetched correctly will send out an update to correct the wrong artist name.

**Comment by yashank09** [comment]
Could I pick this and see if I can fix it by the weekend? Unless you've already started on this @Mar0xy

**Comment by Mar0xy** [comment]
> Could I pick this and see if I can fix it by the weekend? Unless you've already started on this @Mar0xy

Go ahead and try I haven't bothered trying to find a way to fix the artist stuff I had an idea in mind but didn't try it yet.

**Comment by Mastermindzh** [comment]
@yashank09 any help is welcome 😄 

If either of you wants some help feel free to ask!

**Comment by yashank09** [comment]
Sounds good! Let me look over it by the weekend and get back.

**Comment by yashank09** [comment]
Hello, could I please know how to get dev-tools opened up in the app? I tried the most common shortcuts but no luck.
 
I would definitely need a bit more time on this than compared to you both. But since this is still a low priority, I would love to try it before reassigning.

**Comment by Mastermindzh** [comment]
Hey @yashank09 ,

Sorry I had a busy weekend 😄.
In Electron you have multiple screens and each has its own devtools kit included.
To open the kit you call:

```
WINDOWNAME.webContents.openDevTools();
```

You can do this in the `app.on('ready'...` block for the mainWindow 😄 

There are about... 1000 ways to block devtools (even listen.tidal.com can do it) but the electron-code approach works flawlessly.

And don't worry about the time it takes. It's a minor issue that I'm sure most can live with. It's noticeable for sure, but usually you aren't on the home page anyway. (and the workaround is really simple...)

**Comment by Mastermindzh** [comment]
@yashank09 

Did you come around to this or would you like me to pick it up myself?

**Comment by Mastermindzh** [comment]
@yashank09, I fixed the bug myself. It was causing other problems. You can look at [this commit](https://github.com/Mastermindzh/tidal-hifi/commit/d6f63ac560a1b2e02fc7f19cb55e3de3a62242b9) to see how I have done it.

So....

Fixed in [2.2.2](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.2.1).

Use your preferred update path and enjoy!
