### ISSUE TITLE
"Your browser doesnt support the TIDAl web player"

### ISSUE THREAD

**Issue by fpedaccio** [Mastermindzh/tidal-hifi#453]
![image](https://github.com/user-attachments/assets/0e2b5413-8758-4c10-99fe-1a9b14708a96)

**Comment by Mastermindzh** [comment]
Clear your cache and try again, this happens sometimes with TIDAL 🤷🏻.
Cache is located at: `~/.config/tidal-hifi` or your package manager (e.g. flatpak)'s alternative.

If that doesn't work you are probably in a country that TIDAL doesn't like much.

**Comment by Mastermindzh** [comment]
btw, if you have been using tidal-hifi, you might want to save `config.json` before you clear cache, your tidal-hifi settings are stored there ;)
