### ISSUE TITLE
Last.fm Integration on Desktop Does Not Scrobble Songs Less than 2.5 Minutes

### ISSUE THREAD

**Issue by bradleybowman** [Mastermindzh/tidal-hifi#462]
I've noticed an issue when using the desktop application's Last.fm integration.  Songs shorter than about 2.5 minutes don't get scrobbled.  I'm not sure exactly what length the cutoff is, but it seems to be approximately 2.5 minutes.  This is especially noticeable when listening to genres with short song lengths such as some types of metal or grindcore, where entire albums don't get scrobbled because the tracks are shorter than 2 minutes.

I'm using the Tidal Hi-Fi application version 5.16.0 on Arch Linux, kernel 6.10.6.  Let me know if further information is required.  Thank you!

**Comment by Mastermindzh** [comment]
Unfortunately, we don't do anything with Last.FM integration.
It is wholly managed by TIDAL itself.

It would be wise to file a bug report with them.

**Comment by bradleybowman** [comment]
Thanks for taking a look!  I've submitted my report via tidal.com/bugreport
