### ISSUE TITLE
Discord Presence Status doesn't work

### ISSUE THREAD

**Issue by Nzubek** [Mastermindzh/tidal-hifi#464]
In the Settings you can activate the Discord Presence Status Feature, with that Feature you can show in your Discord Profile what you currently listening with TIDAL HI-FI. 

The issue is, even in the setting if everything is correctly configurated, it still won't show up in the Discord Profile.

I installed TIDAL HI-FI with Flatpak. What's weird is that over AppImage installed, works everything fine.

Reproduction:

1. Install tidal-hifi
2. Configurate the settings as seen in the screenshot
3. Notice in Discord that it won't get displayed.

![grafik](https://github.com/user-attachments/assets/586faf51-af2b-4c1c-b5a4-fcb3353845ef)

![grafik](https://github.com/user-attachments/assets/ccb29d7a-f2d8-4d66-953b-509bb8d7b317)

OS: Fedora 40
Kernel: Linux 6.10.6-200.fc40.x86_64
WM: KWin (X11)

```

zuna@fedora:~$ flatpak run com.mastermindzh.tidal-hifi
[2:0829/170134.630330:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[2:0829/170134.954357:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[2:0829/170134.954395:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
LaunchProcess: failed to execvp:
xdg-settings
Can't connect to Discord, is it running? 

```

**Comment by Mastermindzh** [comment]
Hey,

Most likely an issue with either your Discord or your Tidal-HiFi flatpak sandbox permissions.
Other Flatpak users have confirmed that it does work if you configure the sandboxes correctly. By default a lot of traffic is (obviously) blocked by the sandbox that the flatpak app runs in. (that is by flatpak's design).

See flatpak documentation for more info:
https://docs.flatpak.org/en/latest/sandbox-permissions.html
