### ISSUE TITLE
Always 0:00 time discord rich presence

### ISSUE THREAD

**Issue by aljustiet** [Mastermindzh/tidal-hifi#479]
Discord rich presence displays the timestamp wrong. It's always at 0:00.
OS: Arch/Hyprland
Version: 5.16.0 AppImage installed using [Appman](https://github.com/ivan-hc/AppMan)

**Comment by c4p741nth** [comment]
Me too
OS: Fedora 40 / KDE Plasma Wayland
Version: 5.16.0 via Flatpak

**Comment by Mastermindzh** [comment]
Fixed in 5.17.0:
https://github.com/Mastermindzh/tidal-hifi/pull/494

**Comment by aljustiet** [comment]
> Fixed in 5.17.0: #494



> Fixed in 5.17.0: #494

But now having [this](https://github.com/Mastermindzh/tidal-hifi/pull/488#issuecomment-2440559853)
