### ISSUE TITLE
"Listening to" Discord RPC

### ISSUE THREAD

**Issue by 3top1a** [Mastermindzh/tidal-hifi#487]
In the current Discord RPC implementation, the status is shown as "Playing Tidal Hi-Fi", however with [Tidal Enhanced Patcher](https://github.com/nekusu/tidal-enhanced-patcher) it's shown properly as Listening to:
![image](https://github.com/user-attachments/assets/d2e573ed-a874-4d65-a5c0-58d679471e82)

Would it be possible to improve the implementation?
According to the dev portal, it should be ([1](https://discord.com/developers/docs/rich-presence/using-with-the-embedded-app-sdk), [2](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types).)

**Comment by 3top1a** [comment]
I have created [my own fork](https://github.com/3top1a/tidal-hifi) and added the necessary code, but I can't build it (#408 maybe? I'm on Arch rn tho)

**Comment by Mastermindzh** [comment]
Fixed in https://github.com/Mastermindzh/tidal-hifi/pull/494
