### ISSUE TITLE
discord RPC not working with vesktop

### ISSUE THREAD

**Issue by pKalman00** [Mastermindzh/tidal-hifi#489]
vekstop uses arRPC, probably that's the problem, but all solutions i found so far (and used previously on fedora) are for flatpak versions, whereas i installed vesktop from the AUR and tidal from the .pacman file.

Discord RPC is enabled in tidal and arRPC is enabled in vesktop

**Comment by billbeans** [comment]
I'm having a similar problem, except in Vesktop it says I'm browsing Tidal. It doesn't say what I'm listening to

**Comment by pKalman00** [comment]
i just had a look now and it's solved on my end. i did nothing tho. i guess i'll close this issue lol
