### ISSUE TITLE
Playing past the end of the song

### ISSUE THREAD

**Issue by OuraN2O** [Mastermindzh/tidal-hifi#495]
Hello, 
When I was listening to a track it seemed like it wouldn't go to the next in the queue and when I looked the running time was exceeding the duration of the song. I manually changed track and I got the error S6007, then I changed track and it was working. 

Don't know how to reproduce, I wasn't doing anything special.

OS : Arch 6.11.5-arch1-1
DE : KDE Plasma 6.2.2, Wayland
Version of Tidal-HiFi : 5.17.0
Installed via the AUR

![image](https://github.com/user-attachments/assets/5cdbea95-e979-449e-8232-ccd35f6dc294)

**Comment by Mastermindzh** [comment]
Error S6007 is thrown by Tidal itself and for some it happens more often than others.
Nothing we can do about it unfortunately.
