### ISSUE TITLE
Problems when listening to music, sudden error S6007

### ISSUE THREAD

**Issue by spacesweedkid-27** [Mastermindzh/tidal-hifi#497]
Hello there, since the last two updates, I have gotten error S6007 after about the first 10 seconds in to any media I try to play.  
This error came up in the Linux client as well as on the Windows client. 

Regarding the name of the error, I might suspect that this error is server-side related, but I would like this note to be kept up for other users to see, so that they see that this is not your problem (hopefully I am wrong, and you can fix it) so maybe don't close it too soon :)

**Comment by Mastermindzh** [comment]
Hey,

Totally expected on Windows, see: https://github.com/Mastermindzh/tidal-hifi?tab=readme-ov-file#drm-not-working-on-windows-error-s6007

But on Linux it's not supposed to happen but sometimes it does... It usually solves itself after a while, removing config folders and cache sometimes helps too.

Also seems to happen more on the American free plan for some reason :/.

**Comment by adelavega** [comment]
same here on linux. didn't used to happen until today.

**Comment by Mastermindzh** [comment]
Glad it helped @steckums 😄 (btw, love your title, "branch master prime")!

**Comment by waltervolkers** [comment]
I did remove de config folder but no succes. Now i get, after login, direct the error S6001 !

**Comment by adelavega** [comment]
The same happened to me!

**Comment by waltervolkers** [comment]
I removed everything, reinstalled deb package and all is fine now!

**Comment by hhansen-bdai** [comment]
@steckums solution worked for me as well, installing via `.deb` on Ubuntu 22.04
