### ISSUE TITLE
App crashes after first run

### ISSUE THREAD

**Issue by dxh0w1k** [Mastermindzh/tidal-hifi#501]
Having an issue with the app crashing. It will run when its freshly installed once. After closing out of it the first time, it will freeze immediately upon reopening. The UI does not fully load, nothing is clickable, the window will stay frozen. If I try to close the window, I get an error (shown below) but I have to kill the window to get out of it. I've installed it both as a flatpak and appimage, same result in both cases. I've tried clearing user data and reinstalling multiple times - its always good for 1 session and then starts to hang/crash. 

Running Fedora 41 with KDE / Wayland, though same issue on x11 as well. 

Not sure what other information would be helpful, please let me know if I can add anything. Thanks in advance and thanks for putting this together! 

![Screenshot_20241111_180213](https://github.com/user-attachments/assets/9c8d4a01-4efe-4505-b51a-d8adcea20612)

**Comment by johann511** [comment]
I have the same problem on the same OS.  If I close the app,   I have to delete the configuration folder  .local/tidal-hifi   and relogin to my account in order to get it working again.
