### ISSUE TITLE
Profile picture button is fixed to the window

### ISSUE THREAD

**Issue by callapa1** [Mastermindzh/tidal-hifi#51]
**Working OK**
![tidal-pp](https://user-images.githubusercontent.com/54779545/117046518-10a17c80-ad11-11eb-928d-da92271d05dd.jpg)

**Button still shows in the same spot but the picture is way up**
![tidal-pp2](https://user-images.githubusercontent.com/54779545/117046519-11d2a980-ad11-11eb-9f06-de210fd6a109.jpg)

I think the pictures are self-explanatory.

The hover effect should stay on top of the picture.
I'm not sure if it's related but both are uploading buttons, not only the picture itself but also the hover effect with the pen.

**Comment by Mastermindzh** [comment]
Unfortunately, that is a bug on the Tidal website itself. You can check by looking at the actual website in a regular browser: [https://listen.tidal.com/settings](https://listen.tidal.com/settings).

You can submit a bug on the [Tidal website](https://tidal.com/bugreport).
