### ISSUE TITLE
[flatpak] sound quality switches are disabled

### ISSUE THREAD

**Issue by myyc** [Mastermindzh/tidal-hifi#519]
stuck on max for some reason. neither of the other two can be selected.

![image](https://github.com/user-attachments/assets/6fc80fad-8395-4b65-992a-1159f40b8af5)

**Comment by Mastermindzh** [comment]
Can't reproduce it. Does it happen on all songs?
Might be that the song is not available in a lower quality yet?

![image](https://github.com/user-attachments/assets/ce885b8c-7f0a-40c5-b6b5-592a91921f1a)

**Comment by myyc** [comment]
it happens on all the songs. firefox is fine. could it be a network issue which can be mitigated by adding flatpak permissions? i'm using a vpn

**Comment by myyc** [comment]
further tests:
* nothing on flatseal makes it work
* running the binary from a toolbx container (i'm using silverblue) works

**Comment by myyc** [comment]
i have uninstalled and reinstalled the app and it now works. mystery.

**Comment by apawelec** [comment]
@Mastermindzh 
I have the same problem on deb version - from my investigation controls become inactive after enabling _Block ads_ option in _General_ tab and app restart.

**Comment by apawelec** [comment]
Looks like it has been fixed in recent Tidal update - at least in my case controls are now enabled regardless of _Block ads_ setting.
