### ISSUE TITLE
Discord RP not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by abreugx** [Mastermindzh/tidal-hifi#54]
I installed it via snap and the discord rp is not working.

**Comment by NewRedsquare** [comment]
Same for me with updated Manjaro, i only have this even while playing music (tried to restart both tidal and discord same result)
![ddd](https://user-images.githubusercontent.com/38375491/119818209-7206d680-bede-11eb-9bda-dea5d606142c.png)

**Comment by Mastermindzh** [comment]
This happens because the artist info can't be gotten from the web-app.
I will fix it :)

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/120105332-c9b07680-c158-11eb-8f4c-41f00b142d7b.png)

Works again but the artist info is still missing, I'll add a fix for that too before I deploy. Hang tight.

**Comment by Mastermindzh** [comment]
Fixed in [2.2.2](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.2.1).

Use your preferred update path and enjoy!
