### ISSUE TITLE
Release on flatpak

### ISSUE THREAD

**Issue by dspacejs** [Mastermindzh/tidal-hifi#55]
This would be great, I prefer it over snap/installing from source. It will enable updates to automatically be installed.

**Comment by Mastermindzh** [comment]
I had a look and it seems it's not supported by electron-builder by default so I'd have to do quite a bit of work. I'll keep the issue open as I'm not against the release as a flatpack I just don't have the time to dedicate to it now.

Sorry 😄

**Comment by Mar0xy** [comment]
One way to release it as a flatpak is to build it with another builder like [Electron Forge](https://www.electronforge.io/config/makers/flatpak) be it via an extra branch for example.

**Comment by Mastermindzh** [comment]
@Mar0xy , any experience with forge? Seems quite mature.

I don't really mind switching build engines but as I said, low on time so it might take me a while to switch.

I'll see what (and when) I can do 😄 thanks for the heads up!

**Comment by Mar0xy** [comment]
@Mastermindzh , sadly I have no experience with forge else I would of already attempted at adding it in.
I do wanna look into it more but currently also have barely any time 😅

**Comment by bageljrkhanofemus** [comment]
https://github.com/bageljrkhanofemus/tidal-flatpak
Issues so far.
1. generated sources has a couple of missed items, so I did online builds
2. I wasn't sure what ID to give it, so I used  com.Mastermindzh.tidal
3. Discord RPC is broken
4. The icon is the wrong size to be usable, causing the current build to fail

**Comment by Mar0xy** [comment]
> https://github.com/bageljrkhanofemus/tidal-flatpak Issues so far.
> 
>     1. generated sources has a couple of missed items, so I did online builds
> 
>     2. I wasn't sure what ID to give it, so I used  com.Mastermindzh.tidal
> 
>     3. Discord RPC is broken
> 
>     4. The icon is the wrong size to be usable, causing the current build to fail

2. According to flathub's guidelines you have to use com.github.mastermindzh.tidal-hifi

3. to make discord work you have to add `--filesystem=xdg-run/app/com.discordapp.Discord:create` to finish-args and then you have to write a shell script which gets used to launch tidal hifi and put this at the beginning of the shell script followed by it starting tidal-hifi
```sh
#!/bin/sh

# Discord RPC
for i in {0..9}; do
    test -S $XDG_RUNTIME_DIR/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
done
```

**Comment by bageljrkhanofemus** [comment]
2. Done
3. Done
4. Fixed (rescaled image to 512x512 and fixed a bogus install command)
5. Mpris works now too
@Mastermindzh do you want me to transfer ownership of the flatpak repo to you?

**Comment by Mastermindzh** [comment]
@bageljrkhanofemus, 

That is up to you, I appreciate the work either way!

I can keep it updated whenever I release a new version if I'm either a co-maintainer or owner, would be pretty useful.
At some point I still want to look at Electron Forge as well to support some more options.

**Comment by bageljrkhanofemus** [comment]
I sent a request to transfer it. Here's what would be left on your end
1. Accept request and rename the repo to the app ID (I think I should have done that earlier)
2. (Optional) try to do offline builds somehow
3. Publish to flathub.
Thanks for all your work on this project!

**Comment by Mastermindzh** [comment]
@bageljrkhanofemus , I have accepted it.

I will do all of it in the weekend 😄

**Comment by Mastermindzh** [comment]
@bageljrkhanofemus,

Sorry to inform you but the transfer expired. Can you please transfer it again 😄 ?
I will register a flatpack etc in the meantime.

**Comment by Mastermindzh** [comment]
@bageljrkhanofemus, did you already follow the forking etc from here?

https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Mar0xy** [comment]
apart from the xml file being not fully completed (missing developer_name, category, oars, releases and screenshot link being broken) everything else should be fine and even if it still won't work then it's no issue since when you make a PR on flathub you also need to let their bot build the flatpak which then also gives you the errors.

You can check a proper xml file here [Anime Game Launcher Flatpak XML](https://gitlab.com/lane__/an-anime-game-launcher-flatpak/-/blob/master/com.gitlab.KRypt0n_.an-anime-game-launcher.metainfo.xml) as this was on flathub before we took it off flathub to host it on our own repo instead for more control.

**Comment by Mastermindzh** [comment]
@bageljrkhanofemus,

Please give that button a couple of flicks. GitHub sends me a url with a token which has sadly expired.

@Mar0xy,

to make a PR you need to have a fork no?

**Comment by Mar0xy** [comment]
> to make a PR you need to have a fork no?

Yes you need to fork it and put all the files into that fork this is also mentioned on the flathub's submission guide
![image](https://user-images.githubusercontent.com/8841466/163559853-fddae423-24e4-4cc9-a5ee-9acff5f77705.png)

**Comment by Mastermindzh** [comment]
I'll get to it tomorrow. Seeing as the original repo isn't a fork I will just do the fork, copy the files, credit and push 😄

**Comment by Mastermindzh** [comment]
The repo was successfully transferred now, the email states it expires in a day... kinda short 😄 :

![image](https://user-images.githubusercontent.com/4190290/163668267-acbbe2df-202b-4649-a6c2-251672bc66af.png)

Updating the required files now.

**Comment by Mastermindzh** [comment]
And now... we wait 😄.

Thanks to you both!

PS: can you tell I'm not a snap/flatpak/appimage type of guy yet? Took me a while to read all the docs 😛

**Comment by Mastermindzh** [comment]
And it has been released. Thanks to all for the help!
