### ISSUE TITLE
You have been blocked

### ISSUE THREAD

**Issue by jimmy213** [Mastermindzh/tidal-hifi#56]
When I try to log in, I keep getting this message.
![2021-06-04_14-14](https://user-images.githubusercontent.com/29613978/120793335-70bd5580-c53f-11eb-8d48-b89de1808d7d.png)

The same happens if I click on Sign Up.

P.S.: I installed the `tidal-hifi` package from AUR.

**Comment by jimmy213** [comment]
After a system restart, it worked fine. So it was a false alarm I guess.

**Comment by Mastermindzh** [comment]
Glad you got it working, enjoy the music 😄
