### ISSUE TITLE
Music doesn't play

### ISSUE THREAD

**Issue by ZyloTheGitter** [Mastermindzh/tidal-hifi#57]
I will open the app, and the first song I'll choose will play perfectly normal. But if I were to decide to skip the song, it will not play the next song. This will also occur when the song finishes and goes to the next song. Each song I try to play after I play that very first song will not play. The two ways I found to fix it was to restart the application and play or pause and wait like 20 seconds or so and the song will play fine. But then again, it works for the one song then no song will play after that in both fixes. The progress bar for the song moves but the timestamp stays at 0:00. 

Here's an image of what a song looks like when it won't play.

![image](https://user-images.githubusercontent.com/49599230/120876802-8ef37780-c578-11eb-83c9-a676421d4693.png)

**Comment by Mastermindzh** [comment]
I've had no luck reproducing this.
The way this app works is by simply loading up listen.tidal.com in a modified version of chromium.

Does listen.tidal.com work for you in a regular chromium browser? (it should work, but hifi should be disabled)

**Comment by ZyloTheGitter** [comment]
The same error happens in my chromium browser too. Is there a reason for this? Is there something wrong with my chromium installation?

It runs just fine on Firefox. So if it is my chromium installation, how can a fix this? 

Much appreciation for any help.

**Comment by Mastermindzh** [comment]
It might be something wrong, yeah. But I'd suspect it would be the system missing something or maybe even blocking something. Either way, it's not related to tidal-hifi but to listen.tidal.com and your setup. This can help us narrow the problem down.

Have you tried reinstalling chromium? Are you using pulseaudio?

**Comment by ZyloTheGitter** [comment]
Welp,

I went and reinstalled chromium and man do I feel dumb now. The problem is fixed. I don't know what was missing but it's all cleared up now. 

Thank you so much for the help even if it was as simple as that. In the future, I definitely have to troubleshoot these thing more before calling on the developer. Sorry about that.

**Comment by Mastermindzh** [comment]
Well, if you ran into a purist they would've definitely closed the issue as soon as it was confirmed not to be an issue with the software...

But I'm in this to help people, not to boost my project so I don't mind pushing people in the right direction.

As for you troubleshooting more, well... maybe... but even after days you can still miss something small anyway so asking for help is nothing to be sorry about.

Enjoy your music 😄 🎵 !
