### ISSUE TITLE
GNOME dash shortcut not being used by instances

### ISSUE THREAD

**Issue by dspacejs** [Mastermindzh/tidal-hifi#58]
If I start the app using the shortcut in the dash (I have a `.desktop` file in `~/.local/share/applications/tidal.desktop`), it creates a separate instance (instead of being nested under this shortcut in the dash).

Here's what I mean:

![Screenshot from 2021-06-08 16-03-15](https://user-images.githubusercontent.com/9282837/121134889-168bff80-c873-11eb-816d-2f95bb4ba8f4.png)

The icon with the gear is the instance of `/opt/tidal-hifi/tidal-hifi`. It's not using the TIDAL icon (which is from the `.desktop` file shortcut). 

I set up `tidal-hifi` a long time ago and it never used to do this. I can't remember how I got it working exactly. So clearly something is wrong.

I can also create multiple instances by clicking the TIDAL icon multiple times (it should only be able to launch once). 

This is the `.desktop` file:

```
[Desktop Entry]
Name=TIDAL
Exec=/opt/tidal-hifi/tidal-hifi %U
Terminal=false
Type=Application
Icon=/opt/tidal-hifi/assets/icon.png
StartupWMClass=tidal-hifi
Encoding=UTF-8
GenericName=tidal-hifi
Comment=Tidal on Electron with widevine(hifi) support
StartupNotify=true
Categories=Audio;
X-PulseAudio-Properties=media.role=music
```

## Environment

* Ubuntu 20.04.2 LTS
* GNOME 3.36.8
* Installed manually in `/opt`

**Comment by Mastermindzh** [comment]
I can check this out later today. Does this also happen with the .deb file?
Tidal-hifi can be launched as many times as you want, it isn't locked to a single instance so the fact that you can launch more than 1 isn't a problem 😄

**Comment by dspacejs** [comment]
@Mastermindzh not sure if it happens with the .deb, I only installed this manually.

I installed tidal-hifi, removed it, and reinstalled it. This happened after reinstalling it. 

> Tidal-hifi can be launched as many times as you want, it isn't locked to a single instance so the fact that you can launch more than 1 isn't a problem smile

It used to be locked to just one instance in my old installation. So if I clicked the app in the dash, it'd only launch once.

**Comment by Mastermindzh** [comment]
@dspacejs,

The gnome dash (dash-to-dock), by default, opens a single instance.
You can open more using right-click -> "new window".

Single clicking an open application only brings it into focus.

Without details on how exactly you manually installed, we won't be able to troubleshoot very well. The main thing is that your dash to dock doesn't seem to match tidal-hifi (the app) to whatever launch file (presumably the .desktop file) is used on the dash-to-dock dock. Correcting that will fix it.

As you can see, with a clean install of tidal-hifi on Ubuntu Gnome things work out of the box (in this case, I launched 2 instances using the method above, if I don't it'll keep focussing the one)

The easiest way to fix this is to undo what you did and use the prepackaged software and a software manager (either deb or snap for example). That way it will be setup automatically :)

![image](https://user-images.githubusercontent.com/4190290/121806191-2dee3280-cc4f-11eb-8e03-2310e476fbec.png)

**Comment by dspacejs** [comment]
@Mastermindzh to manually install it, I cloned the repo into `/opt/tidal-hifi` and moved the executable to `/opt/tidal-hifi/tidal-hifi` (as we discussed in another thread). Then I created `~/.local/share/applications/tidal.desktop` pointing to this, so there's now a shortcut in the dash.

I'm trying to make it to only launch one instance, not two. Why would I want to run 2 TIDAL instances? Especially if it doesn't even work (i.e due to the "Api failed to start" error you posted in your screenshot). It makes no sense, for an application like this, there should only be one instance allowed.

**Comment by Mastermindzh** [comment]
It does work (surely you have seen that?). 
You can even make it work with 2 apis, you simply have to change the port ;)

Anyway, I'll close the issue as my test concludes it is a problem with the manual install and not a problem with the software itself.
Please use one of the included installers or follow the instructions in the PKGBuild :)

**Comment by dspacejs** [comment]
@Mastermindzh I can try one of the other installers. Just confused what I did wrong, because last time I installed it manually somehow without this issue.
