### ISSUE TITLE
Availability of minimize window without shutdown the process 

### ISSUE THREAD

**Issue by Warkanlock** [Mastermindzh/tidal-hifi#59]
As the title explains, it will be nice to have that feature where you can minimize **tidal-hifi** to the program tray when hit the close button, instead of closing down the process.

I can take this feature if the author allows me, otherwise, I think it's a pretty easy feature which will be a huge boost of usability

**Comment by Mastermindzh** [comment]
I can see why this would be useful.
Feel free to add it!

Please hide it behind a setting (default: false) in the settings window as well :)

I know the Electron tutorial apps have this feature so they might be helpful to you

**Comment by Warkanlock** [comment]
On it!

**Comment by Warkanlock** [comment]
It's fully tested on my local and it works so far without breaking changes, although I spot a bug (_prior to this issue_) where the tray icon does not show the full context menu but instead only a tooltip is shown. I don't know if it's intentional or not. 

When I was working on this issue I added the full context menu on the new refresh, **but** at last I remove it, because I didn't want to take design attributions. 

**This is how it looks like when we add the full context menu (forget about the two options on the top)**
![Screenshot from 2021-06-16 08-15-10](https://user-images.githubusercontent.com/13340320/122209550-07acda80-ce7b-11eb-8637-3f42989bfeee.png)

**Comment by Mastermindzh** [comment]
Your image looks good! That's what it is supposed to do.
See the PR for more details too :)

**Comment by Warkanlock** [comment]
Excellent! I'll do it

**Comment by Mastermindzh** [comment]
Took a bit but I released it just now 😄 

https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.3.0

Have fun!
