### ISSUE TITLE
New menu for tray not working in KDE

### ISSUE THREAD

**Issue by Mar0xy** [Mastermindzh/tidal-hifi#61]
After installing the new update on my arch system which runs KDE as the DE I realized that the menu in the tray does not show up on right click all you get is the following:
![image](https://user-images.githubusercontent.com/8841466/122553382-e2190000-d037-11eb-9236-747fc19c189e.png)

**Comment by Mastermindzh** [comment]
I vaguely remember something about the system having to support the icon menu, might be wrong though.
Doesn't work for me either, but then the menu never worked for me on my personal system.

Thanks for the report!

**Comment by Mar0xy** [comment]
> I vaguely remember something about the system having to support the icon menu, might be wrong though.
> Doesn't work for me either, but then the menu never worked for me on my personal system.
> 
> Thanks for the report!

This seems wrong considering apps like Discord shouldn't show the menu then aswell when you right click the icon but it does for example.
![image](https://user-images.githubusercontent.com/8841466/122564564-cae10f00-d045-11eb-95af-eeb44c40d7fd.png)

**Comment by Mar0xy** [comment]
After looking on electron's issues I found that this issue seems to exist since 2018
[KDE plasma - tray tooltip not working](https://github.com/electron/electron/issues/12321)

**Comment by Mastermindzh** [comment]
Yeah exactly. I've had it work with custom menus before though. I guess I can eventually make one for tidal-hifi as well, would definitely be a setting then though

**Comment by licentiapoetica** [comment]
Also on KDE I noticed that the icon is very blurry with 125% scaling on my specific setup
![image](https://user-images.githubusercontent.com/51519051/164973167-5a4133f2-aed2-4294-9976-bf3bb671c7b4.png)

**Comment by Mastermindzh** [comment]
4.1.0 will fix this :) 

![tidal-menu](https://user-images.githubusercontent.com/4190290/183294163-787586d9-afa9-4638-a44c-67b9f5f63727.png)

**Comment by Mastermindzh** [comment]
Version [4.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.1.0) was just released with a fix for this issue 😄
