### ISSUE TITLE
"You have been blocked"

### ISSUE THREAD

**Issue by markojurkovic** [Mastermindzh/tidal-hifi#62]
When trying to log in to my Tidal account, I get the following:

![Screenshot from 2021-07-04 22-05-15](https://user-images.githubusercontent.com/9203900/124400789-7caa5c00-dd25-11eb-9af0-5955a0289774.png)

This is on a fresh install of Pop OS 21.04. I tried both the latest pre-built version from "Releases" as well as building from Master using NPM. Same thing happens.

**Comment by Mastermindzh** [comment]
Hey @markojurkovic ,

The app doesn't do any blocking, that's all done by Tidal itself.

You should start with checking that you aren't blocked on [listen.tidal.com](listen.tidal.com), after that make sure that there are no pc-wide (firewalls?) or network wide (things like DNS, pihole, etc) ad/js blockers.

If the problem persists, feel free to share what you learn here though.
