### ISSUE TITLE
Avoid Pipewire resampling & Tidal-hifi 

### ISSUE THREAD

**Issue by lordoff** [Mastermindzh/tidal-hifi#66]
Hi,
I'm on manjaro xfce Pahvo 21.1.3.
Runing tidal-hifi and pipewire together with great sound  from 5 months!
In last version of pipewire (from 0.3.33) is possible to set several alternative sample rates. No more fixed.
For example, default sample rate can be 96kHz, but if client play 44,1kHz, pipewire automatically switch. 
Unfortunately, I desperately trying to avoid resampling, when run tidal-hifi, but no success. 
Sample rate always stay default (96kHz in my case).
May be not related directly to tidal-hfi, but to chromium itself, no sure. In Brave & Chrome result is the same.

**Comment by BayLee4** [comment]
Did you managed to get it working in Firefox ?

**Comment by BayLee4** [comment]
Nice ! It's confirming that it is indeed a chromium engine bug, as so this issue should probably be reported [upstream](https://bugs.chromium.org/p/chromium/issues) ? (Before that and by curiosity, does enabling `enable-webrtc-pipewire-capturer` in `chrome://flags` resolve the issue ?)

**Comment by lordoff** [comment]
Thank you guys for attention! 
Yes, I just forgot to say that `enable-webrtc-pipewire-capturer` is Enabled, unfortunately issue is stay... I try the same in Brave and Chrome without success.

**Comment by Mastermindzh** [comment]
Since it is a confirmed upstream issue the only thing we can do is wait, unfortunately.
Good find tho!

**Comment by JensDA** [comment]
I've found [this upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=773302).
