### ISSUE TITLE
Blocking notifications?

### ISSUE THREAD

**Issue by Samuelfaure** [Mastermindzh/tidal-hifi#69]
I don't seem to find an easy way to block the notification when a new song starts. There doesn't seem to be a way to do it from the app.

Is that a feature to develop or did I miss something?

**Comment by Mar0xy** [comment]
Within settings is a way to turn it off 
![image](https://user-images.githubusercontent.com/8841466/140808825-92dc2db7-de82-4a1d-b49f-4b00684050d5.png)

**Comment by Samuelfaure** [comment]
I do not seem to  have this option? 

![tidal](https://user-images.githubusercontent.com/14159757/140893815-40963fe5-ab86-4ded-b3b1-c8f2e7b60ae3.gif)

**Comment by Samuelfaure** [comment]
My apologies, I just realized you could open extra setting with the shortcut Ctrl + =. Closing this.

**Comment by Mastermindzh** [comment]
No problem @Samuelfaure , glad you found out!

Thank you for answering, @Mar0xy!
