### ISSUE TITLE
notify program name

### ISSUE THREAD

**Issue by xf-** [Mastermindzh/tidal-hifi#7]
Works as expected, but no program name/icon
![image](https://user-images.githubusercontent.com/1295633/74589332-a49c0100-5004-11ea-8f9f-6870f7a44422.png)

**Comment by Mastermindzh** [comment]
Is that notify-send running under KDE?
Could you let me know what version of KDE you're running :)?

Are you using the AUR version or one of the other versions?

**Comment by xf-** [comment]
plasma v 5.18.0 and yes to AUR.

notify-send has a ~new~ argument `notify-send --app-name` and the wrapper in nodejs doesn't support it.

```
pikaur -Qi libnotify                                                                                                                                                                                                                                                 
Name            : libnotify
Version         : 0.7.8-1
```
