### ISSUE TITLE
Unable to Pause/Resume consistently 

### ISSUE THREAD

**Issue by GottaSlay** [Mastermindzh/tidal-hifi#70]
When I am trying to use my keyboard's Media Keys to pause/resume the current song. It doesn't do anything at all. Works perfectly on other music streaming platforms though.

Enabling the mpris-player setting allows me to use the media keys to pause and resume the song once... before they continue not working at all.

Using `tidal-hifi-git 2.3.0.r0.g8fea526-2` from AUR on KDE Plasma 5.23.3 under Wayland.

**Comment by Mar0xy** [comment]
I can confirm that this indeed does happen with KDE specifically as I haven't come across this issue on other DEs.

**Comment by lumpiluk** [comment]
I can confirm as well. I'm still using X11, though, and strangely pause/resume is less of a problem on my laptop than on my desktop, although still not as consistent as I'd like. I find it hard to pin down where I might have configured one system slightly different than the other.

**Comment by Mastermindzh** [comment]
Seeing as it's just with KDE I guess it's a KDE issue?
Let's keep it open in case someone finds the cause.

Definitely lots of mpris issues on KDE if you fire up a google search 🤔

**Comment by zearthur99** [comment]
For me, I can only pause the music once, and then play/pause is disabled until the next track, even in the KDE applet.

Maybe its related to https://bugs.chromium.org/p/chromium/issues/detail?id=1052609#c9? It works fine on firefox in here. 

Using firefox:
```
$ playerctl -l
firefox.instance2313
plasma-browser-integration
```

Using tidal-hifi:
```
$ playerctl -l
chromium.instance10156
tidal-hifi
```

Is there any way to add the plasma browser integration into electron? I`m guessing it can also be used to enable mpris capabilities.

**Comment by Mastermindzh** [comment]
@zearthur99 ,

Maybe try the 3.0.0 release and play around with the new "DisableHardwareMediaKeys" setting. It also disables the duplicated MPRIS client :)
