### ISSUE TITLE
why i am getting this ?

### ISSUE THREAD

**Issue by post-master** [Mastermindzh/tidal-hifi#79]
https://prnt.sc/21vloja

Cant i use it with free account ?

**Comment by Mastermindzh** [comment]
Tidal (not this app) is a paid subscription.
It usually costs either $9.99 (regular quality) or $19.99 (up to master quality), however, there is a [black-friday sale](https://tidal.com/offers/blackfriday) on right now.

Unfortunately, this message means that, for some reason, your subscription has been cancelled. (or, expired).
Nothing to do with this app though, something between you and Tidal 😄 

Good luck!

**Comment by nchristopher** [comment]
Tidal actually *does* have [a free tier](https://tidal.com/tiers/free), it was recently introduced.

@post-master - this probably means that your trial of a paid tier of TIDAL expired. You'll need to either continue paying for TIDAL, or downgrade to a free tier. You can probably find out how to do that online.

**Comment by Mastermindzh** [comment]
@nchristopher your link doesn't work for me. Might be region specific.

Would definitely welcome a free tier though!

**Comment by Mar0xy** [comment]
> @nchristopher your link doesn't work for me. Might be region specific.
> 
> Would definitely welcome a free tier though!

It indeed is currently locked to US only.
