### ISSUE TITLE
Support Media Playerback API (KDE/Plasma)

### ISSUE THREAD

**Issue by xf-** [Mastermindzh/tidal-hifi#8]
Would be a nice feature to support Media Player API.
A lot of software like vlc, spotify, plasma integration in Browser (maybe interesting for a code example)
https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/

I think this results also in support of the global media keys and start stop via plasma widget.

**Comment by Mastermindzh** [comment]
Just dropping by to say this is a good request and I'd like to add it eventually.
I'm going through a bit of a busy time so it might be a while but I'm on it!

Thanks for your support.

PS: Global media keys [should already work](https://github.com/Mastermindzh/tidal-hifi/blob/master/src/main.js#L70-L76) :)

**Comment by xf-** [comment]
@Mastermindzh my branch works more or less. I think i have a timing problem, because sometime it works and sometime it fails. I never debugged with electron and got on output in cli with `npm run start`. In docu to enable port and use chromium console as remote device (never did anything with electron before).

https://github.com/xf-/tidal-hifi/commit/405640120625d6c7b83bb52f8e8b38f76df7ab64

nodejs package
https://www.npmjs.com/package/mpris-service

result
![image](https://user-images.githubusercontent.com/1295633/74732214-0ef1b300-524a-11ea-9af7-9e25c06f7af2.png)

**Comment by resign** [comment]
Hello,
I'm on KDE Plasma and just cloned the `mediaPlayer` branch of your repository. I was unable to get the KDE Media Player to show the song that was player. I cloned @xf-'s repo, checked out the `mediaPlayer` branch and ran `npm start`. Is there a particular reason why this isn't working?

**Comment by xf-** [comment]
@resign nice catch - i wanted a sharp cover and not small one. Like i wrote - i had some issues myself.

**Comment by Mastermindzh** [comment]
Tidal deliberately doesn't buffer media it seems... that is the main issue I have with it as well (though my connection is good 99% of the time)

Thanks for the work, once my situation calmed down (moving etc) I might yet fix this KDE issue. If I end up doing so I'll credit your work.

Thanks again.
