### ISSUE TITLE
Add album to metadata (e.g. for last.fm album art)

### ISSUE THREAD

**Issue by mwllgr** [Mastermindzh/tidal-hifi#80]
Hi, I just tried to add the current album to the metadata.

Reason is, when scrobbling with rescrobbled, last.fm does not provide the album art via their API when a song is scrobbled without the album name.

However, I can't find the current album name anywhere except in the credits tab when I click on the current song. (A querySelector would work only when the "Credits" section is open, I tried it with a selector on the href="/album/...")

Any ideas? Thanks!

**Comment by Mar0xy** [comment]
The player does show the album name
![image](https://user-images.githubusercontent.com/8841466/145693152-ca691ccf-f725-4b34-8726-8083b9e2471a.png)
You just have to make sure that the href starts with /album in that element as it also shows mixes and etc and the href changes accordingly to the type iirc album is /album mix is /mix and so on

**Comment by mwllgr** [comment]
Thanks for the suggestion, @Mar0xy, however, I always need the album name. For example, as I mostly listen to playlists, this solution is not suitable for me.

**Comment by Mastermindzh** [comment]
fixed: https://github.com/Mastermindzh/tidal-hifi/pull/88
