### ISSUE TITLE
Error 404 while trying to install dependencies

### ISSUE THREAD

**Issue by drom98** [Mastermindzh/tidal-hifi#83]
When I try to run `npm install` I get the following error: `HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v16.0.4/electron-v16.0.4-linux-x64.zip`

**Comment by Mar0xy** [comment]
I just tried this and didn't run into this issue when trying it yesterday and today also considering this is an issue with electron-builder/castlabs this isn't really relevant to this project.
