### ISSUE TITLE
Assets for 2.6.0 release are 2.5.0 versions

### ISSUE THREAD

**Issue by ItsJimJams** [Mastermindzh/tidal-hifi#87]
Hi! I saw you had a new release up and went to download, but noticed all the assets in the release are labeled as version 2.5.0 and they seem to also be the exact same packages as the previous release.

Great work however!

**Comment by Mastermindzh** [comment]
It was a problem with the package number, the contents are actually 2.6.0 😄 
Release 2.7.0 fixes it regardless.

Thanks for telling me though.
