### ISSUE TITLE
Shortcut for oppening Setting on an german Keyboard.

### ISSUE THREAD

**Issue by roman-zaunidee** [Mastermindzh/tidal-hifi#91]
Hi,
the Ctrl + = is a inpossible Shortcut on a german Keyboard. At least in TKL format. Is possible to change it to something like Ctrl + 0 or so?

Also what is the Shortcut to toggle the MenuBar?

**Comment by drom98** [comment]
Thanks for pointing this out, I've just tried this and it's actually impossible with a PT-PT keyboard as well.
According to [this](https://defkey.com/tidal-desktop-shortcuts) the default shortcut should be `ctrl + p`.
> Also what is the Shortcut to toggle the MenuBar?

Currently there is no shortcut to toggle the menu bar.

**Comment by Mastermindzh** [comment]
Hey @roman-zaunidee,

I will put an item on the backlog to be able to change the shortcut. I might also set a "few" shortcuts to open the menu so other nationalities can also open it without too much of a hassle.

> Also what is the Shortcut to toggle the MenuBar?

There is none. Which together with the settings menu not being able to be opened is.. kinda bad.
I'll put an item on the backlog to set a key to open the menu.

However, there is a config file stored on your computer through which you can change all the settings, including the menubar 😄:

![image](https://user-images.githubusercontent.com/4190290/148677692-72ba39dd-afd4-4cce-a1c7-eb837efba40e.png)

It can be found in the following locations:

- Linux:  `~/.config/tidal-hifi/config.json`
- Mac OS: `~/Library/Application Support/tidal-hifi/config.json`
- Windows: `C:\Users\<your-name>\AppData\Local\tidal-hifi\config.json`

**Comment by Mastermindzh** [comment]
Released in [2.7.1](https://github.com/Mastermindzh/tidal-hifi/releases/tag/2.7.1)
