### ISSUE TITLE
Tidal snap on ubuntu does not sign in to last.fm

### ISSUE THREAD

**Issue by jbrepogmailcom** [Mastermindzh/tidal-hifi#92]
Hello when I use Tidal web interface I can sign in to last.fm without any problem. I just installed tidal-hifi from snap on Ubuntu 20.04 and if I click on "Connect to last.fm" and I allow the app on small last.fm window, nothing happens and button still shows "Connect".

**Comment by Mar0xy** [comment]
last.fm doesn't work out of the box and needs a workaround:
https://github.com/Mastermindzh/tidal-hifi/blob/master/README.md#lastfm-doesnt-work-out-of-the-box-use-rescrobbler-as-a-workaround
