### ISSUE TITLE
Uninstall from Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by biswajitpaul01** [Mastermindzh/tidal-hifi#97]
Could you please help me out uninstalling this? I am using ubuntu 20.04.

I appreciate any help you can provide.

**Comment by Mastermindzh** [comment]
@biswajitpaul01 , Sure,

How did you install it? the .deb? snap?

**Comment by biswajitpaul01** [comment]
@Mastermindzh 

Thanks for reply. I downloaded the deb installer to uninstall the application.

**Comment by Mastermindzh** [comment]
Well, that works! 

Thanks!
