### ISSUE TITLE
MPRIS integration not working

### ISSUE THREAD

**Issue by JamyGolden** [Mastermindzh/tidal-hifi#98]
I'm running Ubuntu 21.10 and the MPRIS integration isn't working (Tidal-Hifi 2.7.1). I've enabled it and restarted the app (as well as the PC) however it still doesn't work. Is this a bug or am I doing something wrong?
![Screenshot from 2022-01-31 19-32-06](https://user-images.githubusercontent.com/602472/151852046-4438e838-02a0-47ea-a84b-e415c2e8adcb.png)

**Comment by bws1** [comment]
seems similar to #70, I experience this issue as well (KDE Plasma 5.23.5)

**Comment by tp0** [comment]
If you installed the snap version, try instead the .deb install.

For me on Ubuntu, snap has had no functional mpris but .deb has.

**Comment by bws1** [comment]
> If you installed the snap version, try instead the .deb install.
> 
> For me on Ubuntu, snap install has had no functional mpris but .deb has.

using Arch Linux with the [`tidal-hifi`](https://aur.archlinux.org/packages/tidal-hifi/) AUR package

**Comment by Mastermindzh** [comment]
@JamyGolden ,

Please clarify which OS you are on and how you installed Tidal-HiFi.

Thanks!

**Comment by JamyGolden** [comment]
I'm on Ubuntu 21.10 and I installed via the snap package. I've just tried out the .deb package and the MPRIS integration works correctly with that install, so looks like a problem with the snap package.

**Comment by Mastermindzh** [comment]
Hey @JamyGolden ,

Snap kinda sandboxes your apps, if you want apps to talk to each other (or the system) you have to specify that permission during installation.
Without doing that Tidal-HiFi is basically screaming in it's own little box 😄 

Good to see that it has been solved, enjoy!
